import { FactionRuntime } from '../../config/factions/runtime/factionRuntime.js';
import { assertFactionBootAssetPolicy } from '../../config/factions/runtime/factionBootGuard.js';
import { attachFactionContextToScene } from '../../config/factions/game/mapRuntimeBridge.js';
import { installFactionUI } from './FactionUI.js';
import { installFactionSearchUI } from './FactionSearchUI.js';
import { installPlayerFactionUI } from './PlayerFactionUI.js';
import { installWorldMapFactionOverlay } from './WorldMapFactionOverlay.js';
export function installFactionSystemIntegration(MainGameScene,{network,worldAdapter,mapAdapter,gameState}={}){if(!MainGameScene?.prototype||!network)return null;const runtime=new FactionRuntime(network,{maxActive:12,minActive:5});const p=MainGameScene.prototype;if(!p.__factionSystemInstalled){p.__factionSystemInstalled=true;p.__factionRuntime=runtime;p.getFactionRuntime=()=>runtime;p.refreshFactionContext=function(mapOrIdentifier,worldNode=null){return attachFactionContextToScene(this,{network,worldAdapter,mapAdapter,mapOrIdentifier,worldNode,runtime});};p.refreshFactionContextForWorldNode=function(nodeId){this.__factionContext=network.getFactionContextForWorldNode(nodeId);return this.__factionContext;};p.getCurrentFactionContext=function(){return this.__factionContext||null;};p.getCurrentFactionControllers=function(){return this.__factionContext?.controllers||null;};p.clearFactionContext=function(){runtime.leaveTerritory();this.__factionContext=null;};p.assertFactionBootAssets=function(){return assertFactionBootAssetPolicy(this);};const oldApply=p.applyMapRuntimeConfig;if(typeof oldApply==='function'&&!p.__factionWrappedMapApply){p.__factionWrappedMapApply=true;p.applyMapRuntimeConfig=function(...args){const r=oldApply.apply(this,args);try{this.refreshFactionContext?.(this.currentMap||this.gameState?.currentMapId);}catch{}return r;};}}
 installFactionUI(MainGameScene,{network,gameState});installFactionSearchUI(MainGameScene,{network});installPlayerFactionUI(MainGameScene,{network,gameState});installWorldMapFactionOverlay(MainGameScene,{network,worldAdapter});return runtime;}
