// Ordered mobile game boot: GAME2 core first, rendering next, movement/animation ownership before skill runtime.
(()=>{'use strict';const groups=[
['https://cdn.babylonjs.com/babylon.js'],
['https://cdn.babylonjs.com/loaders/babylonjs.loaders.min.js'],
['./core/config.js','./core/logger.js','./core/lifecycle.js','./core/rng.js','./core/clock.js','./core/event-bus.js','./core/tick-scheduler.js','./core/transaction.js','./core/save-system.js','./core/validator.js','./core/game-state.js','./core/input-system.js','./core/cultivation-domain.js','./core/cultivation-system.js','./core/meditation-system.js','./core/breakthrough-system.js','./core/combat-balance.js','./core/stat-system.js','./core/entity-health.js','./core/shield-system.js','./core/combat-state-system.js','./core/heal-system.js','./core/status-system.js','./core/death-system.js','./core/damage-system.js','./core/combat-bootstrap.js','./core/skill-catalog.js','./core/cooldown-system.js','./core/skill-resource-system.js','./core/idle-progression-controller.js'],
['./assets/ui/ui-icons.js','./game.js'],
['./assets/environment/terrain/tex_01_Grass_Lush.js','./assets/environment/world/enhanced-world.js'],
['./core/player-rig-adapter.js','./core/socket-service.js','./core/player-renderer.js','./assets/characters/rigged-player.js'],
['./assets/enemies/enemy-registry.js','./assets/enemies/enemy-animation.js','./assets/enemies/enemy-loader.js','./assets/enemies/ultimate-monsters.js'],
['./core/collision-system.js','./core/player-motor.js','./core/camera-controller.js','./core/input-adapter-keyboard.js','./core/input-adapter-mobile.js','./core/player-input-controller.js','./core/facing-controller.js','./core/player-animation-state-machine.js','./core/player-animation-diagnostics.js','./core/spawn-controller.js'],
['./core/enemy-ai-system.js','./core/combat-controller.js','./core/combat-ui-adapter.js'],
['./core/spatial-query.js','./core/targeting-system.js','./core/projectile-system.js','./core/skill-effect-resolver.js','./core/skill-system.js','./core/cast-system.js','./core/projectile-renderer.js','./core/skill-ui-controller.js','./skill-vfx.js'],
['./idle-adventure.js'],
['./core/progression-service.js'],
['./progression-systems.js','./mobile-runtime.js','./mobile-minimap.js']
];const sequentialGroups=new Set([2,5,7,9]),total=groups.flat().length;let done=0,failed=false,timer;const panel=document.createElement('section');panel.id='boot-status';panel.setAttribute('role','status');panel.style.cssText='position:fixed;inset:0;z-index:100000;background:#5aa8d6;color:white;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:24px;text-align:center;font:16px system-ui';const message=document.createElement('p'),retry=document.createElement('button');retry.textContent='Tải lại game';retry.hidden=true;retry.style.cssText='padding:12px 24px;font:inherit;border-radius:12px';retry.onclick=()=>location.reload();panel.append(message,retry);document.body.appendChild(panel);const status=()=>message.textContent=`Đang tải game ${Math.min(done,total)}/${total}`;const fail=r=>{if(failed)return;failed=true;clearTimeout(timer);retry.hidden=false;message.textContent=`Không thể khởi động game: ${r}.`;try{window.GameRuntime?.engine?.stopRenderLoop()}catch(_){}};function load(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=/^https?:\/\//i.test(src)?src:`${src}?t=${Date.now()}`;s.async=false;const to=setTimeout(()=>reject(new Error('Quá thời gian tải '+src)),25000);s.onload=()=>{clearTimeout(to);done++;status();resolve()};s.onerror=()=>{clearTimeout(to);reject(new Error('Không tải được '+src))};document.head.appendChild(s)})}async function boot(){try{if('serviceWorker'in navigator){try{const r=await navigator.serviceWorker.register('./service-worker.js',{updateViaCache:'none'});await r.update();if(r.waiting)r.waiting.postMessage({type:'SKIP_WAITING'})}catch(e){console.warn('[Boot] SW',e)}}status();for(let i=0;i<groups.length;i++){const g=groups[i];if(sequentialGroups.has(i)){for(const src of g)await load(src)}else await Promise.all(g.map(load))}document.querySelectorAll('[data-ui-icon]').forEach(el=>{const p=window.UI_ICONS?.[el.dataset.uiIcon];if(p)el.src=p});const rt=window.GameRuntime;if(!rt)throw new Error('Thiếu GameRuntime');const s=window.GameServices||{};if(!s.events||!s.storage||!s.transactions||!s.cultivation||!s.damage||!s.health||!s.status||!s.skills||!s.casts||!s.cooldowns||!s.projectiles||!s.targeting||!s.input||!s.playerMotor||!s.cameraController||!s.collisions||!s.playerRenderer||!s.playerAnimation||!s.facing)throw new Error('GAME2 core/combat/skill/input/animation chưa khởi tạo đầy đủ');message.textContent='Đang dựng cảnh 3D…';timer=setTimeout(()=>fail('Cảnh 3D chưa sẵn sàng sau 30 giây'),30000);rt.scene.onAfterRenderObservable.addOnce(()=>{if(failed)return;clearTimeout(timer);panel.style.display='none'})}catch(e){fail(e.message);console.error('[Boot]',e)}}boot()})();