// Ordered mobile game boot: GAME2 core first, economy/crafting before combat stats, enemy/formation after runtime scene.
(()=>{'use strict';const groups=[
['https://cdn.babylonjs.com/babylon.js'],
['https://cdn.babylonjs.com/loaders/babylonjs.loaders.min.js'],
['./core/config.js','./core/logger.js','./core/lifecycle.js','./core/rng.js','./core/clock.js','./core/event-bus.js','./core/tick-scheduler.js','./core/transaction.js','./core/save-system.js','./core/validator.js','./core/game-state.js','./core/input-system.js','./core/cultivation-domain.js','./core/cultivation-system.js','./core/meditation-system.js','./core/breakthrough-system.js','./core/combat-balance.js','./core/stat-system.js','./core/entity-health.js','./core/shield-system.js','./core/combat-state-system.js','./core/heal-system.js','./core/status-system.js','./core/death-system.js','./core/damage-system.js','./core/economy-catalog.js','./core/phase10-catalog.js','./core/economy-state.js','./core/wallet-system.js','./core/item-system.js','./core/inventory-system.js','./core/equipment-system.js','./core/shop-system.js','./core/combat-bootstrap.js','./core/skill-catalog.js','./core/cooldown-system.js','./core/skill-resource-system.js','./core/craft-job-system.js','./core/alchemy-system.js','./core/crafting-system.js','./core/pill-system.js','./core/artifact-system.js','./core/phase10-bootstrap.js','./core/idle-progression-controller.js'],
['./assets/ui/ui-icons.js','./game.js'],
['./assets/environment/terrain/tex_01_Grass_Lush.js','./assets/environment/world/enhanced-world.js'],
['./core/player-rig-adapter.js','./core/socket-service.js','./core/player-renderer.js','./assets/characters/rigged-player.js'],
['./assets/enemies/enemy-registry.js','./assets/enemies/enemy-animation.js','./assets/enemies/enemy-loader.js'],
['./core/enemy-domain.js','./core/enemy-entity-registry.js','./core/enemy-renderer.js','./core/spawn-system.js','./core/encounter-system.js','./core/enemy-bootstrap.js','./core/enemy-ai-system.js','./core/ground-loot-system.js','./core/loot-system.js','./core/pickup-system.js','./core/economy-bootstrap.js','./core/formation-system.js','./core/world-craft-nodes.js'],
['./core/collision-system.js','./core/player-motor.js','./core/camera-controller.js','./core/input-adapter-keyboard.js','./core/input-adapter-mobile.js','./core/player-input-controller.js','./core/facing-controller.js','./core/player-animation-state-machine.js','./core/player-animation-diagnostics.js'],
['./core/combat-controller.js','./core/combat-ui-adapter.js'],
['./core/spatial-query.js','./core/targeting-system.js','./core/projectile-system.js','./core/skill-effect-resolver.js','./core/skill-system.js','./core/cast-system.js','./core/projectile-renderer.js','./core/skill-ui-controller.js','./skill-vfx.js'],
['./idle-adventure.js'],
['./core/progression-service.js','./core/economy-ui.js','./core/phase10-ui.js'],
['./progression-systems.js','./mobile-runtime.js','./mobile-minimap.js']
];const sequentialGroups=new Set([2,5,7,8,10,11]),total=groups.flat().length;let done=0,failed=false,timer;const panel=document.createElement('section');panel.id='boot-status';panel.setAttribute('role','status');panel.style.cssText='position:fixed;inset:0;z-index:100000;background:#5aa8d6;color:white;display:flex;flex-direction:column;align-items:center;justify-content:center;padding:24px;text-align:center;font:16px system-ui';const message=document.createElement('p'),retry=document.createElement('button');retry.textContent='Tải lại game';retry.hidden=true;retry.style.cssText='padding:12px 24px;font:inherit;border-radius:12px';retry.onclick=()=>location.reload();panel.append(message,retry);document.body.appendChild(panel);const status=()=>message.textContent=`Đang tải game ${Math.min(done,total)}/${total}`;const fail=r=>{if(failed)return;failed=true;clearTimeout(timer);retry.hidden=false;message.textContent=`Không thể khởi động game: ${r}.`;try{window.GameRuntime?.engine?.stopRenderLoop()}catch(_){}};function load(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=/^https?:\/\//i.test(src)?src:`${src}?t=${Date.now()}`;s.async=false;const to=setTimeout(()=>reject(new Error('Quá thời gian tải '+src)),25000);s.onload=()=>{clearTimeout(to);done++;status();resolve()};s.onerror=()=>{clearTimeout(to);reject(new Error('Không tải được '+src))};document.head.appendChild(s)})}async function boot(){try{if('serviceWorker'in navigator){try{const r=await navigator.serviceWorker.register('./service-worker.js',{updateViaCache:'none'});await r.update();if(r.waiting)r.waiting.postMessage({type:'SKIP_WAITING'})}catch(e){console.warn('[Boot] SW',e)}}status();for(let i=0;i<groups.length;i++){const g=groups[i];if(sequentialGroups.has(i)){for(const src of g)await load(src)}else await Promise.all(g.map(load))}document.querySelectorAll('[data-ui-icon]').forEach(el=>{const p=window.UI_ICONS?.[el.dataset.uiIcon];if(p)el.src=p});const rt=window.GameRuntime;if(!rt)throw new Error('Thiếu GameRuntime');const s=window.GameServices||{};if(!s.events||!s.storage||!s.transactions||!s.cultivation||!s.damage||!s.health||!s.status||!s.wallet||!s.inventory||!s.equipment||!s.items||!s.shop||!s.craftJobs||!s.alchemy||!s.crafting||!s.pills||!s.artifacts||!s.formations||!s.worldCraftNodes||!s.groundLoot||!s.loot||!s.pickup||!s.input||!s.playerMotor||!s.playerRenderer||!s.enemyDomain||!s.enemyEntities||!s.enemyRenderer||!s.spawnSystem||!s.encounters||!s.enemyAI||!s.skills||!s.casts||!s.cooldowns||!s.projectiles||!s.targeting)throw new Error('GAME2 core/economy/crafting/player/enemy/combat/skill chưa khởi tạo đầy đủ');message.textContent='Đang dựng cảnh 3D…';timer=setTimeout(()=>fail('Cảnh 3D chưa sẵn sàng sau 30 giây'),30000);rt.scene.onAfterRenderObservable.addOnce(()=>{if(failed)return;clearTimeout(timer);panel.style.display='none'})}catch(e){fail(e.message);console.error('[Boot]',e)}}boot()})();