const canvas=document.getElementById('renderCanvas');
const engine=new BABYLON.Engine(canvas,true,{preserveDrawingBuffer:true,stencil:true,adaptToDeviceRatio:true});
const scene=new BABYLON.Scene(engine);scene.clearColor=new BABYLON.Color4(.60,.82,.88,1);scene.fogMode=BABYLON.Scene.FOGMODE_LINEAR;scene.fogStart=92;scene.fogEnd=220;scene.fogColor=new BABYLON.Color3(.73,.86,.83);
const hemi=new BABYLON.HemisphericLight('sky',new BABYLON.Vector3(0,1,0),scene);hemi.intensity=1.08;const sun=new BABYLON.DirectionalLight('sun',new BABYLON.Vector3(-.5,-1,.35),scene);sun.position=new BABYLON.Vector3(70,100,-60);sun.intensity=1.25;
const shadow=new BABYLON.ShadowGenerator(1024,sun);shadow.useBlurExponentialShadowMap=true;shadow.blurKernel=18;
const CAM_BETA=1.08,CAM_RADIUS_DEFAULT=19,CAM_RADIUS_MIN=11,CAM_RADIUS_MAX=32,CAM_LOOK_AHEAD=6.4,CAM_TARGET_HEIGHT=1.55,TURN_SPEED=2.35;let cameraRadius=CAM_RADIUS_DEFAULT;
const camera=new BABYLON.ArcRotateCamera('camera',Math.PI/2,CAM_BETA,cameraRadius,new BABYLON.Vector3(0,CAM_TARGET_HEIGHT,0),scene);camera.inputs.clear();camera.panningSensibility=0;camera.lowerRadiusLimit=CAM_RADIUS_MIN;camera.upperRadiusLimit=CAM_RADIUS_MAX;camera.lowerBetaLimit=CAM_BETA;camera.upperBetaLimit=CAM_BETA;camera.fov=.64;camera.minZ=.1;camera.maxZ=420;
const mat=(name,color)=>{const m=new BABYLON.StandardMaterial(name,scene);m.diffuseColor=BABYLON.Color3.FromHexString(color);m.specularColor=new BABYLON.Color3(.06,.06,.06);return m};
const grassMat=mat('jadeGrass','#6fc94f'),pathMat=mat('ancientStone','#cbbd7a'),rockMat=mat('mountainRock','#7e896e'),cliffMat=mat('cliff','#6ea46e'),woodMat=mat('templeWood','#6b4c2d'),roofMat=mat('jadeRoof','#d8784f'),goldMat=mat('gold','#d9b45d'),redMat=mat('enemy','#9f3e38'),whiteMat=mat('robe','#e7ece9'),blueMat=mat('armor','#5da3bf'),darkMat=mat('hair','#17202b'),bladeMat=mat('blade','#9bdcff'),horseMat=mat('horse','#7d5738'),bambooMat=mat('bamboo','#5ea54a'),leafMat=mat('bambooLeaf','#78c957'),waterMat=mat('spiritWater','#67b6d2'),cloudMat=mat('cloud','#d9efe9');waterMat.alpha=.82;cloudMat.alpha=.24;
const ground=BABYLON.MeshBuilder.CreateGround('XianxiaWorld',{width:320,height:320,subdivisions:2},scene);ground.material=grassMat;ground.receiveShadows=true;
const road=BABYLON.MeshBuilder.CreateGround('HeavenRoad',{width:14,height:235,subdivisions:1},scene);road.position.set(0,.025,-42);road.material=pathMat;road.receiveShadows=true;
function mountain(x,z,r,h){const m=BABYLON.MeshBuilder.CreateCylinder('SpiritPeak',{diameterTop:r*.18,diameterBottom:r*2,height:h,tessellation:9},scene);m.position.set(x,h/2-.25,z);m.scaling.x=.7+Math.random()*.5;m.rotation.y=Math.random()*Math.PI;m.material=cliffMat;m.receiveShadows=true;return m}
[[-70,-75,25,58],[-48,-108,22,70],[-82,-132,31,82],[62,-88,28,72],[84,-128,34,92],[48,-148,22,68],[-105,-30,26,55],[108,-48,30,64],[-122,-125,38,88],[125,-145,42,96]].forEach(v=>mountain(...v));
function pagoda(x,z,s=1,levels=2){const root=new BABYLON.TransformNode('ImmortalPavilion',scene);for(let y=0;y<levels;y++){const base=BABYLON.MeshBuilder.CreateBox('hall',{width:4*s,height:1.8*s,depth:3*s},scene);base.position.set(x,1+y*2.05*s,z);base.material=woodMat;base.parent=root;shadow.addShadowCaster(base);const roof=BABYLON.MeshBuilder.CreateCylinder('curvedRoof',{diameterTop:1*s,diameterBottom:5.5*s,height:.65*s,tessellation:4},scene);roof.position.set(x,2+y*2.05*s,z);roof.rotation.y=Math.PI/4;roof.material=roofMat;roof.parent=root;shadow.addShadowCaster(roof)}return root}
pagoda(0,-122,2.3,3);pagoda(-31,-72,1.15,2);pagoda(34,-88,1.2,2);pagoda(-58,-18,.95,2);pagoda(61,-30,1.05,2);pagoda(-82,45,.9,2);pagoda(86,52,1,2);
for(let i=0;i<13;i++){const step=BABYLON.MeshBuilder.CreateBox('SectStep',{width:13,height:.22,depth:1.3},scene);step.position.set(0,.11+i*.07,-99-i*1.15);step.material=pathMat;step.receiveShadows=true}
function pillar(x,z){const p=BABYLON.MeshBuilder.CreateCylinder('GatePillar',{height:8,diameter:1.1,tessellation:8},scene);p.position.set(x,4,z);p.material=woodMat;shadow.addShadowCaster(p)}pillar(-5.2,-94);pillar(5.2,-94);const gate=BABYLON.MeshBuilder.CreateBox('SectGate',{width:13,height:.7,depth:.8},scene);gate.position.set(0,7.5,-94);gate.material=roofMat;shadow.addShadowCaster(gate);
function bamboo(x,z,s=1){const trunk=BABYLON.MeshBuilder.CreateCylinder('Bamboo',{height:5*s,diameter:.18*s,tessellation:7},scene);trunk.position.set(x,2.5*s,z);trunk.material=bambooMat;const crown=BABYLON.MeshBuilder.CreateSphere('BambooLeaves',{diameter:1.55*s,segments:6},scene);crown.position.set(x,4.65*s,z);crown.scaling.y=.55;crown.material=leafMat;shadow.addShadowCaster(trunk);return trunk}
for(let i=0;i<54;i++){const side=i%2?-1:1;const z=75-Math.random()*185;const x=side*(12+Math.random()*34);bamboo(x,z,.7+Math.random()*.55)}
for(let i=0;i<40;i++){const r=BABYLON.MeshBuilder.CreateCylinder('ScholarRock',{diameter:1.8+Math.random()*4,height:1.2+Math.random()*5,tessellation:7},scene);let x=(Math.random()-.5)*250,z=(Math.random()-.5)*250;if(Math.abs(x)<10)x+=x<0?-14:14;r.position.set(x,0,z);r.position.y=r.getBoundingInfo().boundingBox.extendSizeWorld.y;r.rotation.y=Math.random()*Math.PI;r.material=rockMat;r.receiveShadows=true}
[[-48,34,20,12],[55,15,24,14]].forEach(v=>{const w=BABYLON.MeshBuilder.CreateGround('SpiritPond',{width:v[2],height:v[3]},scene);w.position.set(v[0],.04,v[1]);w.material=waterMat});
for(let i=0;i<12;i++){const c=BABYLON.MeshBuilder.CreateSphere('MountainMist',{diameter:12+Math.random()*14,segments:8},scene);c.scaling.y=.18;c.position.set((Math.random()-.5)*230,13+Math.random()*20,-45-Math.random()*115);c.material=cloudMat}
if(typeof window.createPaintedValleyEnvironment==='function'){window.createPaintedValleyEnvironment(scene,shadow);ground.setEnabled(false);road.setEnabled(false)}
const player=new BABYLON.TransformNode('PlayerRoot',scene);player.position.set(0,0,62);player.rotation.y=Math.PI;const bodyRoot=new BABYLON.TransformNode('SkeletonRoot',scene);bodyRoot.parent=player;
function part(name,type,opt,pos,material,parent=bodyRoot){let m=type==='box'?BABYLON.MeshBuilder.CreateBox(name,opt,scene):type==='sphere'?BABYLON.MeshBuilder.CreateSphere(name,opt,scene):BABYLON.MeshBuilder.CreateCylinder(name,opt,scene);m.position.copyFrom(pos);m.material=material;m.parent=parent;shadow.addShadowCaster(m);return m}
const torso=part('Torso','box',{width:.72,height:1.05,depth:.38},new BABYLON.Vector3(0,1.55,0),whiteMat),armor=part('ArmorSocket','box',{width:.86,height:.78,depth:.48},new BABYLON.Vector3(0,1.62,0),blueMat),head=part('Head','sphere',{diameter:.48,segments:12},new BABYLON.Vector3(0,2.28,0),mat('skin','#d8b59a')),hair=part('Hair','sphere',{diameter:.53,segments:10},new BABYLON.Vector3(0,2.38,.03),darkMat);hair.scaling.y=.72;
const armL=part('ArmL','cylinder',{height:.9,diameter:.22,tessellation:8},new BABYLON.Vector3(-.52,1.55,0),whiteMat),armR=part('ArmR','cylinder',{height:.9,diameter:.22,tessellation:8},new BABYLON.Vector3(.52,1.55,0),whiteMat),legL=part('LegL','cylinder',{height:1.05,diameter:.27,tessellation:8},new BABYLON.Vector3(-.22,.58,0),darkMat),legR=part('LegR','cylinder',{height:1.05,diameter:.27,tessellation:8},new BABYLON.Vector3(.22,.58,0),darkMat);
const handSocket=new BABYLON.TransformNode('RightHandSocket',scene);handSocket.parent=bodyRoot;handSocket.position.set(.58,1.18,0);const mountSocket=new BABYLON.TransformNode('MountSocket',scene);mountSocket.parent=player;
function sword(kind=0){if(handSocket.getChildren().length)handSocket.getChildren().forEach(n=>n.dispose());const root=new BABYLON.TransformNode('Weapon',scene);root.parent=handSocket;root.rotation.z=-.2;part('Blade','box',{width:.09,height:1.3,depth:.04},new BABYLON.Vector3(0,-.55,0),kind?goldMat:bladeMat,root);part('Hilt','box',{width:.4,height:.08,depth:.09},new BABYLON.Vector3(0,.1,0),goldMat,root)}sword();
let mounted=false,mount=null,weaponKind=0,armorKind=0,beast=null;function createMount(){const root=new BABYLON.TransformNode('HorseMount',scene);root.parent=mountSocket;part('HorseBody','box',{width:.75,height:.85,depth:1.65},new BABYLON.Vector3(0,.9,0),horseMat,root);const neck=part('HorseNeck','cylinder',{height:.9,diameter:.42,tessellation:8},new BABYLON.Vector3(0,1.45,-.62),horseMat,root);neck.rotation.x=-.45;part('HorseHead','box',{width:.45,height:.45,depth:.7},new BABYLON.Vector3(0,1.82,-.95),horseMat,root);return root}function spawnBeast(){if(beast){beast.dispose();beast=null;return}beast=new BABYLON.TransformNode('SpiritBeast',scene);const bm=mat('beastMat','#7fc6d5');part('BeastBody','sphere',{diameter:.75,segments:10},new BABYLON.Vector3(0,.65,0),bm,beast);part('BeastHead','sphere',{diameter:.5,segments:10},new BABYLON.Vector3(0,1,-.42),bm,beast);beast.position=player.position.add(new BABYLON.Vector3(-1,0,1.5))}
for(let i=0;i<12;i++){const e=BABYLON.MeshBuilder.CreateCylinder('Demon',{height:1.6,diameter:.7,tessellation:8},scene);e.position.set((Math.random()-.5)*95,.8,-10-Math.random()*105);e.material=redMat;shadow.addShadowCaster(e)}
const keys={};addEventListener('keydown',e=>keys[e.key.toLowerCase()]=true);addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);let joy={x:0,y:0},joyId=null;const joystick=document.getElementById('joystick'),stick=document.getElementById('stick');function joyMove(e){const t=[...e.changedTouches].find(t=>t.identifier===joyId);if(!t)return;const r=joystick.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,dx=t.clientX-cx,dy=t.clientY-cy,max=r.width*.32,len=Math.hypot(dx,dy)||1,k=Math.min(1,max/len);joy.x=dx/max*k;joy.y=dy/max*k;stick.style.transform=`translate(${joy.x*max}px,${joy.y*max}px)`}joystick.addEventListener('touchstart',e=>{joyId=e.changedTouches[0].identifier;joyMove(e)},{passive:false});joystick.addEventListener('touchmove',e=>{e.preventDefault();joyMove(e)},{passive:false});joystick.addEventListener('touchend',()=>{joy={x:0,y:0};joyId=null;stick.style.transform=''});
let vy=0,onGround=true,attackT=0,skillT=0;const anim=document.getElementById('animState'),equip=document.getElementById('equipmentState');function pulse(type){if(type==='attack')attackT=.32;else skillT=.55}document.getElementById('attack').onclick=()=>pulse('attack');document.querySelectorAll('[data-skill]').forEach(b=>b.onclick=()=>pulse('skill'));document.getElementById('jump').onclick=()=>{if(onGround){vy=5.2;onGround=false}};document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='weapon'){weaponKind=1-weaponKind;sword(weaponKind)}if(a==='armor'){armorKind=1-armorKind;armor.material=armorKind?goldMat:blueMat}if(a==='mount'){mounted=!mounted;if(mounted&&!mount)mount=createMount();bodyRoot.position.y=mounted?1.75:0;if(mount)mount.setEnabled(mounted);b.textContent=mounted?'Xuống ngựa':'Cưỡi ngựa'}if(a==='beast')spawnBeast();equip.textContent=`${weaponKind?'Tiên kiếm':'Thanh kiếm'} • ${armorKind?'Kim Vân giáp':'Thanh Vân giáp'}${mounted?' • Đang cưỡi':''}`});
scene.onBeforeRenderObservable.add(()=>{const dt=Math.min(.033,engine.getDeltaTime()/1000);let turn=joy.x+(keys.d?1:0)-(keys.a?1:0),forward=-joy.y+(keys.w?1:0)-(keys.s?1:0);turn=BABYLON.Scalar.Clamp(turn,-1,1);forward=BABYLON.Scalar.Clamp(forward,-1,1);if(Math.abs(turn)>.04)player.rotation.y+=turn*TURN_SPEED*dt*(mounted?1.15:1);const moveSpeed=(mounted?6.5:4)*(forward<0?.72:1),facing=new BABYLON.Vector3(Math.sin(player.rotation.y),0,Math.cos(player.rotation.y)),moving=Math.abs(forward)>.05;if(moving){player.position.addInPlace(facing.scale(moveSpeed*forward*dt));player.position.x=BABYLON.Scalar.Clamp(player.position.x,-150,150);player.position.z=BABYLON.Scalar.Clamp(player.position.z,-150,150);const t=performance.now()*.012*(mounted?1.5:1);armL.rotation.x=Math.sin(t)*.55;armR.rotation.x=-Math.sin(t)*.55;legL.rotation.x=-Math.sin(t)*.55;legR.rotation.x=Math.sin(t)*.55}else{armL.rotation.x*=.82;armR.rotation.x*=.82;legL.rotation.x*=.82;legR.rotation.x*=.82}if(!onGround){player.position.y+=vy*dt;vy-=12*dt;if(player.position.y<=0){player.position.y=0;vy=0;onGround=true}}if(attackT>0){attackT-=dt;armR.rotation.z=-1.5*Math.sin((.32-attackT)/.32*Math.PI)}if(skillT>0){skillT-=dt;const s=1+Math.sin((.55-skillT)/.55*Math.PI)*.15;player.scaling.setAll(s)}else player.scaling.setAll(1);if(beast){const target=player.position.add(new BABYLON.Vector3(-1.4,0,1.5));beast.position=BABYLON.Vector3.Lerp(beast.position,target,dt*3);beast.position.y=.15+Math.sin(performance.now()*.004)*.15}camera.alpha=-player.rotation.y-Math.PI/2;camera.beta=CAM_BETA;camera.radius=cameraRadius;const targetHeight=mounted?2.35:CAM_TARGET_HEIGHT;camera.target.copyFrom(player.position.add(facing.scale(CAM_LOOK_AHEAD)).add(new BABYLON.Vector3(0,targetHeight,0)));anim.textContent=attackT>0?'Attack':skillT>0?'Skill':!onGround?'Jump':moving?(mounted?'Ride Run':'Run'):(mounted?'Ride Idle':'Idle');document.getElementById('coords').textContent=`X: ${player.position.x.toFixed(1)} Z: ${player.position.z.toFixed(1)}`});
engine.runRenderLoop(()=>scene.render());addEventListener('resize',()=>engine.resize());