(()=>{
const K='tv-prog-v1',d=Object.assign({level:1,xp:0,gear:0,skill:1,pet:1,research:1,food:0,traps:0,clatter:1,coins:0},JSON.parse(localStorage.getItem(K)||'{}'));
const save=()=>localStorage.setItem(K,JSON.stringify(d));window.SoloProgression=d;window.getProgressionPower=()=>d.gear*8+(d.skill-1)*20+d.research*2;
const hud=document.getElementById('hud'),m=document.createElement('section');m.className='system-modal';m.innerHTML='<div class="system-sheet"><header><b id="sysTitle">Hệ thống</b><button id="sysClose">×</button></header><div id="sysBody" class="system-body"></div></div>';hud.appendChild(m);const t=m.querySelector('#sysTitle'),b=m.querySelector('#sysBody');m.querySelector('#sysClose').onclick=()=>m.classList.remove('show');
function toast(x){let e=document.getElementById('lootToast');if(!e){e=document.createElement('div');e.id='lootToast';e.className='loot-toast';hud.appendChild(e)}e.textContent=x;e.classList.add('show');clearTimeout(e.h);e.h=setTimeout(()=>e.classList.remove('show'),1200)}
function gain(n){d.xp+=n;while(d.xp>=d.level*60){d.xp-=d.level*60;d.level++;d.pet=d.level}save()}
addEventListener('idle:mobWin',e=>{gain(8);d.gear++;if((d.level+e.detail.stage)%3===0)d.skill++;save();toast('Nhận trang bị tự động')});
addEventListener('idle:bossWin',e=>{gain(28);d.gear+=2;d.coins++;d.food++;if(e.detail.stage%4===0)d.traps++;save();toast('Boss rơi chiến lợi phẩm')});
function open(k){m.classList.add('show');if(k==='gear')gear();if(k==='skills')skills();if(k==='pet')pet();if(k==='bag')clatter();if(k==='cultivate')cultivate()}
document.querySelectorAll('.bottom-nav button').forEach(x=>x.onclick=()=>open(x.dataset.panel));
function gear(){t.textContent='Trang bị';b.innerHTML=`<div class="system-summary">Trang bị tự rơi khi chiến đấu và tăng sức mạnh nhân vật.</div><div class="big-stat">${d.gear} món đã thu thập</div><button id="enhanceGear">Cường hóa · 25 Linh thạch</button>`;b.querySelector('#enhanceGear').onclick=()=>{const c=window.IdleCore;if(!c||c.state.stones<25)return toast('Không đủ Linh thạch');c.state.stones-=25;d.gear++;c.save();save();gear()}}
function skills(){t.textContent='Công pháp';b.innerHTML=`<div class="system-summary">4 ô công pháp Auto Combat; Skill Cards dùng để mở và nâng kỹ năng mạnh hơn.</div><div class="big-stat">Cấp công pháp ${d.skill}</div>`}
function slots(r){let a=0,p=0;if(r>=29)a++;if(r>=38)p++;if(r>=47)p++;if(r>=64)a++;if(r>=85)p++;if(r>=98)p++;if(r>=123)p++;if(r>=136)p++;return[a,p]}
function pet(){const s=slots(d.research);t.textContent='Linh thú';b.innerHTML=`<div class="pet-card"><div class="pet-orb">獸</div><div><b>Thanh Linh Hồ</b><span>Cấp ${d.pet}</span><span>Mộc 6 · Thủy 4</span></div></div><div class="system-summary">Pet Research mở ô kỹ năng. ${s[0]} chủ động · ${s[1]} bị động.</div><button id="researchPet">Nghiên cứu ${d.research} · 40 Linh thạch</button><button id="capturePet">Bắt linh thú · Linh thiện ${d.food} · Bẫy ${d.traps}</button>`;b.querySelector('#researchPet').onclick=()=>{const c=window.IdleCore;if(!c||c.state.stones<40)return toast('Không đủ Linh thạch');c.state.stones-=40;d.research++;c.save();save();pet()};b.querySelector('#capturePet').onclick=()=>{if(!d.food||!d.traps)return toast('Cần Linh thiện và Bẫy');d.food--;d.traps--;d.pet++;save();pet();toast('Bắt linh thú thành công')}}
function clatter(){t.textContent='Pháp Ấn / Clatter';b.innerHTML=`<div class="system-summary">Clatter Cards tăng chỉ số và kích hoạt bond; tối đa 9 ô.</div><div class="big-stat">${d.clatter}/9 ô · ${d.coins} Coin</div><div class="clatter-grid">${Array.from({length:9},(_,i)=>`<i class="${i<d.clatter?'open':''}">${i<d.clatter?'印':'🔒'}</i>`).join('')}</div><button id="unlockClatter" ${d.coins<3||d.clatter>=9?'disabled':''}>Mở ô · 3 Coin</button>`;b.querySelector('#unlockClatter').onclick=()=>{if(d.coins<3||d.clatter>=9)return;d.coins-=3;d.clatter++;save();clatter()}}
function cultivate(){t.textContent='Tu luyện';b.innerHTML=`<div class="big-stat">Cấp ${d.level}</div><div class="system-summary">EXP ${Math.floor(d.xp)} / ${d.level*60}<br>Chiến lực phụ trợ +${window.getProgressionPower()}</div>`}
})();