const SW_VERSION='runtime-unified-v24';
const CORE_CACHE=`tu-tien-core-${SW_VERSION}`;
const RUNTIME_CACHE=`tu-tien-runtime-${SW_VERSION}`;
const CORE=['./','./index.html','./style.css','./skill-vfx.css','./assets/ui/ui-icons.js','./assets/ui/ui-icons.css','./assets/environment/terrain/tex_01_Grass_Lush.js','./assets/environment/world/enhanced-world.js','./assets/characters/rigged-player.js','./assets/characters/player-animation-pro.js','./assets/characters/player-upperbody-animation.js','./assets/characters/player-combat-facing.js','./assets/enemies/enemy-registry.js','./assets/enemies/enemy-animation.js','./assets/enemies/enemy-loader.js','./assets/enemies/ultimate-monsters.js','./game.js','./idle-adventure.js','./skill-vfx.js','./progression-systems.js','./mobile-runtime.js','./mobile-controls-fix.js','./manifest.webmanifest','./version.json'];
self.addEventListener('install',e=>{e.waitUntil(caches.open(CORE_CACHE).then(c=>c.addAll(CORE)).catch(()=>{}));self.skipWaiting()});
self.addEventListener('activate',e=>{e.waitUntil((async()=>{const names=await caches.keys();await Promise.all(names.filter(n=>n.startsWith('tu-tien-')&&n!==CORE_CACHE&&n!==RUNTIME_CACHE).map(n=>caches.delete(n)));await self.clients.claim()})())});
self.addEventListener('message',e=>{if(e.data&&e.data.type==='SKIP_WAITING')self.skipWaiting()});
function isStatic(u){return /\.(?:js|css|svg|png|jpg|jpeg|webp|glb|gltf|bin|woff2?)$/i.test(u.pathname)}
async function cacheFirst(req){const hit=await caches.match(req,{ignoreSearch:true});if(hit)return hit;const res=await fetch(req);if(res&&res.ok){const c=await caches.open(RUNTIME_CACHE);c.put(req,res.clone()).catch(()=>{})}return res}
async function networkFirst(req){try{const res=await fetch(new Request(req,{cache:'no-cache'}));if(res&&res.ok){const c=await caches.open(CORE_CACHE);c.put(req,res.clone()).catch(()=>{})}return res}catch(err){const hit=await caches.match(req,{ignoreSearch:true});if(hit)return hit;throw err}}
self.addEventListener('fetch',e=>{const req=e.request;if(req.method!=='GET')return;const u=new URL(req.url);if(u.origin!==self.location.origin)return;if(u.pathname.endsWith('/version.json')||req.mode==='navigate'){e.respondWith(networkFirst(req));return}if(isStatic(u)){e.respondWith(cacheFirst(req));return}e.respondWith(networkFirst(req))});