// THANH VAN TIEN VUC - ENEMY-TARGETED SKILL VFX V4
(()=>{
  const ready=()=>typeof BABYLON!=='undefined'&&typeof scene!=='undefined'&&typeof player!=='undefined';
  const junk=new Set();
  function dispose(x){try{if(x&&!x.isDisposed?.())x.dispose();}catch(_){} junk.delete(x)}
  function later(x,ms){junk.add(x);setTimeout(()=>dispose(x),ms);return x}
  function mat(n,h,a=1,e=1.5){const m=new BABYLON.StandardMaterial(n+Math.random(),scene),c=BABYLON.Color3.FromHexString(h);m.diffuseColor=c.scale(.18);m.emissiveColor=c.scale(e);m.specularColor=c;m.alpha=a;m.disableLighting=true;return m}
  function fade(m,f=20){const a=new BABYLON.Animation('fade','alpha',60,BABYLON.Animation.ANIMATIONTYPE_FLOAT,BABYLON.Animation.ANIMATIONLOOPMODE_CONSTANT);a.setKeys([{frame:0,value:m.alpha},{frame:f,value:0}]);scene.beginDirectAnimation(m,[a],0,f,false)}
  function scale(o,a,b,f=18){o.scaling.setAll(a);const x=new BABYLON.Animation('scale','scaling',60,BABYLON.Animation.ANIMATIONTYPE_VECTOR3,BABYLON.Animation.ANIMATIONLOOPMODE_CONSTANT);x.setKeys([{frame:0,value:new BABYLON.Vector3(a,a,a)},{frame:f,value:new BABYLON.Vector3(b,b,b)}]);scene.beginDirectAnimation(o,[x],0,f,false)}
  function tube(points,h,r=.055,life=300){const m=mat('bolt',h,1,1.9),t=BABYLON.MeshBuilder.CreateTube('SkillBolt',{path:points,radius:r,tessellation:6,cap:BABYLON.Mesh.CAP_ALL},scene);t.material=m;fade(m,18);later(t,life);setTimeout(()=>dispose(m),life+20);return t}
  function ring(p,h,d=2,life=460,w=.08){const m=mat('ring',h,.95,1.5),r=BABYLON.MeshBuilder.CreateTorus('SkillRing',{diameter:d,thickness:w,tessellation:36},scene);r.position=p.clone();r.position.y=.12;r.rotation.x=Math.PI/2;r.material=m;scale(r,.3,2.0,22);fade(m,22);later(r,life);setTimeout(()=>dispose(m),life+20);return r}
  function orb(p,h,d=.7,life=330){const m=mat('orb',h,.9,1.8),s=BABYLON.MeshBuilder.CreateSphere('SkillOrb',{diameter:d,segments:10},scene);s.position=p.clone();s.material=m;scale(s,.25,2,16);fade(m,18);later(s,life);setTimeout(()=>dispose(m),life+20)}
  function flash(p,h,r=6,life=180){const l=new BABYLON.PointLight('SkillFlash',p.clone(),scene);l.diffuse=BABYLON.Color3.FromHexString(h);l.intensity=6;l.range=r;later(l,life);setTimeout(()=>{if(l)l.intensity=1.5},70)}
  function label(t,h){const old=document.querySelector('.skill-cast-banner');if(old)old.remove();const e=document.createElement('div');e.className='skill-cast-banner';e.textContent=t;e.style.setProperty('--skill-color',h);document.getElementById('hud')?.appendChild(e);requestAnimationFrame(()=>e.classList.add('show'));setTimeout(()=>e.classList.remove('show'),480);setTimeout(()=>e.remove(),700)}
  function enemies(){return scene.transformNodes.filter(n=>n&&n.name&&n.name.startsWith('Mob_')&&n.isEnabled?.()!==false)}
  function targetPos(){let best=null,bd=1e9;for(const n of enemies()){const d=BABYLON.Vector3.DistanceSquared(player.position,n.position);if(d<bd){bd=d;best=n}}const p=(best?best.position:player.position).clone();p.y=Math.max(.45,p.y+.75);return p}
  function playerPos(){const p=player.position.clone();p.y+=.9;return p}
  function boltPath(a,b,j=.7,s=8){const pts=[a.clone()];for(let i=1;i<s;i++){const t=i/s;pts.push(BABYLON.Vector3.Lerp(a,b,t).add(new BABYLON.Vector3((Math.random()-.5)*j,0,(Math.random()-.5)*j)))}pts.push(b.clone());return pts}

  function thanhVan(){const a=playerPos(),b=targetPos();label('THANH VÂN KIẾM','#5ee7ff');for(let i=-1;i<=1;i++){const off=new BABYLON.Vector3(i*.28,.08,i*.08);tube([a.add(off),BABYLON.Vector3.Lerp(a,b,.55).add(new BABYLON.Vector3(i*.3,.35,-i*.2)),b.add(off)],i===0?'#e8fdff':'#42dfff',i===0?.085:.045,300)}flash(b,'#62eaff',5,170);ring(b,'#67e8f9',1.9,420,.08);orb(b,'#c7f8ff',.65,300)}
  function hoThe(){const b=targetPos();label('HỘ THỂ KIM QUANG','#ffd65a');flash(b,'#ffd24d',6,220);ring(b,'#ffd65a',2.2,500,.11);setTimeout(()=>ring(b,'#fff0a0',3.0,430,.06),70);for(let i=0;i<7;i++){const a=i/7*Math.PI*2,p=b.add(new BABYLON.Vector3(Math.cos(a)*1.15,.15+Math.sin(i)*.2,Math.sin(a)*1.15));tube([p,b],i%2?'#fff0a0':'#ffb92e',.035,280);orb(p,'#ffd86a',.22,260)}orb(b,'#fff3b0',.9,350)}
  function thienLoi(){const c=targetPos();label('THIÊN LÔI THẦN TRẢM','#b77cff');ring(c,'#7b5cff',2.5,560,.1);setTimeout(()=>ring(c,'#64e7ff',3.8,500,.06),70);const count=11;for(let i=0;i<count;i++){setTimeout(()=>{const a=i/count*Math.PI*2,r=i===0?0:.45+Math.random()*1.9,t=c.add(new BABYLON.Vector3(Math.cos(a)*r,0,Math.sin(a)*r)),top=t.add(new BABYLON.Vector3((Math.random()-.5)*.8,8.5+Math.random()*2.5,(Math.random()-.5)*.8));tube(boltPath(top,t,i===0?1:.7,9),i===0?'#ffffff':(i%2?'#a77cff':'#70e9ff'),i===0?.12:.055,340);for(let k=0;k<(i===0?4:2);k++){const e=t.add(new BABYLON.Vector3((Math.random()-.5)*2.2,.15+Math.random()*.4,(Math.random()-.5)*2.2));tube([t.clone(),BABYLON.Vector3.Lerp(t,e,.5).add(new BABYLON.Vector3((Math.random()-.5)*.4,.1,(Math.random()-.5)*.4)),e],k%2?'#70e9ff':'#b991ff',.024,220)}flash(t,i===0?'#d9c8ff':'#73e9ff',i===0?7:3.5,170);orb(t,i===0?'#eee8ff':'#c7b8ff',i===0?1.1:.5,300)},i*38)}
  function vanKiem(){const c=targetPos();label('VẠN KIẾM QUY TÔNG','#ff6b8d');flash(c,'#ff4f86',7,260);ring(c,'#ff5d85',2.8,580,.11);ring(c,'#d875ff',3.7,580,.055);const m=mat('sword','#fff1ff',.95,1.8);for(let i=0;i<14;i++){const a=i/14*Math.PI*2,start=c.add(new BABYLON.Vector3(Math.cos(a)*2.8,1.2+(i%3)*.25,Math.sin(a)*2.8)),r=new BABYLON.TransformNode('SpiritSword',scene);r.position=start;r.rotation.y=-a-Math.PI/2;const blade=BABYLON.MeshBuilder.CreateBox('Blade',{width:.06,height:.07,depth:1.1},scene);blade.parent=r;blade.material=m;const anim=new BABYLON.Animation('SwordDive','position',60,BABYLON.Animation.ANIMATIONTYPE_VECTOR3,BABYLON.Animation.ANIMATIONLOOPMODE_CONSTANT);anim.setKeys([{frame:0,value:start},{frame:18,value:c.clone()}]);scene.beginDirectAnimation(r,[anim],0,18,false);later(r,360);later(blade,360)}setTimeout(()=>{fade(m,8);dispose(m);orb(c,'#ffd9ef',1.2,350)},330)}

  function lockSkillLv1(){document.querySelectorAll('.ulala-skill-lv').forEach(e=>{if(e.textContent!=='Lv.1')e.textContent='Lv.1'});const deck=document.getElementById('skillDeck');if(deck)new MutationObserver(()=>document.querySelectorAll('.ulala-skill-lv').forEach(e=>e.textContent='Lv.1')).observe(deck,{subtree:true,childList:true,characterData:true});}
  function tuneEnemies(){
    const eng=window.ArenaMonsterEngine;if(!eng||eng.__v4Tuned)return;eng.__v4Tuned=true;
    if(Array.isArray(eng.catalog))eng.catalog.forEach(c=>{c.hpMult=(c.hpMult||1)*2.2;c.speed=(c.speed||2.4)*1.35;c.scale=(c.scale||1)*1.12;});
    const original=eng.spawnMonster3D;
    eng.spawnMonster3D=function(...args){const m=original.apply(this,args);if(!m)return m;m.speed*=1.18;m.attackCooldown=.9;m.maxHp=Math.round(m.maxHp*1.25);m.hp=m.maxHp;m.root.scaling.scaleInPlace(1.08);
      let tries=0;const beautify=setInterval(()=>{tries++;for(const mesh of m.visualMeshes||[]){try{if(!mesh.__outlined){mesh.enableEdgesRendering();mesh.edgesWidth=1.2;mesh.edgesColor=new BABYLON.Color4(.03,.04,.07,.5);mesh.__outlined=true}if(mesh.material&&mesh.material.emissiveColor)mesh.material.emissiveColor=mesh.material.emissiveColor.add(new BABYLON.Color3(.035,.035,.035));}catch(_){}}if((m.visualMeshes&&m.visualMeshes.length)||tries>12)clearInterval(beautify)},120);
      return m;};
  }

  const casts=[thanhVan,hoThe,thienLoi,vanKiem];
  function boot(){if(!ready()){setTimeout(boot,200);return}lockSkillLv1();tuneEnemies();const slots=[...document.querySelectorAll('.ulala-skill-card')];if(slots.length<4){setTimeout(boot,200);return}let last=-1,lock=false;const detect=()=>{const i=slots.findIndex(x=>x.classList.contains('active'));if(i<0||i===last||lock)return;last=i;lock=true;try{casts[i]?.()}catch(e){console.warn('SkillVFX',e)}setTimeout(()=>lock=false,100)};slots.forEach(s=>new MutationObserver(detect).observe(s,{attributes:true,attributeFilter:['class']}));window.SkillVFX={cast:i=>{try{casts[i]?.()}catch(_){}},targetPos};}
  boot();
})();