(()=>{'use strict';
function assert(name,cond){if(!cond)throw new Error(name)}
function fakeRegistry(){return{get(id){return{id,name:id,codeName:id,cat:'blob',icon:'',modelPath:`/${id}.glb`,anims:['Idle','Walk','Punch','Death'],groundOffset:0,height:1,radius:.35,colliderHeight:.8,colliderRadius:.32,attackRange:2,attackWindup:.1,hitTime:.4,recoveryTime:.7,footstepTimes:[.3,.75]}}}}
function runEnemyPipelineTests(){const out=[],test=(name,fn)=>{try{fn();out.push({name,ok:true})}catch(e){out.push({name,ok:false,error:e.message})}};
test('grade and minor map to realm without level',()=>{const d=new GameCore.EnemyDomain({registry:fakeRegistry()}),t=d.defineTemplate({id:'t',enemyId:'mob',grade:'TAM',minor:'HAU'});assert('major=2',t.majorRealmIndex===2);assert('minor=2',t.minorRealmIndex===2);assert('no level',!('level' in t))});
test('same seed produces same ecology sample',()=>{const mk=()=>new GameCore.SpawnSystem({domain:{},entities:{alive:()=>[]},renderer:{},events:null,rng:new GameCore.SeededRng('same'),clock:{now:()=>0},scheduler:null,scene:null,player:null,camera:null}),a=mk(),b=mk(),sub={center:{x:24,z:24},radius:12};const p1=a.samplePoint(sub),p2=b.samplePoint(sub);assert('same point',p1.x===p2.x&&p1.z===p2.z&&a.rngSnapshot()===b.rngSnapshot())});
test('spawn validation rejects configured safe zone and population collision',()=>{const entities={alive:()=>[{position:{x:20,z:20},template:{asset:{colliderRadius:.4}}}]},s=new GameCore.SpawnSystem({domain:{},entities,renderer:{},events:null,rng:new GameCore.SeededRng('v'),clock:{now:()=>0},scheduler:null,scene:null,player:null,camera:null});s.setEcology({zoneId:'z',safeZones:[{x:0,z:0,radius:10}],subZones:{}});assert('safe rejected',s.isValidPoint({x:0,y:0,z:0},{asset:{colliderRadius:.4}})===false);assert('collision rejected',s.isValidPoint({x:20.2,y:0,z:20.2},{asset:{colliderRadius:.4}})===false);assert('valid distant',s.isValidPoint({x:35,y:0,z:35},{asset:{colliderRadius:.4}})===true)});
test('entity registry zone unload unregisters entities',()=>{let u=0;const r=new GameCore.EnemyEntityRegistry({events:null,health:{register(){},unregister(){u++}},stats:{register(){},unregister(){u++}}}),d=new GameCore.EnemyDomain({registry:fakeRegistry()}),t=d.defineTemplate({id:'t',enemyId:'mob'});r.create(t,{zoneId:'z',home:{x:0,y:0,z:0}});r.clearZone('z');assert('cleared',r.all().length===0&&u===2)});
test('ai supports CAST state and emits telegraph timing',()=>{const emitted=[],ai=Object.create(GameCore.EnemyAISystem.prototype);ai.states=new Map();ai.clock={now:()=>1};ai.events={emit:(type,d)=>emitted.push({type,d})};ai.renderer={};ai.now=GameCore.EnemyAISystem.prototype.now;ai.state=GameCore.EnemyAISystem.prototype.state;ai.transition=GameCore.EnemyAISystem.prototype.transition;ai.animationDuration=()=>1;ai.beginAction=GameCore.EnemyAISystem.prototype.beginAction;const e={entityId:'e',state:'SPAWN',template:{asset:{hitTime:.4,recoveryTime:.7},tags:['CASTER']},renderer:{play(){}}};ai.beginAction(e,1,'CAST');assert('cast',ai.states.get('e').name==='CAST'&&emitted.some(x=>x.type==='enemy:telegraph'))});
test('encounter resets and rewards once',()=>{let removed=0,reward=0;const bus={on(){},emit(type){if(type==='encounter:rewardEligible')reward++}},spawn={spawnTemplate(){return{entityId:'boss1'}},remove(){removed++;return true}},enc=new GameCore.EncounterSystem({spawn,entities:{},events:bus,clock:{now:()=>0}});enc.define({id:'boss',bossTemplateId:'bt'});assert('start',enc.start('boss').ok);enc.reset('boss','TEST');assert('removed',removed===1);enc.start('boss');enc.onDeath({entityId:'boss1'});enc.onDeath({entityId:'boss1'});assert('reward once',reward===1&&enc.completed.has('boss'))});
test('animation resolver falls back semantically',()=>{const c=new EnemyAnimationController([{name:'Idle'},{name:'Punch'}]);assert('attack alias',c.resolveAnimName('attack')==='punch');assert('death missing',c.resolveAnimName('death')===null)});
return{ok:out.every(x=>x.ok),results:out}}window.runEnemyPipelineTests=runEnemyPipelineTests;})();
