(()=>{'use strict';
function assert(name,cond){if(!cond)throw new Error(name)}
function fakeRegistry(){return{get(id){return{id,name:id,codeName:id,cat:id.includes('fly')?'flying':'blob',icon:'',modelPath:`/${id}.glb`,anims:['Idle','Walk','Punch','Death'],groundOffset:0,height:1,radius:.35,colliderHeight:.8,colliderRadius:.32,attackRange:2,attackWindup:.1,hitTime:.4,recoveryTime:.7,footstepTimes:[.3,.75]}}}}
function runEnemyPipelineTests(){const out=[],test=(name,fn)=>{try{fn();out.push({name,ok:true})}catch(e){out.push({name,ok:false,error:e.message})}};
test('grade and minor map to realm without level',()=>{const d=new GameCore.EnemyDomain({registry:fakeRegistry()}),t=d.defineTemplate({id:'t',enemyId:'mob',grade:'TAM',minor:'HAU'});assert('major=2',t.majorRealmIndex===2);assert('minor=2',t.minorRealmIndex===2);assert('no level',!Object.prototype.hasOwnProperty.call(t,'level'))});
test('same seed produces same ecology sample',()=>{const mk=()=>new GameCore.SpawnSystem({domain:{},entities:{},renderer:{},events:null,rng:new GameCore.SeededRng('same'),clock:{now:()=>0},scheduler:null,scene:null,player:null}),a=mk(),b=mk(),sub={center:{x:4,z:7},radius:12};const p1=a.samplePoint(sub),p2=b.samplePoint(sub);assert('same x',p1.x===p2.x);assert('same z',p1.z===p2.z);assert('same rng snapshot',a.rngSnapshot()===b.rngSnapshot())});
test('entity registry zone unload unregisters entities',()=>{let u=0;const r=new GameCore.EnemyEntityRegistry({events:null,health:{register(){},unregister(){u++}},stats:{register(){},unregister(){u++}}}),d=new GameCore.EnemyDomain({registry:fakeRegistry()}),t=d.defineTemplate({id:'t',enemyId:'mob'});r.create(t,{zoneId:'z',home:{x:0,y:0,z:0}});assert('before',r.all().length===1);r.clearZone('z');assert('after',r.all().length===0);assert('unregistered',u===2)});
test('ai state transition supports full FSM names',()=>{const ai=Object.create(GameCore.EnemyAISystem.prototype);ai.states=new Map();ai.clock={now:()=>1};ai.events={emit(){}};ai.now=GameCore.EnemyAISystem.prototype.now;const e={entityId:'e',state:'SPAWN'};ai.state=GameCore.EnemyAISystem.prototype.state;ai.transition=GameCore.EnemyAISystem.prototype.transition;assert('alert',ai.transition(e,'ALERT'));assert('name',ai.states.get('e').name==='ALERT');assert('reject bad',ai.transition(e,'NOT_A_STATE')===false)});
test('encounter resets without timer and reward only once on boss death',()=>{let removed=0,reward=0;const bus={on(){},emit(type){if(type==='encounter:rewardEligible')reward++}},spawn={spawnTemplate(){return{entityId:'boss1'}},remove(){removed++;return true}},enc=new GameCore.EncounterSystem({spawn,entities:{},events:bus,clock:{now:()=>0}});enc.define({id:'boss',bossTemplateId:'bt'});assert('start',enc.start('boss').ok);assert('active',enc.isActive('boss'));enc.reset('boss','TEST');assert('removed',removed===1);assert('start2',enc.start('boss').ok);enc.onDeath({entityId:'boss1'});enc.onDeath({entityId:'boss1'});assert('reward once',reward===1);assert('complete',enc.completed.has('boss'))});
test('animation resolver falls back semantically and reports missing safely',()=>{const idle={name:'Idle'},attack={name:'Punch'},c=new EnemyAnimationController([idle,attack]);assert('attack alias',c.resolveAnimName('attack')==='punch');assert('death missing',c.resolveAnimName('death')===null)});
return{ok:out.every(x=>x.ok),results:out}}
window.runEnemyPipelineTests=runEnemyPipelineTests;
})();