(()=>{'use strict';function assert(n,c){if(!c)throw new Error(n)}
function runPhase10Tests(){const out=[],test=(n,f)=>{try{f();out.push({name:n,ok:true})}catch(e){out.push({name:n,ok:false,error:e.message})}};const s=GameServices,c=GameCore.phase10Catalog;
test('alchemy covers pill grade 1-5 and four qualities',()=>{const g=[...new Set(Object.values(c.RECIPES).filter(x=>x.system==='ALCHEMY').map(x=>x.grade))].sort();assert('grades',JSON.stringify(g)==='[1,2,3,4,5]');assert('qualities',c.QUALITY.join(',')==='HA,TRUNG,THUONG,CUC')});
test('reservation blocks double spend',()=>{const inv=s.inventory;const base=inv.state().stacks.spirit_dust||0;inv.state().stacks.spirit_dust=10;const k='phase10_test_reserve';inv.release(k);assert('reserve',inv.reserveResources(k,[{baseId:'spirit_dust',quantity:8}]).ok);assert('available',inv.availableStack('spirit_dust')===2);assert('second spend blocked',!inv.reserveResources(k+'2',[{baseId:'spirit_dust',quantity:3}]).ok);inv.release(k);inv.release(k+'2');inv.state().stacks.spirit_dust=base;inv.store.save()});
test('mid-job save persists deterministic seed/timestamps',()=>{const st=s.economyStore.state.crafting;const id='test_mid_job',before=st.jobs[id];st.jobs[id]={jobId:id,recipeId:'heal_pill_g1',seed:'fixed-seed',state:'RUNNING',startedAt:100,completesAt:200,reservationKey:'x'};s.economyStore.save();const snap=s.economyStore.snapshot().crafting.jobs[id];assert('seed',snap.seed==='fixed-seed');assert('times',snap.startedAt===100&&snap.completesAt===200);if(before)st.jobs[id]=before;else delete st.jobs[id];s.economyStore.save()});
test('offline completion is timestamp based',()=>{const J=GameCore.CraftJobSystem,j=Object.create(J.prototype);j.store={state:{crafting:{serial:0,jobs:{a:{jobId:'a',state:'RUNNING',completesAt:10}}}},save(){}};j.events={emit(){}};j.ensureState=J.prototype.ensureState;J.prototype.update.call(j,11);assert('ready',j.store.state.crafting.jobs.a.state==='READY')});
test('claim full inventory is rejected without claim mutation',()=>{const h=s.craftJobs.handlers.get('CRAFTING'),job={outcome:{success:true}},recipe={action:'CREATE'};const old=s.inventory.hasSpace;s.inventory.hasSpace=()=>false;const v=h.validate(job,recipe);s.inventory.hasSpace=old;assert('full',v.ok===false&&v.reason==='INVENTORY_FULL')});
test('double claim is idempotent by persisted job state',()=>{const J=GameCore.CraftJobSystem,j=Object.create(J.prototype);j.get=()=>({jobId:'x',state:'CLAIMED',claimed:true});j.update=()=>{};const r=J.prototype.claim.call(j,'x');assert('idempotent',r.ok&&r.idempotent)});
test('artifact suppression disables passive and active',()=>{const a=s.artifacts,oldStatus=a.status,oldEq=a.state.equipped;a.status={hasTag:()=>true};assert('passive off',Object.keys(a.statBonuses()).length===0);assert('active blocked',a.activate().reason==='ARTIFACT_SUPPRESSED');a.status=oldStatus;a.state.equipped=oldEq});
test('formation unload/reload preserves placement state',()=>{const f=s.formations,id='formation_test_persist',old=f.state.placements[id];f.state.placements[id]={id,baseId:'spirit_gathering_plate',zoneId:'z',position:{x:1,y:0,z:1},active:true,item:{instanceId:'i'}};f.unloadVisuals('z');assert('still persisted',!!f.state.placements[id]);if(old)f.state.placements[id]=old;else delete f.state.placements[id]});
test('actual world station contexts exist',()=>{assert('furnace',s.worldCraftNodes.context('bronze_furnace_node')?.type==='FURNACE');assert('forge',s.worldCraftNodes.context('forge_node')?.type==='FORGE');assert('formation',s.worldCraftNodes.context('formation_table_node')?.type==='FORMATION_TABLE')});
return{ok:out.every(x=>x.ok),results:out}}window.runPhase10Tests=runPhase10Tests;})();