(()=>{'use strict';
class ArtifactSystem{
 constructor({store=window.GameServices?.economyStore,inventory=window.GameServices?.inventory,items=window.GameServices?.items,status=window.GameServices?.status,shields=window.GameServices?.shields,events=window.GameServices?.events,clock=window.GameServices?.clock,catalog=window.GameCore?.phase10Catalog}={}){Object.assign(this,{store,inventory,items,status,shields,events,clock,catalog});const s=store.state;s.artifacts=s.artifacts||{equipped:null,lastActiveAt:{}};this.state=s.artifacts;events?.on?.('status:applied',d=>{if(d?.entityId==='player'&&(d.tags||[]).includes('ARTIFACT_SUPPRESSED'))this.events?.emit?.('artifact:suppressionChanged',{suppressed:true})},{owner:'ArtifactSystem'});events?.on?.('status:removed',d=>{if(d?.entityId==='player')this.events?.emit?.('artifact:suppressionChanged',{suppressed:this.isSuppressed()})},{owner:'ArtifactSystem'})}
 isSuppressed(){return !!this.status?.hasTag?.('player','ARTIFACT_SUPPRESSED')}
 equip(instanceId){const i=this.inventory.state().instances[instanceId],d=this.catalog.ARTIFACT_DEFS[i?.baseId];if(!i||!d)return{ok:false,reason:'NOT_ARTIFACT'};if(this.inventory.isReservedInstance(instanceId))return{ok:false,reason:'ITEM_RESERVED'};this.state.equipped=instanceId;this.store.save();this.events?.emit?.('artifact:equipped',{instanceId});return{ok:true}}
 unequip(){const id=this.state.equipped;this.state.equipped=null;this.store.save();this.events?.emit?.('artifact:unequipped',{instanceId:id});return{ok:true}}
 equipped(){const i=this.inventory.state().instances[this.state.equipped];return i||null}
 statBonuses(){if(this.isSuppressed())return{};const i=this.equipped(),d=this.catalog.ARTIFACT_DEFS[i?.baseId];return d?{...d.passiveStats}:{}}
 activate(){if(this.isSuppressed())return{ok:false,reason:'ARTIFACT_SUPPRESSED'};const i=this.equipped(),d=this.catalog.ARTIFACT_DEFS[i?.baseId];if(!i||!d?.active)return{ok:false,reason:'NO_ACTIVE_ARTIFACT'};const now=this.clock?.now?.()||0,last=this.state.lastActiveAt[i.instanceId]||-1e9;if(now-last<d.active.cooldown)return{ok:false,reason:'COOLDOWN',remaining:d.active.cooldown-(now-last)};this.state.lastActiveAt[i.instanceId]=now;this.store.save();this.shields?.add?.('player',{amount:d.active.shield,duration:d.active.duration,sourceEntityId:'player',tags:['ARTIFACT']});this.status?.apply?.('player',{id:'ARTIFACT_ACTIVE',category:'BUFF',duration:d.active.duration,tags:['ARTIFACT_ACTIVE']});this.events?.emit?.('artifact:activated',{instanceId:i.instanceId,baseId:i.baseId});return{ok:true}}
}
window.GameCore=window.GameCore||{};window.GameCore.ArtifactSystem=ArtifactSystem;window.GameCore.artifacts=window.GameCore.artifacts||new ArtifactSystem();window.GameServices=Object.assign(window.GameServices||{},{artifacts:window.GameCore.artifacts});
})();