(()=>{'use strict';
class CollisionSystem{
 constructor({scene=window.GameRuntime?.scene,player=window.GameRuntime?.player}={}){this.scene=scene;this.player=player;this.radius=.42;this.halfHeight=.9;this.stepHeight=.38;this.maxSlopeCos=Math.cos(50*Math.PI/180);this.groundProbe=3.5}
 blocker(mesh){if(!mesh||mesh.isDisposed?.()||mesh===this.player)return false;const md=mesh.metadata||{};if(md.isEnemy||md.isPlayer)return false;return md.playerBlocker===true||mesh.checkCollisions===true}
 ground(mesh){if(!mesh||mesh.isDisposed?.())return false;const md=mesh.metadata||{};if(md.isEnemy||md.isPlayer||md.noPlayerGround)return false;return md.playerGround===true||mesh.checkCollisions===true||/ground|terrain|road/i.test(mesh.name||'')}
 rayBlocked(from,to,yOffset=this.halfHeight){if(typeof BABYLON==='undefined'||!this.scene)return false;const dx=to.x-from.x,dz=to.z-from.z,dist=Math.hypot(dx,dz);if(dist<1e-5)return false;const origin=new BABYLON.Vector3(from.x,from.y+yOffset,from.z),dir=new BABYLON.Vector3(dx,0,dz).normalize(),ray=new BABYLON.Ray(origin,dir,dist+this.radius);const hit=this.scene.pickWithRay(ray,m=>this.blocker(m),false);return !!hit?.hit&&hit.distance<=dist+this.radius}
 sampleGround(pos){if(typeof BABYLON==='undefined'||!this.scene)return{ok:true,y:pos.y,normalY:1};const origin=new BABYLON.Vector3(pos.x,pos.y+this.groundProbe*.55,pos.z),ray=new BABYLON.Ray(origin,new BABYLON.Vector3(0,-1,0),this.groundProbe);const hit=this.scene.pickWithRay(ray,m=>this.ground(m),false);if(!hit?.hit||!hit.pickedPoint)return{ok:true,y:pos.y,normalY:1};const n=hit.getNormal?.(true)||new BABYLON.Vector3(0,1,0);return{ok:n.y>=this.maxSlopeCos,y:hit.pickedPoint.y,normalY:n.y}}
 resolveMove(current,desired){const cur={x:Number(current.x)||0,y:Number(current.y)||0,z:Number(current.z)||0},dst={x:Number(desired.x)||0,y:Number(desired.y)||0,z:Number(desired.z)||0};let out={...dst},blocked=false;if(this.rayBlocked(cur,dst)){blocked=true;const xOnly={x:dst.x,y:cur.y,z:cur.z},zOnly={x:cur.x,y:cur.y,z:dst.z};const bx=this.rayBlocked(cur,xOnly),bz=this.rayBlocked(cur,zOnly);if(!bx)out=xOnly;else if(!bz)out=zOnly;else{const stepped={x:dst.x,y:cur.y+this.stepHeight,z:dst.z};if(!this.rayBlocked({...cur,y:cur.y+this.stepHeight},stepped,this.halfHeight*.75))out=stepped;else out={...cur}}}const g=this.sampleGround(out);if(g.ok&&Number.isFinite(g.y))out.y=g.y;else{out={...cur};blocked=true}return{position:out,blocked,grounded:true,normalY:g.normalY}}
}
window.GameCore=window.GameCore||{};window.GameCore.CollisionSystem=CollisionSystem;window.GameCore.collisions=window.GameCore.collisions||new CollisionSystem();window.GameServices=Object.assign(window.GameServices||{},{collisions:window.GameCore.collisions});
})();