(()=>{'use strict';
const qualityOrder=['HA','TRUNG','THUONG','CUC'];
class CraftingSystem{
 constructor({jobs=window.GameServices?.craftJobs,inventory=window.GameServices?.inventory,items=window.GameServices?.items,store=window.GameServices?.economyStore,catalog=window.GameCore?.phase10Catalog}={}){Object.assign(this,{jobs,inventory,items,store,catalog});jobs?.registerHandler?.('CRAFTING',{validate:(j,r)=>this.validateClaim(j,r),apply:(j,r)=>this.applyClaim(j,r)})}
 recipes(){return Object.values(this.catalog.RECIPES).filter(r=>r.system==='CRAFTING')}
 start(recipeId,station,metadata={}){const r=this.catalog.RECIPES[recipeId];if(r?.system!=='CRAFTING')return{ok:false,reason:'NOT_CRAFT_RECIPE'};return this.jobs.start(recipeId,{station,metadata})}
 preview(recipeId){const r=this.catalog.RECIPES[recipeId];return r?{recipeId:r.id,name:r.name,inputs:r.inputs,output:r.output,duration:r.duration,successChance:r.successChance,stationType:r.stationType}:null}
 operation(action,targetInstanceId,station){const item=this.inventory.state().instances[targetInstanceId];if(!item)return{ok:false,reason:'ITEM_MISSING'};const id={ENHANCE:'enhance_item',REFINE:'refine_item',REFORGE:'reforge_item',SALVAGE:'salvage_item'}[String(action).toUpperCase()];return id?this.jobs.start(id,{station,targetInstanceId}):{ok:false,reason:'UNKNOWN_OPERATION'}}
 validateClaim(j,r){if(!j.outcome.success&&r.action==='CREATE')return{ok:true};if(r.action==='CREATE')return{ok:this.inventory.hasSpace(1),reason:'INVENTORY_FULL'};return{ok:!!this.inventory.state().instances[j.targetInstanceId],reason:'TARGET_MISSING'}}
 applyClaim(j,r){if(r.action==='CREATE'){if(!j.outcome.success)return{ok:true,success:false,reason:'CRAFT_FAILED_SAFE'};const item=this.items.createInstance(r.output.baseId,{seed:j.seed,quality:j.outcome.quality});const a=this.inventory.addInstanceDirect(item);return a.ok?{ok:true,success:true,item}:{ok:false,reason:a.reason}}const item=this.inventory.state().instances[j.targetInstanceId];if(!item)return{ok:false,reason:'TARGET_MISSING'};if(!j.outcome.success)return{ok:true,success:false,reason:'OPERATION_FAILED_SAFE',instanceId:item.instanceId};if(r.action==='ENHANCE')item.enhancement=Math.min(15,(Number(item.enhancement)||0)+1);else if(r.action==='REFINE'){const i=Math.min(3,Math.max(0,qualityOrder.indexOf(item.quality)));item.quality=qualityOrder[Math.min(3,i+1)]}else if(r.action==='REFORGE'){const rng=new GameCore.SeededRng(j.seed+':affix'),pool=Object.keys(GameCore.economyCatalog.AFFIXES),pick=rng.pick(pool);item.affixes=pick?[pick]:[]}else if(r.action==='SALVAGE'){delete this.inventory.state().instances[item.instanceId];this.inventory.state().stacks.artifact_shard=(Number(this.inventory.state().stacks.artifact_shard)||0)+2}this.store.save();return{ok:true,success:true,instanceId:item.instanceId,action:r.action}}
 enhance(id,station){return this.operation('ENHANCE',id,station)}refine(id,station){return this.operation('REFINE',id,station)}reforge(id,station){return this.operation('REFORGE',id,station)}salvage(id,station){return this.operation('SALVAGE',id,station)}claim(id){return this.jobs.claim(id)}
}
window.GameCore=window.GameCore||{};window.GameCore.CraftingSystem=CraftingSystem;window.GameCore.crafting=window.GameCore.crafting||new CraftingSystem();window.GameServices=Object.assign(window.GameServices||{},{crafting:window.GameCore.crafting});
})();