(()=>{'use strict';
const TYPES=new Set(['PHYSICAL','METAL','WOOD','WATER','FIRE','EARTH','WIND','LIGHTNING']);
class DamageSystem{
 constructor({health,stats,shields,status,death,combatState,events,rng,balance,counters,logger}={}){Object.assign(this,{health,stats,shields,status,death,combatState,events,rng,balance,counters,logger});this.serial=0}
 realmRule(source,target,request={}){if(!target)return{delta:0,multiplier:1,lethalFloor:0};if(!source){if(request.realmPolicy==='UNSUPPRESSED_ENVIRONMENT')return{delta:0,multiplier:1,lethalFloor:0};source={majorRealmIndex:Math.max(0,Number(request.attackerMajorRealmIndex)||0)}}const delta=(Number(target.majorRealmIndex)||0)-(Number(source.majorRealmIndex)||0),r=this.balance.realmSuppression;if(delta<=0)return{delta,multiplier:r.equalOrLower.multiplier,lethalFloor:0};if(delta===1)return{delta,multiplier:r.plus1.multiplier,lethalFloor:r.plus1.lethalFloor};if(delta===2)return{delta,multiplier:r.plus2.multiplier,lethalFloor:r.plus2.lethalFloor};return{delta,multiplier:r.plus3.multiplier,lethalFloor:r.plus3.lethalFloor}}
 elementMultiplier(type,targetType=null){if(!targetType||!this.counters[type])return 1;if(this.counters[type]===targetType)return this.balance.elementAdvantage;if(this.counters[targetType]===type)return this.balance.elementDisadvantage;return 1}
 resolve(req={}){const requestId=req.requestId||`dmg_${++this.serial}`,targetId=String(req.targetEntityId||''),sourceId=req.sourceEntityId==null?null:String(req.sourceEntityId),target=this.health.get(targetId),source=sourceId?this.health.get(sourceId):null;if(!targetId||!target||!target.alive)return{ok:false,requestId,reason:'INVALID_TARGET'};if(this.status?.has(targetId,'RESPAWN_INVULNERABLE')||this.status?.has(targetId,'INVULNERABLE'))return{ok:true,requestId,sourceEntityId:sourceId,targetEntityId:targetId,finalDamage:0,blocked:'INVULNERABLE',currentHP:target.currentHP,maxHP:target.maxHP};const type=TYPES.has(String(req.damageType||'PHYSICAL').toUpperCase())?String(req.damageType||'PHYSICAL').toUpperCase():'PHYSICAL',ss=sourceId?this.stats.get(sourceId):{},ts=this.stats.get(targetId),tags=new Set(req.tags||[]);let raw=Math.max(0,Number(req.baseAmount)||0);raw*=1+(Number(ss.damageBonuses?.[type])||0);let crit=false;if(req.canCrit&&sourceId){const chance=Math.max(0,Math.min(1,Number(req.critChance??ss.critChance)||0));if((this.rng?.next?.()||0)<chance){crit=true;raw*=Math.max(1,Number(req.critMultiplier??ss.critMultiplier)||1.5)}}const element=this.elementMultiplier(type,req.targetElement||null);let afterElement=raw*element,afterDefense=afterElement;if(!tags.has('TRUE')){if(type==='PHYSICAL'){const d=Math.max(0,Number(ts.defense)||0);afterDefense*=this.balance.defenseK/(this.balance.defenseK+d)}else{const resist=Math.max(this.balance.resistanceMin,Math.min(this.balance.resistanceMax,Number(ts.resistances?.[type])||0));afterDefense*=1-resist}}const realm=this.realmRule(source,target,req);let afterRealm=afterDefense*realm.multiplier;const shield=this.shields?.absorb(targetId,afterRealm,type)||{remaining:afterRealm,absorbed:0};let finalDamage=shield.remaining;if(realm.lethalFloor>0&&target.currentHP-finalDamage<realm.lethalFloor)finalDamage=Math.max(0,target.currentHP-realm.lethalFloor);const before=target.currentHP,snap=this.health.applyDamage(targetId,finalDamage),applied=before-(snap?.currentHP??before);if(sourceId&&applied>0){this.combatState?.mark(sourceId,targetId);this.combatState?.mark(targetId,sourceId)}const result={ok:true,requestId,sourceEntityId:sourceId,targetEntityId:targetId,sourceType:req.sourceType||'GENERIC',damageType:type,rawDamage:raw,elementMultiplier:element,afterDefense,realmDelta:realm.delta,realmMultiplier:realm.multiplier,lethalFloor:realm.lethalFloor,shieldAbsorbed:shield.absorbed,finalDamage:applied,crit,currentHP:snap.currentHP,maxHP:snap.maxHP,tags:[...tags]};this.events?.emit('damage:resolved',result);if(snap.currentHP<=0)this.death?.die(targetId,{request:result});return result}
}
window.GameCore=window.GameCore||{};window.GameCore.DamageSystem=DamageSystem;window.GameCore.damage=window.GameCore.damage||new DamageSystem({health:window.GameCore.health,stats:window.GameCore.stats,shields:window.GameCore.shields,status:window.GameCore.status,death:window.GameCore.death,combatState:window.GameCore.combatState,events:window.GameCore.events,rng:window.GameCore.rng,balance:window.GameCore.combatBalance,counters:window.GameCore.elementCounters,logger:window.GameCore.logger});window.GameServices=Object.assign(window.GameServices||{}, {stats:window.GameCore.stats,health:window.GameCore.health,shields:window.GameCore.shields,status:window.GameCore.status,heal:window.GameCore.heal,death:window.GameCore.death,combatState:window.GameCore.combatState,damage:window.GameCore.damage});
})();