(()=>{'use strict';
class EncounterSystem{
 constructor({spawn=window.GameServices?.spawnSystem,entities=window.GameServices?.enemyEntities,events=window.GameServices?.events,clock=window.GameServices?.clock}={}){Object.assign(this,{spawn,entities,events,clock});this.defs=new Map();this.active=new Map();this.completed=new Set();events?.on?.('entity:died',d=>this.onDeath(d),{owner:'EncounterSystem'})}
 define(def={}){if(!def.id||!def.bossTemplateId)throw new Error('Encounter requires id and bossTemplateId');const x=Object.freeze({id:def.id,name:def.name||def.id,bossTemplateId:def.bossTemplateId,zoneId:def.zoneId||'thanh_van_region',subZoneId:def.subZoneId||'boss_area',position:{...(def.position||{x:0,y:0,z:0})},resetPolicy:def.resetPolicy||'ON_PLAYER_DEATH',repeatable:!!def.repeatable,lootOnce:def.lootOnce!==false});this.defs.set(x.id,x);return x}
 start(id){const def=this.defs.get(String(id));if(!def)return{ok:false,reason:'UNKNOWN_ENCOUNTER'};if(this.active.has(def.id))return{ok:false,reason:'ALREADY_ACTIVE'};if(this.completed.has(def.id)&&!def.repeatable)return{ok:false,reason:'COMPLETED'};const boss=this.spawn?.spawnTemplate?.(def.bossTemplateId,{zoneId:def.zoneId,subZoneId:def.subZoneId,position:{...def.position},spawnPointId:`encounter_${def.id}`,metadata:{encounterId:def.id,boss:true}});if(!boss)return{ok:false,reason:'SPAWN_FAILED'};this.active.set(def.id,{def,bossEntityId:boss.entityId,startedAt:this.clock?.now?.()||0,lootGranted:false,state:'ACTIVE'});this.events?.emit?.('encounter:started',{encounterId:def.id,bossEntityId:boss.entityId});return{ok:true,encounterId:def.id,bossEntityId:boss.entityId}}
 onDeath(d){const id=String(d?.entityId||'');for(const[eid,a]of this.active){if(a.bossEntityId!==id)continue;a.state='COMPLETED';this.active.delete(eid);this.completed.add(eid);if(!a.lootGranted){a.lootGranted=true;this.events?.emit?.('encounter:rewardEligible',{encounterId:eid,bossEntityId:id,lootOnce:a.def.lootOnce})}this.events?.emit?.('encounter:completed',{encounterId:eid,bossEntityId:id})}}
 reset(id,reason='RESET'){const a=this.active.get(String(id));if(!a)return false;this.spawn?.remove?.(a.bossEntityId,'ENCOUNTER_RESET');this.active.delete(String(id));this.events?.emit?.('encounter:reset',{encounterId:String(id),reason});return true}
 resetByPolicy(reason='PLAYER_DEATH'){for(const[id,a]of[...this.active])if(a.def.resetPolicy==='ON_PLAYER_DEATH'&&reason==='PLAYER_DEATH')this.reset(id,reason)}
 isActive(id=null){if(id)return this.active.has(String(id));return this.active.size>0}
 snapshot(){return{active:[...this.active.keys()],completed:[...this.completed]}}
}
window.GameCore=window.GameCore||{};window.GameCore.EncounterSystem=EncounterSystem;window.GameCore.encounters=window.GameCore.encounters||new EncounterSystem();window.GameServices=Object.assign(window.GameServices||{},{encounters:window.GameCore.encounters});
})();