(()=>{'use strict';
class FormationSystem{
 constructor({store=window.GameServices?.economyStore,inventory=window.GameServices?.inventory,items=window.GameServices?.items,catalog=window.GameCore?.phase10Catalog,events=window.GameServices?.events,scheduler=window.GameServices?.scheduler,meditation=window.GameServices?.meditation,damage=window.GameServices?.damage,enemies=window.GameServices?.enemyEntities,player=window.GameRuntime?.player,scene=window.GameRuntime?.scene}={}){Object.assign(this,{store,inventory,items,catalog,events,scheduler,meditation,damage,enemies,player,scene});const s=store.state;s.formations=s.formations||{serial:0,placements:{}};this.state=s.formations;this.visuals=new Map();events?.on?.('zone:unloaded',d=>this.unloadVisuals(d?.zoneId),{owner:'FormationSystem'});events?.on?.('zone:loaded',d=>this.loadZone(d?.zoneId),{owner:'FormationSystem'});scheduler?.register?.('SECOND',(dt,now)=>this.tick(dt,now),{owner:'FormationSystem',label:'formations'});this.loadZone('thanh_van_region')}
 place(instanceId,{zoneId='thanh_van_region',position=null}={}){const item=this.inventory.state().instances[instanceId],def=this.catalog.FORMATION_DEFS[item?.baseId];if(!item||!def)return{ok:false,reason:'NOT_FORMATION'};if(this.inventory.isReservedInstance(instanceId))return{ok:false,reason:'ITEM_RESERVED'};const p=position||this.player?.position;if(!p)return{ok:false,reason:'NO_POSITION'};const id=`formation_${++this.state.serial}`;delete this.inventory.state().instances[instanceId];this.state.placements[id]={id,baseId:item.baseId,item,zoneId,position:{x:p.x,y:p.y||0,z:p.z},active:true,placedAt:Date.now(),lastTickAt:0};this.store.save();this.render(this.state.placements[id]);this.events?.emit?.('formation:placed',{placementId:id,baseId:item.baseId,zoneId});return{ok:true,placementId:id}}
 remove(id){const p=this.state.placements[id];if(!p)return{ok:false,reason:'MISSING'};const add=this.inventory.addInstanceDirect(p.item);if(!add.ok)return add;delete this.state.placements[id];this.visuals.get(id)?.dispose?.();this.visuals.delete(id);this.store.save();this.events?.emit?.('formation:removed',{placementId:id});return{ok:true}}
 setActive(id,active){const p=this.state.placements[id];if(!p)return false;p.active=!!active;this.store.save();return true}
 render(p){if(!this.scene||typeof BABYLON==='undefined'||this.visuals.has(p.id))return;const mesh=BABYLON.MeshBuilder.CreateTorus(p.id,{diameter:Math.max(2,this.catalog.FORMATION_DEFS[p.baseId]?.radius||5),thickness:.08,tessellation:40},this.scene);mesh.position.set(p.position.x,p.position.y+.05,p.position.z);mesh.rotation.x=Math.PI/2;mesh.isPickable=false;mesh.metadata={formationId:p.id};const mat=new BABYLON.StandardMaterial(`${p.id}_mat`,this.scene);mat.emissiveColor=new BABYLON.Color3(.2,.75,1);mat.alpha=.45;mesh.material=mat;this.visuals.set(p.id,mesh)}
 loadZone(zoneId){for(const p of Object.values(this.state.placements))if(p.zoneId===zoneId)this.render(p)}
 unloadVisuals(zoneId){for(const[id,m]of[...this.visuals]){const p=this.state.placements[id];if(p?.zoneId===zoneId){m.dispose();this.visuals.delete(id)}}}
 tick(dt,now){let mult=1;const pp=this.player?.position;for(const p of Object.values(this.state.placements)){if(!p.active)continue;const def=this.catalog.FORMATION_DEFS[p.baseId];if(!def)continue;const dist=pp?Math.hypot(pp.x-p.position.x,pp.z-p.position.z):1e9;if(def.kind==='MEDITATION'&&dist<=def.radius)mult=Math.max(mult,def.meditationMultiplier||1);if(def.kind==='COMBAT'&&now-(p.lastTickAt||0)>=def.tickInterval){p.lastTickAt=now;for(const e of this.enemies?.alive?.(p.zoneId)||[])if(Math.hypot(e.position.x-p.position.x,e.position.z-p.position.z)<=def.radius)this.damage?.resolve?.({sourceEntityId:'player',targetEntityId:e.entityId,sourceType:'FORMATION',damageType:'LIGHTNING',baseAmount:def.damage,canCrit:false,tags:['FORMATION']})}}this.meditation?.setContext?.({formationMultiplier:mult})}
 snapshot(){return JSON.parse(JSON.stringify(this.state))}
 dispose(){this.scheduler?.unregisterOwner?.('FormationSystem');this.events?.disposeOwner?.('FormationSystem');for(const m of this.visuals.values())m.dispose?.();this.visuals.clear()}
}
window.GameCore=window.GameCore||{};window.GameCore.FormationSystem=FormationSystem;window.GameCore.formations=window.GameCore.formations||new FormationSystem();window.GameServices=Object.assign(window.GameServices||{},{formations:window.GameCore.formations});
})();