(()=>{'use strict';
class InventorySystem{
 constructor({store=window.GameServices?.economyStore,items=window.GameServices?.items,transactions=window.GameServices?.transactions,events=window.GameServices?.events}={}){Object.assign(this,{store,items,transactions,events})}
 state(){return this.store.state.inventory}used(){return Object.keys(this.state().instances).length+Object.values(this.state().stacks).filter(x=>x>0).length}hasSpace(extra=1){return this.used()+extra<=this.state().capacity}
 listInstances(){return Object.values(this.state().instances)}listStacks(){return Object.entries(this.state().stacks).map(([baseId,quantity])=>({baseId,quantity}))}
 reservedStack(baseId){let n=0;for(const r of Object.values(this.state().reservations))for(const x of r||[])if(x.baseId===baseId)n+=Number(x.quantity)||0;return n}
 availableStack(baseId){return Math.max(0,(Number(this.state().stacks[baseId])||0)-this.reservedStack(baseId))}
 isReservedInstance(id){return Object.values(this.state().reservations).some(r=>(r||[]).some(x=>x.instanceId===id))}
 reserveResources(key,items=[]){if(!key||this.state().reservations[key])return{ok:false,reason:'RESERVATION_EXISTS'};const normalized=[];for(const x of items){if(x.baseId){const q=Math.max(1,Math.floor(Number(x.quantity)||1));if(this.availableStack(x.baseId)<q)return{ok:false,reason:`INGREDIENT_MISSING:${x.baseId}`};normalized.push({baseId:x.baseId,quantity:q})}else if(x.instanceId){if(!this.state().instances[x.instanceId]||this.isReservedInstance(x.instanceId))return{ok:false,reason:`INSTANCE_UNAVAILABLE:${x.instanceId}`};normalized.push({instanceId:x.instanceId})}}this.state().reservations[key]=normalized;this.store.save();this.events?.emit?.('inventory:reserved',{key,items:normalized});return{ok:true,key}}
 consumeReservation(key){const r=this.state().reservations[key];if(!r)return false;for(const x of r)if(x.baseId&&(Number(this.state().stacks[x.baseId])||0)<x.quantity)return false;for(const x of r)if(x.instanceId&&!this.state().instances[x.instanceId])return false;for(const x of r){if(x.baseId){this.state().stacks[x.baseId]-=x.quantity;if(this.state().stacks[x.baseId]<=0)delete this.state().stacks[x.baseId]}}delete this.state().reservations[key];this.store.save();this.events?.emit?.('inventory:reservationConsumed',{key});return true}
 reserve(key,items=[]){return this.reserveResources(key,items).ok}release(key){if(!this.state().reservations[key])return false;delete this.state().reservations[key];this.store.save();this.events?.emit?.('inventory:reservationReleased',{key});return true}
 addStack(baseId,qty,{idempotencyKey=null}={}){qty=Math.floor(Number(qty)||0);const base=this.items.base(baseId);if(!base?.stackable||qty<=0)return{ok:false,reason:'INVALID_STACK'};return this.transactions.run({idempotencyKey:idempotencyKey||`inv-stack:${baseId}:${Date.now()}:${qty}`,resources:[`inventory:stack:${baseId}`],validate:()=>({ok:this.state().stacks[baseId]>0||this.hasSpace(1),reason:'INVENTORY_FULL'}),apply:()=>{this.state().stacks[baseId]=(Number(this.state().stacks[baseId])||0)+qty;this.store.save();this.events?.emit?.('inventory:changed',{kind:'STACK_ADD',baseId,qty});return true}})}
 addInstanceDirect(item,{toRecoveryOnFull=false}={}){if(!item?.instanceId||this.state().instances[item.instanceId])return{ok:false,reason:'INVALID_OR_DUPLICATE'};if(!this.hasSpace(1)){if(toRecoveryOnFull){this.state().recovery.push(item);this.store.save();return{ok:true,recovery:true}}return{ok:false,reason:'INVENTORY_FULL'}}this.state().instances[item.instanceId]=item;this.store.save();this.events?.emit?.('inventory:changed',{kind:'INSTANCE_ADD',instanceId:item.instanceId});return{ok:true,recovery:false}}
 addInstance(item,{idempotencyKey=null,toRecoveryOnFull=true}={}){if(!item?.instanceId)return{ok:false,reason:'INVALID_ITEM'};return this.transactions.run({idempotencyKey:idempotencyKey||`inv-instance:${item.instanceId}`,resources:[`inventory:instance:${item.instanceId}`],validate:()=>({ok:!this.state().instances[item.instanceId],reason:'DUPLICATE_ITEM'}),apply:()=>this.addInstanceDirect(item,{toRecoveryOnFull})})}
 removeStack(baseId,qty,{ignoreReservations=false}={}){qty=Math.floor(Number(qty)||0);const cur=ignoreReservations?(Number(this.state().stacks[baseId])||0):this.availableStack(baseId);if(qty<=0||cur<qty)return false;this.state().stacks[baseId]-=qty;if(this.state().stacks[baseId]<=0)delete this.state().stacks[baseId];this.store.save();return true}
 removeInstance(id,{ignoreReservations=false}={}){const x=this.state().instances[id];if(!x||(!ignoreReservations&&this.isReservedInstance(id)))return null;delete this.state().instances[id];this.store.save();return x}
 claimRecovery(){let n=0;while(this.state().recovery.length&&this.hasSpace(1)){const item=this.state().recovery.shift();this.state().instances[item.instanceId]=item;n++}if(n)this.store.save();return n}
}
window.GameCore=window.GameCore||{};window.GameCore.InventorySystem=InventorySystem;window.GameCore.inventory=window.GameCore.inventory||new InventorySystem();window.GameServices=Object.assign(window.GameServices||{},{inventory:window.GameCore.inventory});
})();