(()=>{'use strict';
const TAU=Math.PI*2,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function css(){if(document.getElementById('mapV2Style'))return;const s=document.createElement('style');s.id='mapV2Style';s.textContent=`#mapV2Overlay{position:fixed;inset:0;z-index:5000;background:rgba(6,15,22,.82);backdrop-filter:blur(8px);display:none;align-items:center;justify-content:center;padding:max(10px,env(safe-area-inset-top)) max(10px,env(safe-area-inset-right)) max(10px,env(safe-area-inset-bottom)) max(10px,env(safe-area-inset-left))}#mapV2Overlay.show{display:flex}#mapV2Panel{width:min(980px,100%);height:min(760px,100%);display:flex;flex-direction:column;background:#102632;border:1px solid rgba(255,255,255,.18);border-radius:18px;overflow:hidden;box-shadow:0 18px 60px #0008}#mapV2Head{display:flex;align-items:center;gap:8px;padding:10px 12px;background:#173747;color:white}#mapV2Head b{flex:1}#mapV2Head button,#mapV2Tools button{min-height:44px;border:0;border-radius:10px;padding:0 12px;background:#28576d;color:white;font-weight:700}#mapV2Head button.active,#mapV2Tools button.active{background:#5ca9c6;color:#071820}#mapV2Tools{display:flex;flex-wrap:wrap;gap:8px;padding:8px 10px;background:#132c39;color:#d9f5ff;align-items:center}#mapV2Tools .spacer{flex:1}#mapV2CanvasWrap{position:relative;flex:1;min-height:0;background:#081820;overflow:hidden;touch-action:none}#mapV2Canvas{width:100%;height:100%;display:block;touch-action:none}#mapV2Status{font-size:12px;opacity:.85}.mobile-minimap{cursor:pointer;touch-action:manipulation}.mobile-minimap:focus-visible{outline:3px solid #78e9ff;outline-offset:2px}`;document.head.appendChild(s)}
class MapV2UI{
 constructor({data=window.GameServices?.mapData,mapState=window.GameServices?.mapState,input=window.GameServices?.input,events=window.GameServices?.events,rt=window.GameRuntime}={}){Object.assign(this,{data,mapState,input,events,rt});this.mode='LOCAL';this.authoring=false;this.pan={x:0,z:0};this.pointers=new Map();this.lastDraw=0;this.dirty=true;css();this.build();this.bindMini();this.listen();rt?.scene?.onBeforeRenderObservable?.add?.(()=>this.frame())}
 build(){const o=document.createElement('section');o.id='mapV2Overlay';o.setAttribute('aria-hidden','true');o.innerHTML=`<div id="mapV2Panel" role="dialog" aria-modal="true" aria-label="Bản đồ"><div id="mapV2Head"><b>Bản Đồ Thanh Vân</b><button data-map-mode="LOCAL" class="active">Cục bộ</button><button data-map-mode="WORLD">Thế giới</button><button id="mapV2Close">✕</button></div><div id="mapV2Tools"><button id="mapV2Add">＋ Đặt dấu</button><button id="mapV2Delete">⌫ Xóa dấu gần nhất</button><button id="mapV2Reset">◎ Đặt lại góc nhìn</button><span class="spacer"></span><span id="mapV2Status"></span></div><div id="mapV2CanvasWrap"><canvas id="mapV2Canvas" width="900" height="560"></canvas></div></div>`;document.body.appendChild(o);this.overlay=o;this.canvas=o.querySelector('#mapV2Canvas');this.ctx=this.canvas.getContext('2d');this.status=o.querySelector('#mapV2Status');o.querySelector('#mapV2Close').onclick=()=>this.close();o.querySelector('#mapV2Add').onclick=()=>{this.authoring=!this.authoring;o.querySelector('#mapV2Add').classList.toggle('active',this.authoring);this.status.textContent=this.authoring?'Chạm bản đồ để đặt dấu cá nhân':''};o.querySelector('#mapV2Delete').onclick=()=>this.deleteNearest();o.querySelector('#mapV2Reset').onclick=()=>{this.pan={x:0,z:0};this.mapState.setZoom(this.mode,1);this.dirty=true};for(const b of o.querySelectorAll('[data-map-mode]'))b.onclick=()=>this.setMode(b.dataset.mapMode);this.bindPointers()}
 bindMini(){const mini=document.getElementById('miniMap');if(!mini)return;mini.setAttribute('role','button');mini.setAttribute('tabindex','0');mini.setAttribute('aria-label','Mở bản đồ cục bộ');mini.addEventListener('click',()=>this.open('LOCAL'));mini.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();this.open('LOCAL')}})}
 listen(){for(const ev of['world:chunkDiscovered','world:poiDiscovered','waypoint:unlocked','quest:markersChanged','enemy:spawned','enemy:entityRemoved','map:stateChanged','map:worldEventsChanged','world:environmentChanged','zone:loaded'])this.events?.on?.(ev,()=>{this.dirty=true},{owner:'MapV2UI'})}
 setMode(m){this.mode=m==='WORLD'?'WORLD':'LOCAL';this.pan={x:0,z:0};for(const b of this.overlay.querySelectorAll('[data-map-mode]'))b.classList.toggle('active',b.dataset.mapMode===this.mode);this.dirty=true}
 open(mode='LOCAL'){this.setMode(mode);this.overlay.classList.add('show');this.overlay.setAttribute('aria-hidden','false');this.resize();this.dirty=true}
 close(){this.overlay.classList.remove('show');this.overlay.setAttribute('aria-hidden','true');this.authoring=false;for(const [id] of this.pointers)this.input?.releasePointer?.(id);this.pointers.clear()}
 resize(){const r=this.canvas.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1);const w=Math.max(300,Math.round(r.width*d)),h=Math.max(220,Math.round(r.height*d));if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h;this.dirty=true}}
 bindPointers(){const c=this.canvas;const pt=e=>{const r=c.getBoundingClientRect(),sx=c.width/r.width,sy=c.height/r.height;return{x:(e.clientX-r.left)*sx,y:(e.clientY-r.top)*sy}};c.addEventListener('pointerdown',e=>{if(!this.input?.claimPointer?.(e.pointerId,'MAP_V2'))return;e.preventDefault();e.stopPropagation();c.setPointerCapture?.(e.pointerId);const q=pt(e);this.pointers.set(e.pointerId,{...q,start:q,last:q});this.dirty=true},{passive:false});c.addEventListener('pointermove',e=>{const p=this.pointers.get(e.pointerId);if(!p)return;e.preventDefault();e.stopPropagation();const q=pt(e);if(this.pointers.size===1&&!this.authoring){const dx=q.x-p.last.x,dy=q.y-p.last.y,scale=this.mode==='WORLD'?1:.22/this.mapState.getZoom('LOCAL');this.pan.x-=dx*scale;this.pan.z+=dy*scale}else if(this.pointers.size===2){const a=[...this.pointers.values()],other=a[0]===p?a[1]:a[0],old=Math.hypot(p.last.x-other.last.x,p.last.y-other.last.y),neu=Math.hypot(q.x-other.last.x,q.y-other.last.y);if(old>3&&neu>3){const z=this.mapState.getZoom(this.mode)*neu/old;this.mapState.setZoom(this.mode,clamp(z,.55,3))}}p.last=q;this.dirty=true},{passive:false});const end=(e,cancel=false)=>{const p=this.pointers.get(e.pointerId);if(!p)return;e.preventDefault();e.stopPropagation();const q=pt(e),moved=Math.hypot(q.x-p.start.x,q.y-p.start.y);if(!cancel&&this.authoring&&moved<12&&this.mode==='LOCAL')this.addMarkerAt(q);this.pointers.delete(e.pointerId);this.input?.releasePointer?.(e.pointerId);this.dirty=true};c.addEventListener('pointerup',e=>end(e,false),{passive:false});c.addEventListener('pointercancel',e=>end(e,true),{passive:false})}
 addMarkerAt(screen){const s=this.data.local(),p=this.screenToWorld(screen,s);if(!p)return;const n=this.mapState.list(s.zoneId).length+1,r=this.mapState.add({zoneId:s.zoneId,position:p,label:`Dấu cá nhân ${n}`,icon:'✦'});if(r?.ok){this.authoring=false;this.overlay.querySelector('#mapV2Add').classList.remove('active');this.status.textContent='Đã lưu dấu cá nhân'}}
 deleteNearest(){const s=this.data.local(),ms=this.mapState.list(s.zoneId);if(!ms.length){this.status.textContent='Không có dấu cá nhân';return}const center={x:s.player.position.x+this.pan.x,z:s.player.position.z+this.pan.z};ms.sort((a,b)=>Math.hypot(a.position.x-center.x,a.position.z-center.z)-Math.hypot(b.position.x-center.x,b.position.z-center.z));this.mapState.remove(ms[0].id);this.status.textContent='Đã xóa dấu gần nhất';this.dirty=true}
 frame(){const now=performance.now();this.drawMini(now);if(!this.overlay.classList.contains('show'))return;if(now-this.lastDraw<120&&!this.dirty)return;this.lastDraw=now;this.resize();this.mode==='WORLD'?this.drawWorld():this.drawLocal();this.dirty=false}
 drawMini(now){if(now-(this._miniLast||0)<100)return;this._miniLast=now;const c=document.getElementById('miniMapCanvas');if(!c)return;const x=c.getContext('2d'),s=this.data.local(),w=c.width,h=c.height,cx=w/2,cy=h/2,r=Math.min(cx,cy)-4,range=72,y=-s.player.yaw,ca=Math.cos(y),sa=Math.sin(y);x.clearRect(0,0,w,h);x.save();x.beginPath();x.arc(cx,cy,r,0,TAU);x.clip();x.fillStyle='#214f45';x.fillRect(0,0,w,h);for(const m of s.markers){if(m.kind==='POI'&&!m.discovered)continue;const dx=m.position.x-s.player.position.x,dz=m.position.z-s.player.position.z,rx=dx*ca-dz*sa,rz=dx*sa+dz*ca,d=Math.hypot(rx,rz);if(d>range*1.2)continue;const sc=Math.min(range,d)/range*r*.84,px=cx+(rx/(d||1))*sc,py=cy+(rz/(d||1))*sc;this.dot(x,px,py,m.kind==='BOSS'?5:m.kind==='ENEMY'?3.5:4,this.color(m.kind),m.icon)}x.restore();x.fillStyle='#6ff3ff';x.beginPath();x.moveTo(cx,cy-9);x.lineTo(cx+5,cy+6);x.lineTo(cx-5,cy+6);x.closePath();x.fill();x.strokeStyle='#f6e4a1';x.lineWidth=2;x.beginPath();x.arc(cx,cy,r,0,TAU);x.stroke()}
 dot(ctx,x,y,r,color,icon=''){ctx.beginPath();ctx.arc(x,y,r,0,TAU);ctx.fillStyle=color;ctx.fill();if(icon&&r>=4){ctx.font=`${Math.max(8,r*2)}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='#fff';ctx.fillText(icon,x,y)}}
 color(k){return({ENEMY:'#ff5151',BOSS:'#ff9a35',NPC:'#7fe0ff',QUEST:'#ffd54a',QUEST_READY:'#fff48b',WAYPOINT:'#62e5ff',POI:'#d6c9ff',CUSTOM:'#ff7cf1',EVENT:'#ff6f6f',CONNECTION:'#9ff59a'})[k]||'#fff'}
 localTransform(s){const z=this.mapState.getZoom('LOCAL'),b=s.zone.bounds,w=this.canvas.width,h=this.canvas.height,span=Math.max(b.maxX-b.minX,b.maxZ-b.minZ)/z,cx=s.player.position.x+this.pan.x,cz=s.player.position.z+this.pan.z,scale=Math.min(w,h)/span;return{scale,cx,cz,to:p=>({x:w/2+(p.x-cx)*scale,y:h/2-(p.z-cz)*scale}),from:q=>({x:cx+(q.x-w/2)/scale,z:cz-(q.y-h/2)/scale})}}
 screenToWorld(q,s){return this.localTransform(s).from(q)}
 drawLocal(){const s=this.data.local(),c=this.ctx,w=this.canvas.width,h=this.canvas.height,T=this.localTransform(s);c.clearRect(0,0,w,h);c.fillStyle='#07161d';c.fillRect(0,0,w,h);const z=s.zone,size=z.chunkSize||70,maxX=Math.floor((z.bounds.maxX-z.bounds.minX)/size),maxZ=Math.floor((z.bounds.maxZ-z.bounds.minZ)/size);for(let x=0;x<=maxX;x++)for(let zz=0;zz<=maxZ;zz++){const key=`${z.id}:${x},${zz}`,disc=!!s.discoveredChunks[key],p0=T.to({x:z.bounds.minX+x*size,z:z.bounds.minZ+(zz+1)*size}),p1=T.to({x:z.bounds.minX+(x+1)*size,z:z.bounds.minZ+zz*size});c.fillStyle=disc?'#244f48':'#0b171d';c.fillRect(p0.x,p0.y,p1.x-p0.x,p1.y-p0.y);c.strokeStyle='rgba(255,255,255,.05)';c.strokeRect(p0.x,p0.y,p1.x-p0.x,p1.y-p0.y)}c.lineCap='round';for(const r of z.terrain?.roads||[]){const a=T.to(r.a),b=T.to(r.b);c.strokeStyle='#bca77e';c.lineWidth=Math.max(2,r.width*T.scale);c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke()}for(const wa of z.terrain?.water||[]){const p=T.to(wa.center);c.fillStyle='#2d8aa5';c.beginPath();c.arc(p.x,p.y,wa.radius*T.scale,0,TAU);c.fill()}for(const m of s.markers){if(!this.data.pointDiscovered(s.zoneId,m.position)&&!['CUSTOM','CONNECTION','QUEST','QUEST_READY','WAYPOINT'].includes(m.kind))continue;const p=T.to(m.position);if(p.x<-30||p.y<-30||p.x>w+30||p.y>h+30)continue;this.dot(c,p.x,p.y,m.kind==='BOSS'?9:7,this.color(m.kind),m.icon);if(m.kind!=='ENEMY'){c.fillStyle='#e8f6f7';c.font='12px system-ui';c.textAlign='center';c.fillText(m.label||'',p.x,p.y+17)}}const pp=T.to(s.player.position);this.dot(c,pp.x,pp.y,8,'#62e8ff','▲');this.status.textContent=`${z.name} · ${s.environment?.weather||''} · ${s.environment?.labelTime||''} · Zoom ${this.mapState.getZoom('LOCAL').toFixed(1)}×`}
 drawWorld(){const s=this.data.world(),c=this.ctx,w=this.canvas.width,h=this.canvas.height,z=this.mapState.getZoom('WORLD'),nodes=s.nodes,margin=80,step=(w-margin*2)/Math.max(1,nodes.length-1)*z,baseX=w/2-((nodes.length-1)*step)/2+this.pan.x,baseY=h/2+this.pan.z*.2,pos=new Map();c.clearRect(0,0,w,h);c.fillStyle='#07161d';c.fillRect(0,0,w,h);nodes.forEach((n,i)=>pos.set(n.id,{x:baseX+i*step,y:baseY+(i%2?40:-40)}));for(const e of s.edges){const a=pos.get(e.a),b=pos.get(e.b);if(!a||!b)continue;c.strokeStyle='#6f8f8b';c.lineWidth=5;c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke()}for(const n of nodes){const p=pos.get(n.id),disc=n.discovered;c.beginPath();c.arc(p.x,p.y,n.current?28:23,0,TAU);c.fillStyle=n.current?'#4dc6df':disc?'#397267':'#17272c';c.fill();c.strokeStyle=n.current?'#baf7ff':'#8aa4a1';c.lineWidth=2;c.stroke();c.fillStyle=disc||n.current?'#f1fbfb':'#718184';c.font='bold 13px system-ui';c.textAlign='center';c.fillText(disc||n.current?n.name:'Chưa khám phá',p.x,p.y+45);if(n.waypoints){c.font='11px system-ui';c.fillStyle='#78e9ff';c.fillText(`◉ ${n.waypoints}`,p.x,p.y+61)}}this.status.textContent=`${s.region.name} · ${s.environment?.weather||''} · ${s.environment?.labelTime||''} · Fog theo Discovery`}
 dispose(){this.events?.disposeOwner?.('MapV2UI');this.overlay?.remove?.()}
}
window.GameCore=window.GameCore||{};window.GameCore.MapV2UI=MapV2UI;
})();