(()=>{'use strict';
const clone=v=>typeof structuredClone==='function'?structuredClone(v):JSON.parse(JSON.stringify(v));
function realmLabel(s){const majors=['Luyện Khí','Trúc Cơ','Kim Đan','Nguyên Anh','Hóa Thần'];if((s.majorRealmIndex||0)===0){const l=Math.max(1,Math.min(12,Number(s.layer)||1)),m=l<=3?'Sơ':l<=6?'Trung':l<=9?'Hậu':'Đỉnh';return `${majors[0]} Tầng ${l} · ${m}`}const minors=['Sơ','Trung','Hậu','Đỉnh'];return `${majors[s.majorRealmIndex]||`Cảnh ${s.majorRealmIndex}`} · ${minors[s.minorRealmIndex||0]}`}
class PetSystem{
 constructor({store=window.GameServices?.economyStore,catalog=window.GameCore?.petCatalog,stats=window.GameServices?.stats,health=window.GameServices?.health,events=window.GameServices?.events,storage=window.GameStorage,inventory=window.GameServices?.inventory,transactions=window.GameServices?.transactions}={}){Object.assign(this,{store,catalog,stats,health,events,storage,inventory,transactions});this.ensureState();this.migrateLegacy();for(const p of this.all())if(p.deployed)this.registerRuntime(p)}
 ensureState(){const s=this.store.state;s.pets=s.pets||{serial:0,instances:{},deployedId:null,migration:null};s.pets.instances=s.pets.instances||{};return s.pets}
 migrateLegacy(){const s=this.ensureState();if(s.migration)return;const legacy=this.storage?.read?.('tv-prog-v3',this.storage?.read?.('tv-prog-v2',{}))||{},count=Math.max(0,Number(legacy.pet)||0);s.migration={legacyPetCount:count,policy:count>0?'NORMALIZED_TO_ONE_STARTER':'NO_LEGACY_PET',appliedAt:Date.now()};if(count>0&&!Object.keys(s.instances).length)this.create('thanh_linh_ho',{source:'LEGACY_NORMALIZATION',bond:10});this.store.save()}
 create(definitionId,{source='SYSTEM',bloodline=null,bond=0}={}){const def=this.catalog.DEFINITIONS[definitionId];if(!def)return null;const s=this.ensureState(),id=`pet_${++s.serial}_${definitionId}`,p={petId:id,definitionId,name:def.name,bloodline:bloodline||def.bloodline,bond:Math.max(0,Math.min(100,Number(bond)||0)),cultivationCurrent:0,majorRealmIndex:0,layer:1,minorRealmIndex:0,evolutionStage:0,skills:[...(def.skills||[])],deployed:false,state:'RETURN',createdAt:Date.now(),source};s.instances[id]=p;this.store.save();this.events?.emit?.('pet:created',{petId:id,definitionId,source});return clone(p)}
 all(){return Object.values(this.ensureState().instances)}get(id){return this.ensureState().instances[String(id)]||null}deployed(){const id=this.ensureState().deployedId;return id?this.get(id):null}requirement(p){return this.catalog.realmRequirement(p)}
 grantCultivation(id,amount,source='PET_ACTIVITY'){const p=this.get(id);if(!p)return{ok:false,reason:'PET_MISSING'};const req=this.requirement(p),before=p.cultivationCurrent;p.cultivationCurrent=Math.min(req,Math.max(0,before+Math.max(0,Number(amount)||0)));this.store.save();this.events?.emit?.('pet:cultivationChanged',{petId:p.petId,gained:p.cultivationCurrent-before,current:p.cultivationCurrent,required:req,source});return{ok:true,gained:p.cultivationCurrent-before,current:p.cultivationCurrent,required:req,capped:p.cultivationCurrent>=req}}
 cultivateWithEssence(id,qty=1){const p=this.get(id);qty=Math.max(1,Math.floor(Number(qty)||1));if(!p)return{ok:false,reason:'PET_MISSING'};return this.transactions.run({idempotencyKey:`pet-cultivate:${id}:${Date.now()}:${qty}`,resources:['inventory',`pet:${id}`],validate:()=>({ok:this.inventory.availableStack('bloodline_essence')>=qty,reason:'MISSING_BLOODLINE_ESSENCE'}),apply:()=>{if(!this.inventory.removeStack('bloodline_essence',qty))throw new Error('MATERIAL_CONSUME_FAILED');return this.grantCultivation(id,12*qty,'BLOODLINE_ESSENCE')}})}
 feed(id,qty=1){const p=this.get(id);qty=Math.max(1,Math.floor(Number(qty)||1));if(!p)return{ok:false,reason:'PET_MISSING'};return this.transactions.run({idempotencyKey:`pet-feed:${id}:${Date.now()}:${qty}`,resources:['inventory',`pet:${id}`],validate:()=>({ok:this.inventory.availableStack('pet_food')>=qty,reason:'MISSING_PET_FOOD'}),apply:()=>{if(!this.inventory.removeStack('pet_food',qty))throw new Error('MATERIAL_CONSUME_FAILED');this.addBond(id,5*qty,'PET_FOOD');return{bond:p.bond}}})}
 breakthrough(id){const p=this.get(id);if(!p)return{ok:false,reason:'PET_MISSING'};const req=this.requirement(p);if(p.cultivationCurrent<req)return{ok:false,reason:'INSUFFICIENT_CULTIVATION'};p.cultivationCurrent=0;if(p.majorRealmIndex===0){p.layer++;if(p.layer>12){p.majorRealmIndex=1;p.layer=null;p.minorRealmIndex=0}}else{p.minorRealmIndex++;if(p.minorRealmIndex>3){p.majorRealmIndex++;p.minorRealmIndex=0}}this.syncRuntime(p);this.store.save();this.events?.emit?.('pet:breakthrough',{petId:p.petId,realm:realmLabel(p)});return{ok:true,pet:clone(p)}}
 evolve(id){const p=this.get(id),def=p&&this.catalog.DEFINITIONS[p.definitionId];if(!p||!def)return{ok:false,reason:'PET_MISSING'};if(p.evolutionStage>=def.evolutions.length-1)return{ok:false,reason:'MAX_EVOLUTION'};const need=(p.evolutionStage+1)*35;if(p.bond<need)return{ok:false,reason:'BOND_TOO_LOW',requiredBond:need};p.evolutionStage++;this.store.save();this.events?.emit?.('pet:evolved',{petId:p.petId,evolutionStage:p.evolutionStage});return{ok:true,pet:clone(p)}}
 addBond(id,amount,reason='INTERACTION'){const p=this.get(id);if(!p)return false;p.bond=Math.max(0,Math.min(100,p.bond+Math.max(0,Number(amount)||0)));this.store.save();this.events?.emit?.('pet:bondChanged',{petId:p.petId,bond:p.bond,reason});return true}
 deploy(id){const p=this.get(id);if(!p)return{ok:false,reason:'PET_MISSING'};const s=this.ensureState(),old=this.deployed();if(old&&old.petId!==p.petId)this.withdraw(old.petId);s.deployedId=p.petId;p.deployed=true;p.state='FOLLOW';this.registerRuntime(p);this.store.save();this.events?.emit?.('pet:deployed',{petId:p.petId});return{ok:true,pet:clone(p)}}
 withdraw(id=this.ensureState().deployedId){const p=this.get(id);if(!p)return{ok:false,reason:'PET_MISSING'};p.deployed=false;p.state='RETURN';if(this.ensureState().deployedId===p.petId)this.ensureState().deployedId=null;this.unregisterRuntime(p);this.store.save();this.events?.emit?.('pet:withdrawn',{petId:p.petId});return{ok:true}}
 statBlock(p){const def=this.catalog.DEFINITIONS[p.definitionId],blood=this.catalog.BLOODLINES[p.bloodline]?.statMods||{},realm=(p.majorRealmIndex||0),step=realm===0?Math.max(1,p.layer||1):1+Math.max(0,p.minorRealmIndex||0),evo=1+(p.evolutionStage||0)*.16,bond=1+(p.bond||0)*.002,base=def.baseStats;return{maxHP:(base.maxHP+realm*55+(step-1)*7)*evo,maxMana:(base.maxMana+realm*24)*evo,attack:(base.attack+realm*11+(step-1)*1.2)*evo*bond,defense:(base.defense+realm*9+(step-1))*evo,moveSpeed:(base.moveSpeed||6.5)+(Number(blood.moveSpeed)||0),critChance:.04+(Number(blood.critChance)||0),critMultiplier:1.4,resistances:{},damageBonuses:{},...Object.fromEntries(Object.entries(blood).filter(([k])=>!['moveSpeed','critChance'].includes(k)).map(([k,v])=>[k,(Number(v)||0)]))}}
 registerRuntime(p){this.stats?.register?.(p.petId,{provider:()=>this.statBlock(p)});const st=this.statBlock(p);if(!this.health?.get?.(p.petId))this.health?.register?.(p.petId,{currentHP:st.maxHP,maxHP:st.maxHP,majorRealmIndex:p.majorRealmIndex||0,minorRealmIndex:p.minorRealmIndex||0,kind:'PET',metadata:{petId:p.petId}});this.syncRuntime(p)}
 unregisterRuntime(p){this.health?.unregister?.(p.petId);this.stats?.unregister?.(p.petId)}syncRuntime(p){if(!p?.deployed)return;const h=this.health?.get?.(p.petId);if(h){this.health.setRealm?.(p.petId,p.majorRealmIndex||0,p.minorRealmIndex||0);this.health.syncMax?.(p.petId)}}markDown(id){const p=this.get(id);if(!p)return false;p.state='DOWN';p.downedAt=Date.now();this.store.save();this.events?.emit?.('pet:downed',{petId:p.petId});return true}revive(id){const p=this.get(id);if(!p||!p.deployed)return false;const st=this.statBlock(p);this.health?.register?.(p.petId,{currentHP:st.maxHP,maxHP:st.maxHP,majorRealmIndex:p.majorRealmIndex||0,minorRealmIndex:p.minorRealmIndex||0,kind:'PET',metadata:{petId:p.petId}});p.state='RETURN';this.store.save();this.events?.emit?.('pet:revived',{petId:p.petId});return true}realmLabel(id){const p=typeof id==='string'?this.get(id):id;return p?realmLabel(p):''}snapshot(){return clone(this.ensureState())}
}
window.GameCore=window.GameCore||{};window.GameCore.PetSystem=PetSystem;window.GameCore.pets=window.GameCore.pets||new PetSystem();window.GameServices=Object.assign(window.GameServices||{},{pets:window.GameCore.pets});
})();