(()=>{'use strict';
const s=window.GameServices||{},events=s.events;let ctx=null,modal=null;
function ensure(){if(modal)return modal;modal=document.createElement('section');modal.id='phase10Modal';modal.className='system-modal';modal.setAttribute('aria-hidden','true');modal.innerHTML='<div class="system-sheet" role="dialog" aria-modal="true"><header><b id="p10Title">Luyện Chế</b><button id="p10Close">✕</button></header><div id="p10Body" class="system-body"></div></div>';document.getElementById('hud')?.appendChild(modal);modal.querySelector('#p10Close').onclick=close;return modal}
function close(){ensure().classList.remove('show');ensure().setAttribute('aria-hidden','true');ctx=null}
function open(c){ctx=c;const m=ensure();m.classList.add('show');m.setAttribute('aria-hidden','false');m.querySelector('#p10Title').textContent=c.type==='FURNACE'?'Đan Lô':c.type==='FORGE'?'Luyện Khí Đài':'Trận Pháp Đài';render(m.querySelector('#p10Body'))}
function button(text,fn){const x=document.createElement('button');x.type='button';x.textContent=text;x.onclick=fn;return x}
function toast(r,ok='Thành công'){window.GameUI?.toast?.(r?.ok?ok:`Không thể: ${r?.reason||'UNKNOWN'}`)}
function render(b){const jobs=s.craftJobs?.list?.().filter(j=>!['CLAIMED','CANCELLED'].includes(j.state))||[],all=s.inventory?.listInstances?.()||[],recipes=ctx?.type==='FURNACE'?s.alchemy?.recipes?.()||[]:(s.crafting?.recipes?.()||[]).filter(r=>r.stationType===ctx?.type&&r.action==='CREATE');b.innerHTML=`<div class="system-summary">Trạm: <b>${ctx?.stationId||''}</b><br>Job được lưu, có reservation và seed cố định; đóng/reload không reroll.</div><h3>Công thức</h3><div id="p10Recipes"></div><h3>Job</h3><div id="p10Jobs"></div><h3 id="p10ToolsTitle">Thao tác</h3><div id="p10Tools"></div>`;
const rr=b.querySelector('#p10Recipes');for(const r of recipes)rr.appendChild(button(`${r.name} · ${r.duration}s`,()=>{const res=r.system==='ALCHEMY'?s.alchemy.start(r.id,ctx):s.crafting.start(r.id,ctx);toast(res,'Đã bắt đầu');render(b)}));
const jj=b.querySelector('#p10Jobs');for(const j of jobs){const row=document.createElement('div');row.className='system-summary';row.append(`${j.recipeId} · ${j.state} `);if(j.state==='READY')row.appendChild(button('Nhận',()=>{const r=s.craftJobs.claim(j.jobId);toast(r,'Đã nhận kết quả');render(b)}));if(j.state==='RUNNING')row.appendChild(button('Hủy',()=>{toast({ok:s.craftJobs.cancel(j.jobId)},'Đã hủy');render(b)}));jj.appendChild(row)}
const tools=b.querySelector('#p10Tools');if(ctx?.type==='FURNACE'){for(const i of all.filter(x=>s.items.base(x.baseId)?.type==='PILL'))tools.appendChild(button(`Dùng ${s.items.base(i.baseId).name} · G${i.grade} ${i.quality}`,()=>{toast(s.pills.use(i.instanceId),'Đã dùng đan');render(b)}))}
else if(ctx?.type==='FORGE'){for(const i of all.filter(x=>['EQUIPMENT','ARTIFACT'].includes(s.items.base(x.baseId)?.type))){const row=document.createElement('div');row.className='system-summary';row.append(`${s.items.base(i.baseId).name} +${i.enhancement||0} ${i.quality} `);if(s.items.base(i.baseId)?.type==='ARTIFACT'){row.appendChild(button(s.artifacts.state.equipped===i.instanceId?'Đang trang bị':'Trang bị pháp bảo',()=>{toast(s.artifacts.equip(i.instanceId),'Đã trang bị');render(b)}));row.appendChild(button('Kích hoạt',()=>toast(s.artifacts.activate(),'Pháp bảo đã kích hoạt')))}else{row.appendChild(button('Cường hóa',()=>{toast(s.crafting.enhance(i.instanceId,ctx),'Đã tạo job');render(b)}));row.appendChild(button('Tinh luyện',()=>{toast(s.crafting.refine(i.instanceId,ctx),'Đã tạo job');render(b)}));row.appendChild(button('Tái chú',()=>{toast(s.crafting.reforge(i.instanceId,ctx),'Đã tạo job');render(b)}));row.appendChild(button('Phân giải',()=>{toast(s.crafting.salvage(i.instanceId,ctx),'Đã tạo job');render(b)}))}tools.appendChild(row)}}
else if(ctx?.type==='FORMATION_TABLE'){for(const i of all.filter(x=>s.items.base(x.baseId)?.type==='FORMATION'))tools.appendChild(button(`Đặt ${s.items.base(i.baseId).name} tại đây`,()=>{toast(s.formations.place(i.instanceId,{zoneId:'thanh_van_region'}),'Đã đặt trận');render(b)}));for(const p of Object.values(s.formations.state.placements||{})){const row=document.createElement('div');row.className='system-summary';row.append(`${GameCore.phase10Catalog.FORMATION_DEFS[p.baseId]?.name||p.baseId} · ${p.active?'Đang bật':'Đang tắt'} `);row.appendChild(button(p.active?'Tắt':'Bật',()=>{s.formations.setActive(p.id,!p.active);render(b)}));row.appendChild(button('Thu hồi',()=>{toast(s.formations.remove(p.id),'Đã thu hồi');render(b)}));tools.appendChild(row)}}}
events?.on?.('craft:stationInteracted',open,{owner:'Phase10UI'});events?.on?.('craft:jobReady',()=>{if(ctx)render(ensure().querySelector('#p10Body'))},{owner:'Phase10UI'});window.Phase10UI={open,close};
})();