(()=>{'use strict';
class PlayerMotor{
 constructor({player=window.GameRuntime?.player,input=window.GameServices?.input,collisions=window.GameServices?.collisions,stats=window.GameServices?.stats,events=window.GameServices?.events,scheduler=window.GameServices?.scheduler}={}){Object.assign(this,{player,input,collisions,stats,events,scheduler});this.velocity={x:0,z:0};this.acceleration=34;this.deceleration=42;this.lastSafePosition=this.readPosition();this.knockbacks=[];this.moving=false;this.enabled=true;scheduler?.register?.('FRAME',(dt)=>this.update(Math.min(.05,Math.max(0,dt||0))),{owner:'PlayerMotor',label:'player-motor'})}
 readPosition(){return{x:Number(this.player?.position?.x)||0,y:Number(this.player?.position?.y)||0,z:Number(this.player?.position?.z)||0}}
 moveToward(current,target,maxDelta){if(current<target)return Math.min(target,current+maxDelta);if(current>target)return Math.max(target,current-maxDelta);return current}
 addKnockback(x,z,speed=8,duration=.2){const l=Math.hypot(x,z)||1;this.knockbacks.push({x:x/l,z:z/l,speed:Math.max(0,Number(speed)||0),remaining:Math.max(0,Number(duration)||0)})}
 computeKnockback(dt){let x=0,z=0;for(let i=this.knockbacks.length-1;i>=0;i--){const k=this.knockbacks[i];x+=k.x*k.speed;z+=k.z*k.speed;k.remaining-=dt;if(k.remaining<=0)this.knockbacks.splice(i,1)}return{x,z}}
 update(dt){if(!this.enabled||!this.player)return false;const intent=this.input?.getMoveIntent?.()||{x:0,z:0,magnitude:0},s=this.stats?.get?.('player')||{},speed=Math.max(0,Number(s.moveSpeed)||8.8),desiredX=intent.x*intent.magnitude*speed,desiredZ=intent.z*intent.magnitude*speed,rate=intent.magnitude>.01?this.acceleration:this.deceleration;this.velocity.x=this.moveToward(this.velocity.x,desiredX,rate*dt);this.velocity.z=this.moveToward(this.velocity.z,desiredZ,rate*dt);const kb=this.computeKnockback(dt),vx=this.velocity.x+kb.x,vz=this.velocity.z+kb.z,cur=this.readPosition(),desired={x:cur.x+vx*dt,y:cur.y,z:cur.z+vz*dt},r=this.collisions?.resolveMove?.(cur,desired)||{position:desired,blocked:false,grounded:true};this.player.position.set(r.position.x,r.position.y,r.position.z);const mag=Math.hypot(this.velocity.x,this.velocity.z),was=this.moving;this.moving=mag>.12||Math.hypot(kb.x,kb.z)>.1;if(!r.blocked&&r.grounded)this.lastSafePosition={...r.position};if(intent.magnitude>.08){const angle=Math.atan2(intent.x,intent.z);this.events?.emit?.('player:facingIntent',{entityId:'player',angle,source:intent.source});window.setPlayerTargetAngle?.(angle)}if(was!==this.moving)this.events?.emit?.('movement:changed',{entityId:'player',moving:this.moving,velocity:{...this.velocity},intent});this.events?.emit?.('movement:updated',{entityId:'player',moving:this.moving,velocity:{...this.velocity},intent,position:{...r.position},blocked:!!r.blocked});window.isPlayerMoving=this.moving;window.PLAYER_MOTION_STATE=this.moving?'moving':'idle';return this.moving}
 teleport(position,{reason='TELEPORT',markSafe=true}={}){if(!this.player||!position)return false;this.velocity.x=this.velocity.z=0;this.knockbacks.length=0;const p={x:Number(position.x)||0,y:Number(position.y)||0,z:Number(position.z)||0};const g=this.collisions?.sampleGround?.(p);if(g?.ok&&Number.isFinite(g.y))p.y=g.y;this.player.position.set(p.x,p.y,p.z);if(markSafe)this.lastSafePosition={...p};this.events?.emit?.('player:teleported',{entityId:'player',position:{...p},reason});return true}
 recoverLastSafe(reason='RECOVER'){return this.teleport(this.lastSafePosition,{reason,markSafe:false})}
 isMoving(){return this.moving}
 getVelocity(){return{...this.velocity}}
 dispose(){this.scheduler?.disposeOwner?.('PlayerMotor')}
}
window.GameCore=window.GameCore||{};window.GameCore.PlayerMotor=PlayerMotor;window.GameCore.playerMotor=window.GameCore.playerMotor||new PlayerMotor();window.GameServices=Object.assign(window.GameServices||{},{playerMotor:window.GameCore.playerMotor});
})();