(()=>{'use strict';const clone=v=>typeof structuredClone==='function'?structuredClone(v):JSON.parse(JSON.stringify(v));
class QuestSystem{constructor({catalog=window.GameCore?.phase12Catalog,store=window.GameServices?.economyStore,events=window.GameServices?.events,tx=window.GameServices?.transactions,wallet=window.GameServices?.wallet,inventory=window.GameServices?.inventory,flags=window.GameServices?.worldFlags}={}){Object.assign(this,{catalog,store,events,tx,wallet,inventory,flags});store.state.quests=store.state.quests||{};this.state=store.state.quests;events?.on?.('entity:died',d=>this.onDomain('KILL',d),{owner:'QuestSystem'});events?.on?.('loot:picked',d=>this.onDomain('PICKUP',d),{owner:'QuestSystem'});events?.on?.('pet:captureResolved',d=>{if(d?.success)this.onDomain('CAPTURE',d)},{owner:'QuestSystem'});events?.on?.('worldFlag:changed',d=>this.onDomain('FLAG',d),{owner:'QuestSystem'})}
def(id){return this.catalog.QUESTS[id]||null}get(id){return this.state[id]||null}all(){return Object.values(this.state).map(clone)}status(id){return this.get(id)?.status||'NOT_STARTED'}
start(id){const def=this.def(id);if(!def)return{ok:false,reason:'QUEST_UNKNOWN'};const q=this.get(id);if(q&&q.status!=='NOT_STARTED')return{ok:q.status==='ACTIVE'||q.status==='READY',already:true,status:q.status};this.state[id]={id,status:'ACTIVE',startedAt:Date.now(),objectives:Object.fromEntries(def.objectives.map(o=>[o.id,{current:0,target:o.count}])),rewarded:false};this.store.save();this.events?.emit?.('quest:started',{questId:id});this.refresh(id);return{ok:true,quest:clone(this.state[id])}}
match(o,d){if(o.type==='KILL'){if(o.filter?.kind==='ENEMY'&&String(d?.entityId||'').startsWith('enemy_')===false)return false;return true}if(o.type==='PICKUP')return !o.filter?.baseId||d?.baseId===o.filter.baseId;if(o.type==='CAPTURE')return !o.filter?.definitionId||d?.definitionId===o.filter.definitionId;if(o.type==='FLAG')return d?.key===o.filter?.key&&d?.value===o.filter?.value;return false}
onDomain(type,d){for(const q of Object.values(this.state)){if(q.status!=='ACTIVE')continue;const def=this.def(q.id);for(const o of def.objectives){if(o.type!==type||!this.match(o,d))continue;const rec=q.objectives[o.id];rec.current=Math.min(rec.target,rec.current+Math.max(1,Number(d?.quantity)||1));this.events?.emit?.('quest:objective',{questId:q.id,objectiveId:o.id,current:rec.current,target:rec.target})}this.refresh(q.id)}this.store.save()}
refresh(id){const q=this.get(id),def=this.def(id);if(!q||q.status!=='ACTIVE')return false;const ready=def.objectives.every(o=>(q.objectives[o.id]?.current||0)>=o.count);if(ready){q.status='READY';q.readyAt=Date.now();this.store.save();this.events?.emit?.('quest:ready',{questId:id})}return ready}
complete(id){const q=this.get(id),def=this.def(id);if(!q||!def)return{ok:false,reason:'QUEST_MISSING'};if(q.status==='COMPLETED')return{ok:true,idempotent:true};if(q.status!=='READY')return{ok:false,reason:'QUEST_NOT_READY'};const before=clone(this.store.state),rewards=def.rewards||[];const r=this.tx.run({idempotencyKey:`quest-reward:${id}`,resources:['inventory','wallet',`quest:${id}`],validate:()=>{if(q.status!=='READY'||q.rewarded)return{ok:false,reason:'QUEST_NOT_READY'};for(const rw of rewards)if(rw.kind==='STACK'&&!this.store.state.inventory.stacks[rw.baseId]&&!this.inventory.hasSpace(1))return{ok:false,reason:'INVENTORY_FULL'};return{ok:true}},apply:()=>{for(const rw of rewards){if(rw.kind==='CURRENCY')this.store.state.wallet[rw.tier]=(Number(this.store.state.wallet[rw.tier])||0)+Math.max(0,Number(rw.amount)||0);else if(rw.kind==='STACK')this.store.state.inventory.stacks[rw.baseId]=(Number(this.store.state.inventory.stacks[rw.baseId])||0)+Math.max(0,Math.floor(Number(rw.quantity)||0))}q.rewarded=true;q.status='COMPLETED';q.completedAt=Date.now();for(const[k,v]of Object.entries(def.flagsOnComplete||{}))this.flags.set(k,v,`QUEST_${id}`);this.store.save();this.events?.emit?.('quest:completed',{questId:id,rewards:clone(rewards)});return clone(q)},rollback:()=>{this.store.state=before;this.state=this.store.state.quests;this.store.save()}});return r.ok?{ok:true,quest:clone(this.get(id)),idempotent:!!r.idempotent}:r}
summary(id){const q=this.get(id),def=this.def(id);if(!def)return null;return{questId:id,name:def.name,status:this.status(id),objectives:def.objectives.map(o=>({id:o.id,type:o.type,current:q?.objectives?.[o.id]?.current||0,target:o.count}))}}
}
window.GameCore=window.GameCore||{};window.GameCore.QuestSystem=QuestSystem;window.GameCore.quests=window.GameCore.quests||new QuestSystem();window.GameServices=Object.assign(window.GameServices||{},{quests:window.GameCore.quests});
})();