(()=>{'use strict';
const catalog=Object.freeze({
 thanh_van:Object.freeze({id:'thanh_van',name:'Thanh Vân',slot:0,rank:'NHAN',quality:'HA',mastery:'NHAP_MON',element:'WIND',damageType:'WIND',castType:'CAST_TIME',castTime:.22,channelInterval:0,recovery:.18,manaCost:8,cooldown:1.4,gcd:.35,range:12,targetingMode:'ENEMY',hitShape:'PROJECTILE',projectile:{speed:18,lifetime:1.1,radius:.45},effects:[{type:'DAMAGE',baseAmount:18}],animationKey:'cast_wind',vfxKey:'wind_slash',sfxKey:'skill_wind',interrupt:{stun:true,silence:true,death:true,movement:false},movementPolicy:'ALLOW',tags:['PROJECTILE','WIND']}),
 ho_the:Object.freeze({id:'ho_the',name:'Hộ Thể',slot:1,rank:'NHAN',quality:'HA',mastery:'NHAP_MON',element:'EARTH',damageType:'EARTH',castType:'INSTANT',castTime:0,channelInterval:0,recovery:.15,manaCost:14,cooldown:6,gcd:.35,range:0,targetingMode:'SELF',hitShape:'SELF',effects:[{type:'SHIELD',amount:35,duration:4,priority:10}],animationKey:'cast_guard',vfxKey:'guard',sfxKey:'skill_guard',interrupt:{death:true},movementPolicy:'ALLOW',tags:['DEFENSIVE','SHIELD']}),
 thien_loi:Object.freeze({id:'thien_loi',name:'Thiên Lôi',slot:2,rank:'HOANG',quality:'HA',mastery:'NHAP_MON',element:'LIGHTNING',damageType:'LIGHTNING',castType:'CAST_TIME',castTime:.42,channelInterval:0,recovery:.22,manaCost:18,cooldown:3.2,gcd:.35,range:14,targetingMode:'ENEMY',hitShape:'PROJECTILE',projectile:{speed:24,lifetime:1.0,radius:.5},effects:[{type:'DAMAGE',baseAmount:34}],animationKey:'cast_lightning',vfxKey:'lightning',sfxKey:'skill_lightning',interrupt:{stun:true,silence:true,death:true,movement:true},movementPolicy:'INTERRUPT',tags:['PROJECTILE','LIGHTNING']}),
 van_kiem:Object.freeze({id:'van_kiem',name:'Vạn Kiếm',slot:3,rank:'HUYEN',quality:'HA',mastery:'NHAP_MON',element:'METAL',damageType:'METAL',castType:'CAST_TIME',castTime:.55,channelInterval:0,recovery:.28,manaCost:24,cooldown:5.5,gcd:.35,range:0,targetingMode:'SELF',hitShape:'CIRCLE',radius:5.2,effects:[{type:'DAMAGE_AOE',baseAmount:28,radius:5.2}],animationKey:'cast_swords',vfxKey:'sword_rain',sfxKey:'skill_swords',interrupt:{stun:true,silence:true,death:true,movement:true},movementPolicy:'INTERRUPT',tags:['AOE','METAL']})
});
const bySlot=Object.freeze(Object.values(catalog).sort((a,b)=>a.slot-b.slot));
window.GameCore=window.GameCore||{};window.GameCore.skillCatalog=catalog;window.GameCore.skillsBySlot=bySlot;
})();