(()=>{'use strict';
const DEFAULT_ECOLOGY=Object.freeze({zoneId:'thanh_van_region',safeZones:Object.freeze([{x:0,z:0,radius:12}]),subZones:Object.freeze({
 thanh_truc_lam:Object.freeze({populationBudget:4,center:{x:18,z:18},radius:18,groups:Object.freeze([{templateId:'bamboo_cactoro',weight:3},{templateId:'bamboo_dragon',weight:1}])}),
 linh_khe_coc:Object.freeze({populationBudget:3,center:{x:-24,z:20},radius:16,groups:Object.freeze([{templateId:'creek_cactoro',weight:2},{templateId:'creek_dragon',weight:1}])})
})});
class SpawnSystem{
 constructor({domain=window.GameServices?.enemyDomain,entities=window.GameServices?.enemyEntities,renderer=window.GameServices?.enemyRenderer,events=window.GameServices?.events,rng=null,clock=window.GameServices?.clock,scheduler=window.GameServices?.scheduler,scene=window.GameRuntime?.scene,player=window.GameRuntime?.player,camera=window.GameRuntime?.camera}={}){Object.assign(this,{domain,entities,renderer,events,clock,scheduler,scene,player,camera});this.rng=rng||new window.GameCore.SeededRng('enemy-spawn-v1');this.ecology=DEFAULT_ECOLOGY;this.activeZoneId=this.ecology.zoneId;this.respawnQueue=[];this.cleanupQueue=[];this.spawnSerial=0;scheduler?.register?.('SLOW',()=>this.maintain(),{owner:'SpawnSystem',label:'spawn-ecology'});events?.on?.('entity:died',d=>this.onDeath(d),{owner:'SpawnSystem'});events?.on?.('zone:unloaded',d=>{if(d?.zoneId)this.unloadZone(d.zoneId)},{owner:'SpawnSystem'})}
 setEcology(def){if(def?.zoneId&&def?.subZones)this.ecology=def}
 weighted(groups){return this.rng.weighted(groups||[])||null}
 samplePoint(sub){const a=this.rng.range(0,Math.PI*2),r=Math.sqrt(this.rng.next())*Math.max(2,sub.radius||12);return{x:sub.center.x+Math.cos(a)*r,y:0,z:sub.center.z+Math.sin(a)*r}}
 isWater(mesh){const md=mesh?.metadata||{};return md.isWater===true||/water|lake|river|stream/i.test(mesh?.name||'')}
 insideSafeZone(p){return(this.ecology.safeZones||[]).some(z=>Math.hypot(p.x-z.x,p.z-z.z)<Math.max(0,Number(z.radius)||0))}
 cameraTooClose(p){const cp=this.camera?.position;if(!cp)return false;return Math.hypot(p.x-cp.x,p.z-cp.z)<10}
 collidesPopulation(p,template){const r=Math.max(.2,template?.asset?.colliderRadius||.35);for(const e of this.entities?.alive?.()||[]){const er=Math.max(.2,e.template?.asset?.colliderRadius||.35);if(Math.hypot(p.x-e.position.x,p.z-e.position.z)<r+er+1.1)return true}return false}
 isValidPoint(p,template=null){if(!Number.isFinite(p.x)||!Number.isFinite(p.z))return false;if(this.insideSafeZone(p))return false;if(this.player&&Math.hypot(p.x-this.player.position.x,p.z-this.player.position.z)<8)return false;if(this.cameraTooClose(p))return false;if(this.collidesPopulation(p,template))return false;if(this.scene&&typeof BABYLON!=='undefined'){const origin=new BABYLON.Vector3(p.x,30,p.z),hit=this.scene.pickWithRay(new BABYLON.Ray(origin,new BABYLON.Vector3(0,-1,0),60),m=>m?.isEnabled?.()!==false&&(m.metadata?.walkable===true||/ground|terrain/i.test(m.name||'')),false);if(!hit?.hit)return false;if(this.isWater(hit.pickedMesh))return false;if(hit.pickedPoint)p.y=hit.pickedPoint.y;const obstacle=this.scene.pickWithRay(new BABYLON.Ray(new BABYLON.Vector3(p.x,p.y+.5,p.z),new BABYLON.Vector3(0,1,0),Math.max(1,template?.asset?.colliderHeight||1)),m=>m?.checkCollisions===true||m?.metadata?.blocksSpawn===true,false);if(obstacle?.hit)return false}return true}
 spawnTemplate(templateId,{zoneId=this.ecology.zoneId,subZoneId='manual',position=null,spawnPointId=null,metadata={}}={}){const t=this.domain?.getTemplate?.(templateId);if(!t)return null;const p={...(position||{x:0,y:0,z:0})};if(!this.isValidPoint(p,t))return null;const e=this.entities.create(t,{zoneId,subZoneId,spawnPointId,home:p,metadata});e.position={...p};this.renderer?.attach?.(e).catch?.(err=>console.error('[SpawnSystem] render',err));this.events?.emit?.('enemy:spawned',{entityId:e.entityId,templateId:t.id,zoneId,subZoneId});return e}
 maintain(){const now=this.clock?.now?.()||0;for(let i=this.cleanupQueue.length-1;i>=0;i--){const q=this.cleanupQueue[i];if(now<q.at)continue;this.cleanupQueue.splice(i,1);const e=this.entities?.get?.(q.entityId);if(e&&!e.alive)this.entities.remove(e.entityId,{reason:'DEAD_CLEANUP'})}for(let i=this.respawnQueue.length-1;i>=0;i--){const q=this.respawnQueue[i];if(now<q.at)continue;this.respawnQueue.splice(i,1);if(q.zoneId===this.activeZoneId)this.spawnTemplate(q.templateId,{zoneId:q.zoneId,subZoneId:q.subZoneId,position:q.position,spawnPointId:q.spawnPointId,metadata:{respawned:true}})}for(const[subZoneId,sub]of Object.entries(this.ecology.subZones||{})){const alive=this.entities.alive(this.ecology.zoneId).filter(e=>e.subZoneId===subZoneId&&e.template.role!=='boss');const need=Math.max(0,(sub.populationBudget||0)-alive.length);for(let i=0;i<need;i++){const g=this.weighted(sub.groups||[]),t=g?this.domain?.getTemplate?.(g.templateId):null;let p=null;for(let attempt=0;attempt<8;attempt++){const candidate=this.samplePoint(sub);if(t&&this.isValidPoint(candidate,t)){p=candidate;break}}if(g&&t&&p)this.spawnTemplate(g.templateId,{zoneId:this.ecology.zoneId,subZoneId,position:p,spawnPointId:`${subZoneId}_${++this.spawnSerial}`})}}}
 onDeath(d){const e=this.entities?.get?.(d?.entityId);if(!e)return;this.entities.markDead(e.entityId);e.renderer?.play?.('death',false,1);e.renderer?.setHP?.(0,e.template.stats.maxHP);const now=this.clock?.now?.()||0;if(e.template.role!=='boss')this.respawnQueue.push({at:now+e.template.respawnSeconds,templateId:e.template.id,zoneId:e.zoneId,subZoneId:e.subZoneId,position:{...e.home},spawnPointId:e.spawnPointId});this.cleanupQueue.push({at:now+.9,entityId:e.entityId})}
 remove(entityId,reason='DESPAWN'){return this.entities?.remove?.(entityId,{reason})||false}
 unloadZone(zoneId){this.respawnQueue=this.respawnQueue.filter(q=>q.zoneId!==zoneId);this.cleanupQueue=this.cleanupQueue.filter(q=>this.entities?.get?.(q.entityId)?.zoneId!==zoneId);return this.entities?.clearZone?.(zoneId)||0}
 list(){return this.entities?.all?.()||[]}
 alive(){return this.entities?.alive?.()||[]}
 rngSnapshot(){return this.rng.snapshot()}
 dispose(){this.scheduler?.unregisterOwner?.('SpawnSystem');this.events?.disposeOwner?.('SpawnSystem')}
}
window.GameCore=window.GameCore||{};window.GameCore.SpawnSystem=SpawnSystem;window.GameCore.spawnSystem=window.GameCore.spawnSystem||new SpawnSystem();window.GameServices=Object.assign(window.GameServices||{},{spawnSystem:window.GameCore.spawnSystem});
})();