(()=>{'use strict';
class StatusSystem{
 constructor({events,clock,scheduler,health}={}){this.events=events;this.clock=clock;this.scheduler=scheduler;this.health=health;this.byEntity=new Map();this.serial=0;scheduler?.register?.('FAST',(dt,now)=>this.update(now),{owner:'StatusSystem',label:'status-ticks'})}
 apply(entityId,def={}){const id=String(entityId);if(!this.health.get(id)?.alive)return null;const now=this.clock?.now?.()||0,key=def.id||`status_${++this.serial}`,list=this.byEntity.get(id)||[];let s=list.find(x=>x.id===key);const duration=Math.max(0,Number(def.duration)||0),maxStacks=Math.max(1,Number(def.maxStacks)||1);if(s){s.stacks=def.stackMode==='STACK'?Math.min(maxStacks,s.stacks+1):s.stacks;if(def.refreshMode!=='IGNORE')s.expiresAt=now+duration}else{s={id:key,entityId:id,category:def.category||'DEBUFF',stacks:1,maxStacks,duration,expiresAt:now+duration,tickInterval:Math.max(.05,Number(def.tickInterval)||0),nextTick:def.tickInterval?now+Math.max(.05,Number(def.tickInterval)):null,sourceEntityId:def.sourceEntityId||null,damageType:def.damageType||'PHYSICAL',tickDamage:Math.max(0,Number(def.tickDamage)||0),tags:[...(def.tags||[])],statModifiers:def.statModifiers||{},definition:def};list.push(s);this.byEntity.set(id,list)}this.events?.emit('status:applied',{...s});return{...s}}
 has(entityId,statusId){return(this.byEntity.get(String(entityId))||[]).some(s=>s.id===statusId)}
 remove(entityId,statusId,reason='removed'){const id=String(entityId),list=this.byEntity.get(id)||[],idx=list.findIndex(s=>s.id===statusId);if(idx<0)return false;const[s]=list.splice(idx,1);if(!list.length)this.byEntity.delete(id);this.events?.emit('status:removed',{entityId:id,statusId:s.id,reason});return true}
 clear(entityId,predicate=null){const id=String(entityId),list=[...(this.byEntity.get(id)||[])];for(const s of list)if(!predicate||predicate(s))this.remove(id,s.id,'cleared')}
 update(now=this.clock?.now?.()||0){for(const[id,list]of[...this.byEntity])for(const s of[...list]){if(!this.health.get(id)?.alive){this.remove(id,s.id,'dead');continue}if(s.nextTick!=null&&now>=s.nextTick){while(s.nextTick!=null&&now>=s.nextTick){s.nextTick+=s.tickInterval;if(s.tickDamage>0)window.GameServices?.damage?.resolve?.({sourceEntityId:s.sourceEntityId,targetEntityId:id,sourceType:'DOT',damageType:s.damageType,baseAmount:s.tickDamage,tags:['DOT',...s.tags],canCrit:false})}}if(now>=s.expiresAt)this.remove(id,s.id,'expired')}}
 snapshot(entityId){return(this.byEntity.get(String(entityId))||[]).map(s=>({...s,definition:undefined}))}
}
window.GameCore=window.GameCore||{};window.GameCore.StatusSystem=StatusSystem;window.GameCore.status=window.GameCore.status||new StatusSystem({events:window.GameCore.events,clock:window.GameCore.clock,scheduler:window.GameCore.tickScheduler,health:window.GameCore.health});
})();