import { resolveClanContext, clanSummary, isClanMember, isClanOfficialMember, isClanGuest, joinClan, promoteClanMember, claimClanTimedBenefit, createClanModal, addClanInfo, addClanActionCard, toastClan, fmt } from './ClanFactionBridge.js?v=20261001-org-relations-v40';
export function openClanMainHallModal(scene,faction){
 const ctx=resolveClanContext(scene,faction);if(!ctx){scene.showToast?.('⚠️ Không tìm thấy Gia Tộc trong Faction V5.');return null;}const sum=clanSummary(ctx);const ui=createClanModal(scene,{title:'🏛️ ĐẠI ĐIỆN TỘC TRƯỞNG',subtitle:`${sum.name} • ${sum.rank}`,accent:0xf59e0b});
 addClanInfo(scene,ui.modal,-220,ui.contentTop,`Quan hệ: ${sum.relationBand} (${fmt(sum.reputation)})   •   Cống hiến: ${fmt(sum.contribution)}\nTín nhiệm: ${fmt(sum.trust)}   •   Trung thành: ${fmt(sum.loyalty)}   •   Uy danh: ${fmt(ctx.relation.prestige||0)}\nLinh khố: ${fmt(sum.treasury)}   •   Chi nhánh: ${sum.branches}   •   Phụ thuộc: ${sum.vassals}${sum.localBranch?`\nHiện diện hiện tại: ${sum.localBranch}`:''}`,{size:'11.5px',color:'#fde68a',width:440});
 const refresh=()=>{ui.close();scene.openClanBuildingUI?.('main_hall',ctx.faction.id);scene.updateHUD?.();};
 addClanActionCard(scene,ui.modal,{y:-90,title:isClanMember(ctx)?'🕯️ Bái Tế Tổ Tiên':'📜 Xin Nhập Tộc / Khách Khanh',body:isClanMember(ctx)?'Phúc lợi 24 giờ/lần, ghi trực tiếp vào quan hệ Faction V5.':'Gia tộc thường nhận Ngoại Tính; Cổ Tộc chỉ ký Khách Khanh nếu chưa có huyết mạch.',button:isClanMember(ctx)?'BÁI TẾ':'XIN GIA NHẬP',onPress:()=>{const r=isClanMember(ctx)?claimClanTimedBenefit(ctx,'clan.ancestor',86400000,{contribution:120,loyalty:10,prestige:5,toast:'Bái tế hoàn tất: +120 cống hiến, tăng trung thành và uy danh.'}):joinClan(ctx);toastClan(scene,r,'🕯️');if(r.ok)refresh();}});
 addClanActionCard(scene,ui.modal,{y:15,title:'🎖️ Khảo Hạch Thăng Cấp Tộc Nhân',body:isClanGuest(ctx)?'Khách Khanh không thăng gia phả/huyết mạch; cần trở thành tộc nhân chính thức.':'Cấp bậc dựa trên cống hiến + uy tín thật: Ngoại Tính → Bàng Hệ → Trực Hệ → Chi Chủ → Trưởng Lão...' ,button:'KHẢO HẠCH',enabled:isClanOfficialMember(ctx),onPress:()=>{const r=promoteClanMember(ctx);toastClan(scene,r,'🎖️');if(r.ok)refresh();}});
 addClanActionCard(scene,ui.modal,{y:120,title:'🤝 Quan Hệ, Chi Nhánh & Thế Lực Phụ Thuộc',body:'Xem minh ước, thù địch, vassal, chi nhánh và ảnh hưởng đang được Faction V5 quản lý.',button:'MỞ QUAN HỆ',onPress:()=>{ui.close();scene.openClanBuildingUI?.('discipline',ctx.faction.id);}});
 addClanActionCard(scene,ui.modal,{y:225,title:'📋 Ủy Thác & Công Việc Gia Tộc',body:'Nhiệm vụ lấy trực tiếp từ quest hooks/khế ước của thế lực hiện tại, không dùng danh sách giả lập.',button:'NHIỆM VỤ',onPress:()=>{ui.close();scene.openClanBuildingUI?.('mission',ctx.faction.id);}});
 return ui.modal;
}
