import { generateFaction, hash32 } from '../generation/factionGenerator.js';
import { FACTION_ARCHETYPES, FACTION_POWER_TIERS, FACTION_SCOPES } from '../core/factionConstants.js';
import { getJurisdictionBudget } from './jurisdictionBudgets.js';

const TYPE_SCOPE=Object.freeze({great_region:FACTION_SCOPES.PRIMARY_REGION,province:FACTION_SCOPES.SECONDARY_TERRITORY,nation:FACTION_SCOPES.NATION,commandery:FACTION_SCOPES.COMMANDERY,city_territory:FACTION_SCOPES.CITY,settlement:FACTION_SCOPES.SETTLEMENT});
const TYPE_TIER=Object.freeze({great_region:FACTION_POWER_TIERS.OVERLORD,province:FACTION_POWER_TIERS.MAJOR,nation:FACTION_POWER_TIERS.MEDIUM,commandery:FACTION_POWER_TIERS.MEDIUM,city_territory:FACTION_POWER_TIERS.MINOR,settlement:FACTION_POWER_TIERS.LOCAL});
const LOCAL_MIX=Object.freeze({
 great_region:[FACTION_ARCHETYPES.SECT,FACTION_ARCHETYPES.DYNASTY,FACTION_ARCHETYPES.ANCIENT_CLAN,FACTION_ARCHETYPES.MERCHANT_GUILD,FACTION_ARCHETYPES.PROFESSION_GUILD,FACTION_ARCHETYPES.INTELLIGENCE_NETWORK,FACTION_ARCHETYPES.UNDERWORLD,FACTION_ARCHETYPES.ACADEMY],
 province:[FACTION_ARCHETYPES.SECT,FACTION_ARCHETYPES.DYNASTY,FACTION_ARCHETYPES.CULTIVATION_FAMILY,FACTION_ARCHETYPES.CULTIVATION_FAMILY,FACTION_ARCHETYPES.MERCHANT_GUILD,FACTION_ARCHETYPES.PROFESSION_GUILD,FACTION_ARCHETYPES.MILITARY_ORDER,FACTION_ARCHETYPES.LOOSE_CULTIVATOR_ALLIANCE,FACTION_ARCHETYPES.INTELLIGENCE_NETWORK,FACTION_ARCHETYPES.UNDERWORLD],
 nation:[FACTION_ARCHETYPES.DYNASTY,FACTION_ARCHETYPES.SECT,FACTION_ARCHETYPES.CULTIVATION_FAMILY,FACTION_ARCHETYPES.CULTIVATION_FAMILY,FACTION_ARCHETYPES.MERCHANT_GUILD,FACTION_ARCHETYPES.PROFESSION_GUILD,FACTION_ARCHETYPES.MILITARY_ORDER,FACTION_ARCHETYPES.INTELLIGENCE_NETWORK,FACTION_ARCHETYPES.UNDERWORLD,FACTION_ARCHETYPES.LOOSE_CULTIVATOR_ALLIANCE],
 city_territory:[FACTION_ARCHETYPES.ADMINISTRATION,FACTION_ARCHETYPES.SECT,FACTION_ARCHETYPES.CULTIVATION_FAMILY,FACTION_ARCHETYPES.CULTIVATION_FAMILY,FACTION_ARCHETYPES.MERCHANT_GUILD,FACTION_ARCHETYPES.PROFESSION_GUILD,FACTION_ARCHETYPES.MILITARY_ORDER,FACTION_ARCHETYPES.UNDERWORLD],
 settlement:[FACTION_ARCHETYPES.ADMINISTRATION,FACTION_ARCHETYPES.CULTIVATION_FAMILY,FACTION_ARCHETYPES.SECT,FACTION_ARCHETYPES.MERCHANT_GUILD,FACTION_ARCHETYPES.UNDERWORLD]
});
function scopeFor(type){return TYPE_SCOPE[type]||FACTION_SCOPES.LOCAL;}
function tierFor(type,index){const base=TYPE_TIER[type]||FACTION_POWER_TIERS.LOCAL;if(index===0)return base;if(base===FACTION_POWER_TIERS.OVERLORD)return FACTION_POWER_TIERS.MAJOR;if(base===FACTION_POWER_TIERS.MAJOR)return index<3?FACTION_POWER_TIERS.MAJOR:FACTION_POWER_TIERS.MEDIUM;if(base===FACTION_POWER_TIERS.MEDIUM)return index<2?FACTION_POWER_TIERS.MEDIUM:FACTION_POWER_TIERS.MINOR;return base;}
export function generateJurisdictionFactions({worldSeed='v5',jurisdiction,importance=1}={}){
 if(!jurisdiction)return Object.freeze([]);const budget=getJurisdictionBudget(jurisdiction.type,importance);const mix=LOCAL_MIX[jurisdiction.type]||LOCAL_MIX.settlement;const result=[];
 for(let i=0;i<budget.local;i++){const archetype=mix[(hash32(`${worldSeed}:${jurisdiction.id}:${i}`)+i)%mix.length];const f=generateFaction({worldSeed,territoryId:jurisdiction.id,continentKey:jurisdiction.continentKey,slot:i,archetype,tier:tierFor(jurisdiction.type,i),territoryMeta:{...jurisdiction,primaryRegionId:jurisdiction.type==='great_region'?jurisdiction.id:jurisdiction.regionId}});result.push(Object.freeze({...f,scope:scopeFor(jurisdiction.type),homeTerritoryId:jurisdiction.id,meta:Object.freeze({...f.meta,jurisdictionId:jurisdiction.id,jurisdictionType:jurisdiction.type,localJurisdictionFaction:true})}));}
 return Object.freeze(result);
}
