/**
 * mineralsData.js
 * He Thong Khoang Thach Tu Tien (6 Pham Cap x 6 Loai)
 * Pham Cap (rank 0): Quang thuong, pham nhan khai thac.
 * Nhat Pham (rank 1): Quang linh, Luyen Khi Ky.
 * Nhi Pham (rank 2): Linh quang, Truc Co Ky.
 * Tam Pham (rank 3): Tien quang, Kim Dan Ky.
 * Tu Pham (rank 4): Than quang, Nguyen Anh Ky.
 * Ngu Pham (rank 5): Hon Nguyen Quang, Hoa Than Ky.
 */

export const ALL_MINERALS = [
  // ===== PHAM CAP (rank 0) =====
  { id:'ore_0_1', rank:0, rankName:'Pham Cap', name:'Tho Thiet Khoang', emoji:'🪨', icon:'ore_icon_ore_0_1', color:'#9ca3af', price:5, hardness:2, purity:30, desc:'Quang sat tho binh thuong, dung ren nong cu va khi gioi pham nhan so cap.', uses:['ren vu khi pham','vat lieu xay dung'], dropSources:['Pham Thu','khai thac nui rung'] },
  { id:'ore_0_2', rank:0, rankName:'Pham Cap', name:'Dong Khoang', emoji:'🟤', icon:'ore_icon_ore_0_2', color:'#b45309', price:8, hardness:3, purity:40, desc:'Quang dong pham chat, duc tien bac va binh dong pham nhan thong dung.', uses:['duc dong tien','vat lieu phu luc cap thap'], dropSources:['Pham Thu','thuong nhan pham nhan'] },
  { id:'ore_0_3', rank:0, rankName:'Pham Cap', name:'Ngan Khoang', emoji:'⬜', icon:'ore_icon_ore_0_3', color:'#e2e8f0', price:15, hardness:3, purity:45, desc:'Quang bac tinh luyen don gian, vat lieu co ban cho phap khi nhap mon.', uses:['ren phap khi so cap','ma bac trang bi'], dropSources:['Pham Thu cap cao','hang dong nong'] },
  { id:'ore_0_4', rank:0, rankName:'Pham Cap', name:'Thach Anh Vun', emoji:'🔶', icon:'ore_icon_ore_0_4', color:'#f59e0b', price:12, hardness:4, purity:35, desc:'Manh thach anh vun thu duoc tu khai thac hang da, chua linh khi vo cung mong.', uses:['che phu luc thuong','trang tri pham nhan'], dropSources:['khai thac hang da','Da Tho Tinh'] },
  { id:'ore_0_5', rank:0, rankName:'Pham Cap', name:'Hac Thach', emoji:'⬛', icon:'ore_icon_ore_0_5', color:'#374151', price:10, hardness:5, purity:25, desc:'Da den cung ran, dung lat duong luyen khi so cap hay tran dai pham nhan.', uses:['vat lieu xay dung','nung chay lay quang sat'], dropSources:['Tieu Da Tru','Tieu Thanh Lang'] },
  { id:'ore_0_6', rank:0, rankName:'Pham Cap', name:'Hoa Tinh Thach', emoji:'🔴', icon:'ore_icon_ore_0_6', color:'#ef4444', price:20, hardness:4, purity:50, desc:'Da chua hoa tinh de bat lua, dung luyen lo dan pham so cap va giu nhiet.', uses:['nhien lieu lo dan','ren vu khi hoa tinh'], dropSources:['vung dia nhiet','Da Tru Dau Dan'] },

  // ===== NHAT PHAM (rank 1) =====
  { id:'ore_1_1', rank:1, rankName:'Nhat Pham', name:'Linh Thiet Khoang', emoji:'🔵', icon:'ore_icon_ore_1_1', color:'#60a5fa', price:60, hardness:5, purity:60, desc:'Quang thiet hap thu linh khi thien dia, ren phap khi Luyen Khi Ky nhap mon.', uses:['ren phap khi Nhat Pham','luyen dan phu gia'], dropSources:['Nhat Pham Yeu Thu','nui linh mach nong'] },
  { id:'ore_1_2', rank:1, rankName:'Nhat Pham', name:'Thanh Dong Tinh', emoji:'🟢', icon:'ore_icon_ore_1_2', color:'#4ade80', price:75, hardness:5, purity:65, desc:'Dong tinh xanh luc, dan linh khi tot va bo tro khac phu luc Luyen Khi.', uses:['che phu luc Nhat Pham','lam linh tuyen dao'], dropSources:['Thanh Lang','hang dong linh mach'] },
  { id:'ore_1_3', rank:1, rankName:'Nhat Pham', name:'Ngung Linh Thach', emoji:'💠', icon:'ore_icon_ore_1_3', color:'#67e8f9', price:90, hardness:6, purity:70, desc:'Da ngung tu linh khi so ky, cuc ky quan trong trong luyen dan Nhat Pham.', uses:['nguyen lieu luyen dan Nhat Pham','ket tran Nhat Pham'], dropSources:['Doc Giac Tru','suoi linh mach'] },
  { id:'ore_1_4', rank:1, rankName:'Nhat Pham', name:'Huyen Thiet Tinh', emoji:'⚫', icon:'ore_icon_ore_1_4', color:'#1e293b', price:100, hardness:7, purity:72, desc:'Huyen thiet chua han khi cung ran bat thuong, luyen phap khi sac ben va ben lau.', uses:['ren phap khi han tinh','lam kiem tien so cap'], dropSources:['Huyet Tich Ma','dia mach han bang'] },
  { id:'ore_1_5', rank:1, rankName:'Nhat Pham', name:'Xich Kim Sa', emoji:'🟠', icon:'ore_icon_ore_1_5', color:'#f97316', price:120, hardness:6, purity:68, desc:'Cat vang do lay tu song linh mach hoa he, tang hoa luc phap bao.', uses:['tang hoa cong phap bao','luyen phu luc hoa tinh'], dropSources:['vung hoa linh mach','Huyet Tich Ma'] },
  { id:'ore_1_6', rank:1, rankName:'Nhat Pham', name:'Truc Co Thach', emoji:'🟡', icon:'ore_icon_ore_1_6', color:'#facc15', price:150, hardness:7, purity:75, desc:'Linh thach dac biet giup cu co can co tu tien, nguyen lieu then chot Nhat Pham.', uses:['can co tu tien Luyen Khi','nguyen lieu dot pha'], dropSources:['Huyet Lang Van Moc','linh mach Nhat Pham'] },

  // ===== NHI PHAM (rank 2) =====
  { id:'ore_2_1', rank:2, rankName:'Nhi Pham', name:'Huyen Thiet Khoang', emoji:'🔷', icon:'ore_icon_ore_2_1', color:'#3b82f6', price:400, hardness:7, purity:78, desc:'Quang huyen thiet Nhi Pham, hap thu nguyen khi thien dia day dac hon.', uses:['ren phap khi Nhi Pham','kiem linh Truc Co'], dropSources:['Thiet Giap Te Nguu','nui linh mach Truc Co'] },
  { id:'ore_2_2', rank:2, rankName:'Nhi Pham', name:'Han Bang Tinh', emoji:'❄️', icon:'ore_icon_ore_2_2', color:'#93c5fd', price:500, hardness:8, purity:80, desc:'Tinh khoang tu dia mach han bang ngan nam, chua linh luc bang han thuan tuy.', uses:['phap khi bang han','phu luc han he Nhi Pham'], dropSources:['Hoa Duc Quy','hang bang linh mach'] },
  { id:'ore_2_3', rank:2, rankName:'Nhi Pham', name:'Lou Quang Thach', emoji:'⚡', icon:'ore_icon_ore_2_3', color:'#fbbf24', price:600, hardness:7, purity:82, desc:'Da chua lou khi thien nhien, duc phap bao lou he va lam dan dien lou phu.', uses:['phap bao lou he','phu luc lou Nhi Pham'], dropSources:['Thiet Giap Ky Ma','dinh lou son linh mach'] },
  { id:'ore_2_4', rank:2, rankName:'Nhi Pham', name:'Tu Kim Sa', emoji:'💜', icon:'ore_icon_ore_2_4', color:'#a855f7', price:700, hardness:8, purity:83, desc:'Cat vang tim tu linh mach Truc Co, tinh chat lam tang hieu qua luyen phu.', uses:['phu luc Nhi Pham','tran phap Truc Co'], dropSources:['Hoa Nam Cu Giai','linh mach Truc Co'] },
  { id:'ore_2_5', rank:2, rankName:'Nhi Pham', name:'Bich Ngoc Khoang', emoji:'💚', icon:'ore_icon_ore_2_5', color:'#2dd4bf', price:850, hardness:8, purity:85, desc:'Quang ngoc bich thien nhien chua moc linh khi, dung luyen phap khi moc he.', uses:['phap khi moc he Nhi Pham','tang sinh menh luc'], dropSources:['Hoa Nam Cu Giai','rung linh mach sau'] },
  { id:'ore_2_6', rank:2, rankName:'Nhi Pham', name:'Tinh Kim Khoang', emoji:'✨', icon:'ore_icon_ore_2_6', color:'#fde047', price:1000, hardness:9, purity:88, desc:'Tinh kim thuan chat hap thu kim linh khi, nguyen lieu kiem phap khi Truc Co dinh phong.', uses:['kiem phap khi Nhi Pham Cuc Pham','luyen dan ho tro'], dropSources:['Hoa Nam Cu Giai Dinh Phong','linh mach kim he'] },

  // ===== TAM PHAM (rank 3) =====
  { id:'ore_3_1', rank:3, rankName:'Tam Pham', name:'Thien Cuong Tinh', emoji:'🔩', icon:'ore_icon_ore_3_1', color:'#94a3b8', price:3000, hardness:9, purity:88, desc:'Tinh khoang Thien Cuong tu vung kim dan linh mach, cung vo song khong gi pha noi.', uses:['ren phap khi Kim Dan','kiem tien Tam Pham'], dropSources:['U Minh Mang Xa','Kim Dan linh mach'] },
  { id:'ore_3_2', rank:3, rankName:'Tam Pham', name:'Luu Ly Tinh', emoji:'🔮', icon:'ore_icon_ore_3_2', color:'#818cf8', price:3500, hardness:8, purity:90, desc:'Luu ly thuan chat xuyen suot than thuc, tang cuong than hon va y niem.', uses:['phap khi than thuc Tam Pham','tran phap tam linh'], dropSources:['Duong Lang Yeu','dia linh mach than thuc'] },
  { id:'ore_3_3', rank:3, rankName:'Tam Pham', name:'Huyet Ngoc Thach', emoji:'❤️', icon:'ore_icon_ore_3_3', color:'#e11d48', price:4000, hardness:8, purity:89, desc:'Da ngoc mau huyet do ngung tu sinh menh luc cua dia mach, phuc hoi va tang HP.', uses:['phap khi sinh menh Tam Pham','hoi phuc dan duoc'], dropSources:['Luc Doc Chu','linh mach huyet tinh'] },
  { id:'ore_3_4', rank:3, rankName:'Tam Pham', name:'Tinh Hoa Van Tinh', emoji:'☄️', icon:'ore_icon_ore_3_4', color:'#f97316', price:5000, hardness:10, purity:91, desc:'Van tinh roi tu thien thuong chua hoa tinh cuc thuan, uy luc kinh nguoi.', uses:['phap khi hoa Tam Pham','phu luc hoa cuc pham'], dropSources:['Doc Nhan Vu Su','vung van tinh thien nhien'] },
  { id:'ore_3_5', rank:3, rankName:'Tam Pham', name:'Han Nguyet Tinh', emoji:'🌙', icon:'ore_icon_ore_3_5', color:'#a5f3fc', price:5500, hardness:9, purity:92, desc:'Tinh khoang ngung tu linh luc nguyet quang ngan nam, han luc bao trum.', uses:['phap khi han Tam Pham','tran phap am han'], dropSources:['Doc Nhan Vu Su','linh mach am han'] },
  { id:'ore_3_6', rank:3, rankName:'Tam Pham', name:'Than Lou Tinh', emoji:'🌩️', icon:'ore_icon_ore_3_6', color:'#7c3aed', price:7000, hardness:9, purity:93, desc:'Tinh khoang thu hut lou kiep thien nhien, luyen phap khi lou he cuc pham.', uses:['phap khi lou Tam Pham Cuc Pham','dan duoc dot pha'], dropSources:['Doc Nhan Vu Su Dinh Phong','dinh thien lou linh mach'] },

  // ===== TU PHAM (rank 4) =====
  { id:'ore_4_1', rank:4, rankName:'Tu Pham', name:'Can Thiet Tinh', emoji:'⚔️', icon:'ore_icon_ore_4_1', color:'#e2e8f0', price:20000, hardness:10, purity:93, desc:'Thiet tinh hung chiu van lou, duc than khi Nguyen Anh bat kha xam pham.', uses:['than khi Tu Pham','phap bao bac Nguyen Anh'], dropSources:['Kho Lau Binh','Nguyen Anh linh mach'] },
  { id:'ore_4_2', rank:4, rankName:'Tu Pham', name:'Than Ngoc Tinh', emoji:'🌟', icon:'ore_icon_ore_4_2', color:'#fef08a', price:25000, hardness:9, purity:95, desc:'Ngoc than ngung tu tinh luc thien dia, lien ket than thuc voi thien dao.', uses:['than khi than thuc Tu Pham','ngung tu Nguyen Anh'], dropSources:['Kho Lau Cung Thu','linh mach Nguyen Anh'] },
  { id:'ore_4_3', rank:4, rankName:'Tu Pham', name:'Thien Ma Tinh', emoji:'🟣', icon:'ore_icon_ore_4_3', color:'#701a75', price:30000, hardness:10, purity:94, desc:'Tinh khoang ma tinh tu vung co chien truong, hoa hop ma va tien nguyen khi.', uses:['than khi ma he Tu Pham','luyen phap khi am ma'], dropSources:['Goblin Dao Tac','dia mach ma tinh'] },
  { id:'ore_4_4', rank:4, rankName:'Tu Pham', name:'Xich Long Tinh', emoji:'🔴', icon:'ore_icon_ore_4_4', color:'#dc2626', price:40000, hardness:10, purity:95, desc:'Tinh khoang ngung tu long tuc, tang cuong uy ap va khi truong cua phap bao.', uses:['phap bao long tuc Tu Pham','tang uy ap canh gioi'], dropSources:['Xich Diem Phi Long','dia mach long uyen'] },
  { id:'ore_4_5', rank:4, rankName:'Tu Pham', name:'Thai Hu Tinh', emoji:'🌀', icon:'ore_icon_ore_4_5', color:'#6366f1', price:50000, hardness:9, purity:96, desc:'Tinh thach tu hu khong thien dia, dung mo khong gian di bao va luu tru phap luc.', uses:['khong gian di bao','luu tru phap luc Nguyen Anh'], dropSources:['Xich Diem Phi Long','khe ho khong gian'] },
  { id:'ore_4_6', rank:4, rankName:'Tu Pham', name:'Ngu Hanh Linh Tinh', emoji:'🌈', icon:'ore_icon_ore_4_6', color:'#06b6d4', price:65000, hardness:10, purity:97, desc:'Tinh khoang ngu hanh hoa quyen hoan my, nguyen lieu luyen than khi can bang cuc pham.', uses:['than khi ngu hanh Tu Pham Cuc Pham','tran phap ngu hanh'], dropSources:['Xich Diem Phi Long Dinh Phong','dia mach ngu hanh'] },

  // ===== NGU PHAM (rank 5) =====
  { id:'ore_5_1', rank:5, rankName:'Ngu Pham', name:'Hon Nguyen Thiet', emoji:'🏔️', icon:'ore_icon_ore_5_1', color:'#44403c', price:200000, hardness:10, purity:97, desc:'Thiet khoang tu hon nguyen thai so, ren chi bao Hoa Than bat hoai vinh hang.', uses:['chi bao Hoa Than','luyen tien khi sieu cap'], dropSources:['Thai Co Chan Long','dia mach hon nguyen'] },
  { id:'ore_5_2', rank:5, rankName:'Ngu Pham', name:'Tien Ngoc Tinh', emoji:'💎', icon:'ore_icon_ore_5_2', color:'#f0abfc', price:280000, hardness:9, purity:98, desc:'Ngoc tien thuan chat tu tien gioi rot xuong, lien thong thien dao va tien dao.', uses:['phi thang tien gioi chuan bi','phap bao Ngu Pham'], dropSources:['Cuu Tieu Ma Ton','linh mach tien gioi tan du'] },
  { id:'ore_5_3', rank:5, rankName:'Ngu Pham', name:'Hu Khong Tinh', emoji:'🌌', icon:'ore_icon_ore_5_3', color:'#4f46e5', price:350000, hardness:10, purity:98, desc:'Tinh khoang ton tai giua hu khong vu tru, be gay khong gian va thoi gian.', uses:['phap bao khong gian Ngu Pham','ngung luyen thien menh'], dropSources:['Hon Don Cu Thu','khe ho vu tru'] },
  { id:'ore_5_4', rank:5, rankName:'Ngu Pham', name:'Tao Hoa Than Tinh', emoji:'⭐', icon:'ore_icon_ore_5_4', color:'#fbbf24', price:500000, hardness:10, purity:99, desc:'Than tinh xuat hien khi tao hoa moi khai, ham chua moi dai dao nguyen ly.', uses:['chi bao dai dao','dot pha Hoa Than Dinh Phong'], dropSources:['Chi Ton Than Ma Chi Chu','dai thien dia linh mach'] },
  { id:'ore_5_5', rank:5, rankName:'Ngu Pham', name:'Vo Cuc Thien Tinh', emoji:'♾️', icon:'ore_icon_ore_5_5', color:'#e0e7ff', price:700000, hardness:10, purity:99, desc:'Tinh khoang tu vo cuc thien dao sieu viet, bieu tuong tuyet dinh cua tu chan.', uses:['luyen chi bao vo cuc','thien dao cong minh'], dropSources:['Chi Ton Than Ma Chi Chu','thien dao linh mach'] },
  { id:'ore_5_6', rank:5, rankName:'Ngu Pham', name:'Khai Thien Hon Nguyen Tinh', emoji:'🌠', icon:'ore_icon_ore_5_6', color:'#f43f5e', price:1000000, hardness:10, purity:100, desc:'Tinh khoang duy nhat ton tai tu thoi khai thien lap dia, do thuan khiet tuyet doi.', uses:['chi bao khai thien','phi thang tien gioi yeu to cot loi'], dropSources:['Chi Ton Than Ma Chi Chu Dinh Phong','cuc dia thien dao'] },

  // ===== BO SUNG: PHAM CAP (4 loai them, tong 10) =====
  { id:'ore_0_7', rank:0, rankName:'Pham Cap', name:'Sat Vi Khoang', emoji:'🔧', icon:'ore_icon_ore_0_7', color:'#78716c', price:6, hardness:2, purity:28, desc:'Manh sat vi rach ra tu khoang sat chu, dung han gan va sua chua do vat pham nhan.', uses:['sua chua cong cu','han gan pham nhan'], dropSources:['Pham Thu','khai thac ven doi'] },
  { id:'ore_0_8', rank:0, rankName:'Pham Cap', name:'Vang Sa Khoang', emoji:'🟡', icon:'ore_icon_ore_0_8', color:'#ca8a04', price:18, hardness:2, purity:40, desc:'Cat vang pham chat tu long song, duc tien xu giao thuong va lam do trang suc pham.', uses:['duc tien vang','do trang suc pham nhan'], dropSources:['long song','Pham Thu boi long'] },
  { id:'ore_0_9', rank:0, rankName:'Pham Cap', name:'Bach Thach Khoi', emoji:'🤍', icon:'ore_icon_ore_0_9', color:'#f1f5f9', price:9, hardness:3, purity:32, desc:'Da trang pham chat dung xay dung nha cua phong thi va mat dat nen lo dan so cap.', uses:['xay dung nha cua','mat dat lo dan pham'], dropSources:['mo da trang','Tieu Da Tru'] },
  { id:'ore_0_10', rank:0, rankName:'Pham Cap', name:'Kim Tinh Sa', emoji:'✨', icon:'ore_icon_ore_0_10', color:'#d97706', price:25, hardness:4, purity:52, desc:'Cat tinh vang nguyen chat hoi tu tu cat song linh, pham nhan ban duoc gia cao.', uses:['vat lieu trang suc quy','nen cho luyen dan pham cap'], dropSources:['vung cat linh','thuong nhan cao cap pham'] },

  // ===== BO SUNG: NHAT PHAM (4 loai them, tong 10) =====
  { id:'ore_1_7', rank:1, rankName:'Nhat Pham', name:'Bach Kim Khoang', emoji:'🔘', icon:'ore_icon_ore_1_7', color:'#e2e8f0', price:130, hardness:6, purity:68, desc:'Bach kim tinh luyen Nhat Pham, cung va deo dai hon bac thuong, dung ren phap khi nhe.', uses:['ren phap khi nhe Nhat Pham','vong tay linh luc'], dropSources:['khoang bac cao nguyen','Nhat Pham Yeu Thu'] },
  { id:'ore_1_8', rank:1, rankName:'Nhat Pham', name:'Cu Linh Thach', emoji:'💙', icon:'ore_icon_ore_1_8', color:'#3b82f6', price:110, hardness:5, purity:65, desc:'Da xanh dam hap thu linh khi nuoc song linh mach, giam ma sat trong chien dau.', uses:['phap khi thuy he Nhat Pham','giam sat thuong phan xa'], dropSources:['ven suoi linh mach','Thanh Lang'] },
  { id:'ore_1_9', rank:1, rankName:'Nhat Pham', name:'Hoa Linh Tho Thach', emoji:'🔴', icon:'ore_icon_ore_1_9', color:'#ef4444', price:140, hardness:6, purity:70, desc:'Da tho hoa linh Nhat Pham, chua nhiet luc lam tang hoa cong luyen dan phu can ban.', uses:['tang hoa cong phu luc','luyen lo dan hoa Nhat Pham'], dropSources:['nui lua linh mach','Hoa Tho'] },
  { id:'ore_1_10', rank:1, rankName:'Nhat Pham', name:'Pho Phong Sa', emoji:'💨', icon:'ore_icon_ore_1_10', color:'#bae6fd', price:160, hardness:5, purity:72, desc:'Cat pho phong Nhat Pham lay tu dinh nui cao, tang toc do phap bao phong he.', uses:['phap bao phong he Nhat Pham','tang toc giai doan'], dropSources:['dinh nui phong mach','Nhat Pham Pho Phong Thu'] },

  // ===== BO SUNG: NHI PHAM (4 loai them, tong 10) =====
  { id:'ore_2_7', rank:2, rankName:'Nhi Pham', name:'Huyen Am Khoang', emoji:'🌑', icon:'ore_icon_ore_2_7', color:'#1e293b', price:780, hardness:8, purity:82, desc:'Quang am linh Nhi Pham cuc thuan, dung luyen phap khi am he uy luc cao Truc Co.', uses:['phap khi am he Nhi Pham','phu luc am tinh'], dropSources:['dong am linh mach','Am Sinh Ma'] },
  { id:'ore_2_8', rank:2, rankName:'Nhi Pham', name:'Duong Hoa Khoang', emoji:'☀️', icon:'ore_icon_ore_2_8', color:'#fcd34d', price:820, hardness:7, purity:80, desc:'Quang duong hoa tuong phan Am Khoang, tang cuong duong luc phap khi su pham manh.', uses:['phap khi duong he Nhi Pham','doi trong voi Huyen Am'], dropSources:['dinh nui day nang','Duong Tinh Thu'] },
  { id:'ore_2_9', rank:2, rankName:'Nhi Pham', name:'Moc Tinh Khoang', emoji:'🌿', icon:'ore_icon_ore_2_9', color:'#4ade80', price:900, hardness:7, purity:83, desc:'Tinh khoang moc he Nhi Pham ngung tu sinh luc thinh viet, tang HP hoi phuc.', uses:['phap khi moc he Nhi Pham','dan duoc sinh menh'], dropSources:['rung linh mach sau','Cu Giai Xa'] },
  { id:'ore_2_10', rank:2, rankName:'Nhi Pham', name:'Khoang Linh Van Sa', emoji:'🌫️', icon:'ore_icon_ore_2_10', color:'#94a3b8', price:950, hardness:8, purity:86, desc:'Cat linh van Nhi Pham doi tu mat dat linh mach bay len, rat kho ket tinh thuong.', uses:['nguyen lieu tren nguoi Nhi Pham','ket tran khong khi'], dropSources:['vung linh van ma','mot so nui cao'] },

  // ===== BO SUNG: TAM PHAM (4 loai them, tong 10) =====
  { id:'ore_3_7', rank:3, rankName:'Tam Pham', name:'Xich Diem Tinh', emoji:'🔥', icon:'ore_icon_ore_3_7', color:'#dc2626', price:6000, hardness:9, purity:90, desc:'Tinh khoang hoa linh Kim Dan, nhiet do gap 3 lan Lou Tinh, luyen phap khi hoa cuc pham.', uses:['phap khi hoa Tam Pham Cuc Pham','dan duoc pha canh'], dropSources:['Hoa Phuong Bach Tuoc','nui lua linh mach Kim Dan'] },
  { id:'ore_3_8', rank:3, rankName:'Tam Pham', name:'Mo Ngan Tinh', emoji:'🔵', icon:'ore_icon_ore_3_8', color:'#0ea5e9', price:6500, hardness:9, purity:91, desc:'Ngan tinh thuon nguon Kim Dan, phan xa anh sang lam mat linh thuc va chong can nhieu.', uses:['chong can nhieu tinh than','phap khi phan xa'], dropSources:['hang ngan linh mach','Am Cuu Duoi Nuoc'] },
  { id:'ore_3_9', rank:3, rankName:'Tam Pham', name:'Phong Tinh Khoang', emoji:'🌀', icon:'ore_icon_ore_3_9', color:'#7c3aed', price:7500, hardness:8, purity:92, desc:'Khoang tinh gio Tam Pham ngung tu phong khi thien nhien, tang toc pho phong phap bao.', uses:['phap bao phong toc Tam Pham','tran kieu van du'], dropSources:['dinh nui cao phong linh mach','Kim Dan Phong Thu'] },
  { id:'ore_3_10', rank:3, rankName:'Tam Pham', name:'Dinh The Tinh Thach', emoji:'🏆', icon:'ore_icon_ore_3_10', color:'#ca8a04', price:9000, hardness:10, purity:93, desc:'Da tinh vang dinh the hoa tu kim dan linh mach dinh phong, ai co cung de nghi ngut.', uses:['phap khi Kim Dan dinh phong','chu tran nen lo phan thuong'], dropSources:['Kim Dan linh mach dinh phong','thi truong bi mat tu tien'] },

  // ===== BO SUNG: TU PHAM (4 loai them, tong 10) =====
  { id:'ore_4_7', rank:4, rankName:'Tu Pham', name:'Nguyen Anh Hoa Thach', emoji:'💫', icon:'ore_icon_ore_4_7', color:'#c026d3', price:55000, hardness:9, purity:96, desc:'Da hoa tu nguyen anh tien nhan tu hoa, lien thong nguyen anh voi vat chat huu hinh.', uses:['linh khi nguyen anh','ket hop vat chat va tinh than'], dropSources:['Long Ho Cuoc Dau','vung nguyen anh di tich'] },
  { id:'ore_4_8', rank:4, rankName:'Tu Pham', name:'Vo Thuong Vuong Tinh', emoji:'👑', icon:'ore_icon_ore_4_8', color:'#eab308', price:70000, hardness:10, purity:96, desc:'Tinh khoang vuong cap Nguyen Anh, chi co tien nhan canh gioi Tu Pham moi tim duoc.', uses:['phap bao cap vuong Tu Pham','dan duoc Cuc Pham Tu Pham'], dropSources:['Tu Pham Cuong Gian','kho bau tu tien co dai'] },
  { id:'ore_4_9', rank:4, rankName:'Tu Pham', name:'Am Duong Lieu Tinh', emoji:'☯️', icon:'ore_icon_ore_4_9', color:'#8b5cf6', price:80000, hardness:9, purity:97, desc:'Tinh khoang chua ca am va duong can bang hoan hao, bat kha thi Nguyen Anh Ky.', uses:['can bang am duong phap khi','nguyen lieu phan duong dan'], dropSources:['Am Duong Cau','dia mach cau dong'] },
  { id:'ore_4_10', rank:4, rankName:'Tu Pham', name:'Thien Viet Khoang', emoji:'🌌', icon:'ore_icon_ore_4_10', color:'#1d4ed8', price:95000, hardness:10, purity:97, desc:'Khoang viet qua gioi han vat chat thuong, xu ly phap bao Tu Pham co the lam tu nguyen anh.', uses:['phap bao tu nguyen anh','khoang vuot canh gioi'], dropSources:['Phi Tien Chu Tu','dia mach tu pham dinh phong'] },

  // ===== BO SUNG: NGU PHAM (4 loai them, tong 10) =====
  { id:'ore_5_7', rank:5, rankName:'Ngu Pham', name:'Tao Hoa Khai Thien Tinh', emoji:'🌟', icon:'ore_icon_ore_5_7', color:'#fef08a', price:1200000, hardness:10, purity:100, desc:'Tinh khoang xuat hien luc tao hoa mo mang thien dia, mang nang luong khai thien nguyen thuy.', uses:['chi bao toa hoa Ngu Pham','nguon goc su pham sieu cap'], dropSources:['Chi Ton Than Ma tu ngu','cuc dia tao hoa linh mach'] },
  { id:'ore_5_8', rank:5, rankName:'Ngu Pham', name:'Nhat Nguyet Quang Tinh', emoji:'🌗', icon:'ore_icon_ore_5_8', color:'#f0abfc', price:1500000, hardness:9, purity:99, desc:'Tinh hoa quang minh nhat nguyet hoi tu ngan nam, hai nguon sang am duong toan hao.', uses:['cong phu am duong song tu','dan duoc sieu cap Ngu Pham'], dropSources:['Chi Ton Than Ma','nui nhat nguyet giao nhau'] },
  { id:'ore_5_9', rank:5, rankName:'Ngu Pham', name:'Thien Dao Chan Tinh', emoji:'⚖️', icon:'ore_icon_ore_5_9', color:'#4ade80', price:2000000, hardness:10, purity:100, desc:'Chan tinh thien dao khong the ban duoc, ai so huu duoc la nguoi cam thu duoc thien dao.', uses:['cong phu thien dao','nguyen ly chap thuan vay chau'], dropSources:['cuc ky hiem - chung kien thien dao hoi tu','giao hoi thien dai'] },
  { id:'ore_5_10', rank:5, rankName:'Ngu Pham', name:'Hon Don Nguyen Tinh', emoji:'🫧', icon:'ore_icon_ore_5_10', color:'#e0e7ff', price:3000000, hardness:10, purity:100, desc:'Nguyen tinh hon don tu truoc khi vu tru hinh thanh, tuyet dinh nhat vat chat ton tai.', uses:['chi bao truoc khai thien','sieu viet canh gioi Hoa Than'], dropSources:['chi xuat hien trong toan canh gioi ket thuc','tren canh gioi hoa than dinh phong'] }
];


export function getMineralById(id) { return ALL_MINERALS.find(m => m.id === id) || null; }
export function getMineralByName(name) { return ALL_MINERALS.find(m => m.name === name) || null; }
export function getMineralsByRank(rank) { return ALL_MINERALS.filter(m => m.rank === rank); }
export function getMineralsForCrafting(rank) { return ALL_MINERALS.filter(m => m.rank === rank); }
export function getMineralSilverValue(mineral) { return mineral ? mineral.price : 0; }
