(()=>{'use strict';
const master=window.TuTienSkillMaster;if(!master||master.skillCount!==144)throw new Error('SkillSystem cần đúng 144 skill');
const cache=new Map();
function elementName(key){for(const [name,data] of Object.entries(master.elements))if(data.key===key)return name;return'Kiếm';}
function get(id){if(cache.has(id))return cache.get(id);const [elemKey,tierRaw,rankRaw]=String(id||'').split('_'),tierIdx=Number(tierRaw),rankIdx=Number(rankRaw);if(!Number.isInteger(tierIdx)||!Number.isInteger(rankIdx)||tierIdx<0||tierIdx>3||rankIdx<0||rankIdx>3)return null;const element=elementName(elemKey),edata=master.elements[element],balance=master.balance[tierIdx*4+rankIdx],tier=master.tiers[tierIdx],rank=master.ranks[rankIdx],profile=edata&&edata.profiles[rankIdx]||{};if(!edata||!balance)return null;const flat=tierIdx*4+rankIdx,name=edata.names[flat]||`Bí Kíp ${tierIdx}-${rankIdx}`;const skill={id,name,element,elemKey,tierIdx,rankIdx,tierId:tier.id,rankId:rank.id,tierName:tier.name,rankName:rank.name,tierColor:tier.color,badge:(tier.badge||tier.name||'')+'·'+String(rank.name||'').charAt(0),...balance,spiritScaling:!!edata.spiritScaling,icon:`assets/skills/${elemKey}/${tier.id}_${rank.id}.png`,vfx:`assets/vfx/skills/${elemKey}/${tier.id}_${rank.id}.png`,role:profile.role||'',mechanicText:name+': '+(profile.mechanic||''),statusText:profile.status||'',effect:profile.effect||null};cache.set(id,skill);return skill;}
function equippedAssets(state){const paths=[];for(const id of state&&state.equippedSkills||[]){const skill=get(id);if(skill)paths.push(skill.icon,skill.vfx);}return[...new Set(paths)];}
function validate(){const ids=new Set();for(const data of Object.values(master.elements))for(let t=0;t<4;t++)for(let r=0;r<4;r++)ids.add(`${data.key}_${t}_${r}`);return{ok:ids.size===144,count:ids.size};}
window.SkillSystem={get,equippedAssets,validate,master,clearCache:()=>cache.clear()};
})();
