const SECT_ARCHETYPES = new Set(['SECT']);
export const SECT_RANKS = Object.freeze(['Tạp Dịch','Đệ Tử Ngoại Môn','Đệ Tử Nội Môn','Đệ Tử Chân Truyền','Chấp Sự','Trưởng Lão','Điện Chủ','Thái Thượng Trưởng Lão','Tông Chủ']);
const FONT = 'Be Vietnam Pro, sans-serif';
export const fmt = value => Math.round(Number(value || 0)).toLocaleString('vi-VN');

export function getSectCoordinator(scene) { return scene?.getFactionRuntimeCoordinator?.() || scene?.__factionCoordinator || null; }
export function getSectNetwork(scene) { return getSectCoordinator(scene)?.network || scene?.getFactionRuntime?.()?.network || null; }
function factionFromOverride(network,value){if(!value)return null;if(typeof value==='string')return network?.getFaction?.(value)||null;if(value.id)return network?.getFaction?.(value.id)||value;return null;}
function pickContextSect(scene,network){const context=scene?.getCurrentFactionContext?.()||scene?.__factionContext||null;if(!context)return null;const id=context.controllers?.cultivationController;const controlled=id?network?.getFaction?.(id):null;if(controlled&&SECT_ARCHETYPES.has(controlled.archetype))return controlled;return(context.factions||[]).find(f=>SECT_ARCHETYPES.has(f?.archetype))||null;}

export function resolveSectContext(scene,factionOverride=null){
  const coordinator=getSectCoordinator(scene);coordinator?.expireContracts?.();const network=getSectNetwork(scene),state=coordinator?.state||coordinator?.gameState?.factionState||null;
  let faction=factionFromOverride(network,factionOverride);if(faction&&!SECT_ARCHETYPES.has(faction.archetype))faction=null;
  const affiliation=state?.affiliations?.CULTIVATION||state?.affiliations?.cultivation||null;
  if(!faction)faction=pickContextSect(scene,network);
  if(!faction&&affiliation?.factionId){const f=network?.getFaction?.(affiliation.factionId);if(f&&SECT_ARCHETYPES.has(f.archetype))faction=f;}
  if(!faction)return null;
  const relation=state?.relations?.[faction.id]||Object.freeze({factionId:faction.id,reputation:0,trust:0,loyalty:0,contribution:0,prestige:0,debt:0,membershipRank:null});
  const membership=affiliation?.factionId===faction.id?affiliation:null;
  const detail=coordinator?.materializeFactionSystems?.(faction.id)||null,branches=network?.getFactionBranches?.(faction.id)||[],vassals=network?.getFactionVassals?.(faction.id)||[];
  const territoryId=coordinator?.currentTerritoryId||scene?.getCurrentFactionContext?.()?.territoryId||null,localBranch=branches.find(b=>b.territoryId===territoryId)||null;
  return {scene,coordinator,network,state,faction,relation,membership,detail,branches,vassals,territoryId,localBranch};
}
export function isSectMember(ctx){return!!ctx?.membership;}
export function sectRank(ctx){return ctx?.relation?.membershipRank||ctx?.membership?.membershipRank||ctx?.membership?.rank||(isSectMember(ctx)?SECT_RANKS[0]:'Khách Vãng Lai');}
export function sectRankIndex(ctx){const i=SECT_RANKS.indexOf(sectRank(ctx));return i<0?-1:i;}
export function relationBand(value){const v=Number(value||0);if(v<=-800)return'Tử Thù';if(v<=-400)return'Thù Địch';if(v<=-100)return'Ác Cảm';if(v<100)return'Trung Lập';if(v<300)return'Thiện Cảm';if(v<600)return'Hữu Hảo';if(v<900)return'Tôn Kính';return'Sùng Kính';}
export function sectSummary(ctx){const econ=ctx?.detail?.economy||{};return ctx?Object.freeze({name:ctx.faction.name,rank:sectRank(ctx),member:isSectMember(ctx),reputation:Number(ctx.relation.reputation||0),trust:Number(ctx.relation.trust||0),loyalty:Number(ctx.relation.loyalty||0),contribution:Number(ctx.relation.contribution||0),treasury:Number(econ.treasury??ctx.faction.economy?.treasury??0),branches:ctx.branches.length,vassals:ctx.vassals.length,localBranch:ctx.localBranch?.name||ctx.localBranch?.id||null,relationBand:relationBand(ctx.relation.reputation)}):null;}
export function updateSectRelation(ctx,delta={}){if(!ctx?.coordinator)return null;const next=ctx.coordinator.updateFactionReputation(ctx.faction.id,delta);ctx.coordinator.syncToGameState?.();return next;}
export function setSectMembershipRank(ctx,membershipRank){if(!ctx?.coordinator||!ctx?.faction?.id)return null;const current=ctx.state?.relations?.[ctx.faction.id]||ctx.relation||{factionId:ctx.faction.id};const next=Object.freeze({...current,membershipRank:membershipRank??null});ctx.coordinator.state.relations={...(ctx.coordinator.state.relations||{}),[ctx.faction.id]:next};const affiliation=ctx.coordinator.state.affiliations?.CULTIVATION;if(affiliation?.factionId===ctx.faction.id&&membershipRank!=null)ctx.coordinator.setPlayerAffiliation('CULTIVATION',ctx.faction.id,{...affiliation,membershipRank});ctx.coordinator.syncToGameState?.();return next;}
export function recordSectMemory(ctx,type='helpedFaction',{severity=1,actionKey=null,meta={}}={}){if(!ctx?.coordinator)return null;const m=ctx.coordinator.addFactionMemory(ctx.faction.id,type,{severity,sourceTerritoryId:ctx.territoryId,meta:{...meta,actionKey,timestamp:Date.now()}});ctx.coordinator.syncToGameState?.();return m;}
export function claimSectTimedBenefit(ctx,actionKey,cooldownMs,{contribution=0,loyalty=0,prestige=0,severity=.2,toast='Đã nhận bổng lộc.'}={}){if(!isSectMember(ctx))return{ok:false,message:'Bạn chưa phải đệ tử tông môn này.'};const list=ctx.state?.memories?.[ctx.faction.id]||[];const last=[...list].reverse().find(m=>m?.meta?.actionKey===actionKey);const remain=Math.max(0,cooldownMs-(Date.now()-Number(last?.meta?.timestamp||0)));if(remain>0)return{ok:false,reason:'COOLDOWN',remainMs:remain,message:`Còn ${Math.ceil(remain/3600000)} giờ mới có thể nhận lại.`};recordSectMemory(ctx,'helpedFaction',{severity,actionKey});updateSectRelation(ctx,{contribution,loyalty,prestige});return{ok:true,message:toast};}
export function spendSectContribution(ctx,amount){amount=Math.max(0,Number(amount||0));if(!isSectMember(ctx))return{ok:false,message:'Chỉ đệ tử tông môn mới sử dụng được.'};const current=Number(ctx.state?.relations?.[ctx.faction.id]?.contribution??ctx.relation?.contribution??0);if(current<amount)return{ok:false,message:`Cần ${fmt(amount)} cống hiến, hiện có ${fmt(current)}.`};updateSectRelation(ctx,{contribution:-amount});return{ok:true,remaining:current-amount};}
export function joinSect(ctx){if(!ctx?.coordinator)return{ok:false,message:'Faction V5 chưa sẵn sàng.'};if(isSectMember(ctx))return{ok:false,message:'Bạn đã là đệ tử tông môn này.'};const occupied=ctx.state?.affiliations?.CULTIVATION;if(occupied?.factionId&&occupied.factionId!==ctx.faction.id)return{ok:false,message:'Bạn đang có một thế lực tu luyện chính. Hãy rời thế lực đó trước.'};ctx.coordinator.setPlayerAffiliation('CULTIVATION',ctx.faction.id,{membershipRank:'Tạp Dịch',joinedAt:Date.now(),source:'sect_hall'});updateSectRelation(ctx,{reputation:20,trust:10,loyalty:10});setSectMembershipRank(ctx,'Tạp Dịch');recordSectMemory(resolveSectContext(ctx.scene,ctx.faction.id),'helpedFaction',{severity:.2,actionKey:'sect.join'});return{ok:true,message:`Đã bái nhập ${ctx.faction.name} với thân phận Tạp Dịch.`};}
export function leaveSect(ctx){if(!isSectMember(ctx))return{ok:false,message:'Bạn không phải đệ tử tông môn này.'};ctx.coordinator.clearPlayerAffiliation('CULTIVATION');updateSectRelation(ctx,{loyalty:-120,reputation:-40});setSectMembershipRank(ctx,null);ctx.coordinator.syncToGameState?.();return{ok:true,message:`Đã rời ${ctx.faction.name}. Quan hệ cá nhân vẫn được lưu.`};}
export function promoteSectMember(ctx){if(!isSectMember(ctx))return{ok:false,message:'Bạn chưa phải đệ tử chính thức.'};const rel=ctx.state?.relations?.[ctx.faction.id]||ctx.relation,idx=Math.max(0,SECT_RANKS.indexOf(rel.membershipRank||sectRank(ctx)));if(idx>=SECT_RANKS.length-1)return{ok:false,message:'Đã đạt cấp bậc cao nhất.'};const req=[0,120,450,1200,2600,5200,8500,13500,22000],rep=[0,0,100,250,400,600,750,880,950],next=idx+1;if(Number(rel.contribution||0)<req[next])return{ok:false,message:`Cần ${fmt(req[next])} tổng cống hiến để thăng ${SECT_RANKS[next]}.`};if(Number(rel.reputation||0)<rep[next])return{ok:false,message:`Cần ${fmt(rep[next])} uy tín tông môn.`};updateSectRelation(ctx,{prestige:30,loyalty:12});setSectMembershipRank(ctx,SECT_RANKS[next]);return{ok:true,rank:SECT_RANKS[next],message:`Khảo hạch thành công: ${SECT_RANKS[next]}.`};}
export function acceptSectDuty(ctx,{type='protector',duration=12,payment={},obligations=[],penalties=[]}={}){if(!ctx?.coordinator)return{ok:false,message:'Faction V5 chưa sẵn sàng.'};if(!isSectMember(ctx))return{ok:false,message:'Chỉ đệ tử tông môn mới nhận được ủy thác nội bộ.'};const exists=(ctx.state?.contracts||[]).find(c=>c.factionId===ctx.faction.id&&c.type===type&&c.status==='active');if(exists)return{ok:false,existing:exists,message:'Bạn đã có một khế ước cùng loại đang hoạt động.'};const contract=ctx.coordinator.acceptFactionContract({factionId:ctx.faction.id,type,duration,payment,obligations,penalties});ctx.coordinator.syncToGameState?.();return{ok:true,contract,message:'Đã nhận tông môn ủy thác. Khế ước đã lưu vào Faction V5.'};}
export function getSectQuestHooks(ctx){const h=ctx?.coordinator?.getQuestHooks?.(ctx.faction.id)||[];const normalized=h.map(x=>typeof x==='string'?x:(x?.title||x?.id||'Ủy thác tông môn')).filter(Boolean);return(normalized.length?normalized:['Trừ ma hộ đạo','Tuần tra sơn môn','Thu thập tài nguyên tông môn']).slice(0,3);}
export function getSectDiplomacyRows(ctx,limit=6){const map=new Map();for(const r of ctx?.network?.relations||[]){if(r.a!==ctx.faction.id&&r.b!==ctx.faction.id)continue;map.set(r.id,r);}for(const r of ctx?.coordinator?.diplomacy?.toJSON?.()||[]){if(r.a!==ctx.faction.id&&r.b!==ctx.faction.id)continue;map.set(r.id,r);}return[...map.values()].map(r=>{const otherId=r.a===ctx.faction.id?r.b:r.a,other=ctx.network?.getFaction?.(otherId);return{...r,otherId,otherName:other?.name||otherId};}).slice(0,limit);}
export function createSectModal(scene,{title,subtitle,accent=0xa855f7,background=0x0f0b1e,height=760}={}){scene?.closeModal?.();const width=Number(scene?.scale?.width||scene?.game?.config?.width||540),screenH=Number(scene?.scale?.height||scene?.game?.config?.height||960),pW=Math.min(500,width-24),pH=Math.min(height,screenH-28);const modal=scene.add.container(width/2,screenH/2).setDepth(2000005).setScrollFactor(0),overlay=scene.add.rectangle(0,0,width,screenH,0x000000,.78).setInteractive();modal.add(overlay);const panel=scene.add.graphics();panel.fillStyle(background,.985);panel.fillRoundedRect(-pW/2,-pH/2,pW,pH,14);panel.lineStyle(2,accent,.95);panel.strokeRoundedRect(-pW/2,-pH/2,pW,pH,14);modal.add(panel);modal.add(scene.add.text(0,-pH/2+31,title,{fontFamily:'Cinzel, Philosopher, serif',fontSize:'19px',color:'#fff4bf',fontStyle:'bold',align:'center',wordWrap:{width:pW-44}}).setOrigin(.5));modal.add(scene.add.text(0,-pH/2+61,subtitle||'',{fontFamily:FONT,fontSize:'11px',color:'#e7ddff',align:'center',wordWrap:{width:pW-44}}).setOrigin(.5));const close=()=>{if(!modal?.active)return;modal.destroy(true);if(scene.activeModal===modal)scene.activeModal=null;if(scene.activeModalOverlay===overlay)scene.activeModalOverlay=null;};const closeHit=scene.add.rectangle(0,pH/2-31,156,36,accent,.28).setStrokeStyle(1,accent).setInteractive({useHandCursor:true}),closeTxt=scene.add.text(0,pH/2-31,'✕ ĐÓNG',{fontFamily:FONT,fontSize:'13px',fontStyle:'bold',color:'#ffffff'}).setOrigin(.5);closeHit.on('pointerdown',close);modal.add([closeHit,closeTxt]);scene.activeModal=modal;scene.activeModalOverlay=overlay;return{modal,pW,pH,close,contentTop:-pH/2+92};}
export function addSectInfo(scene,modal,x,y,text,{size='12px',color='#e7ddff',width=440,style='normal'}={}){const t=scene.add.text(x,y,text,{fontFamily:FONT,fontSize:size,color,fontStyle:style,wordWrap:{width,useAdvancedWrap:true},lineSpacing:4});modal.add(t);return t;}
export function addSectActionCard(scene,modal,{y,title,body='',button='THỰC HIỆN',accent=0xa855f7,enabled=true,onPress=null,height=94}={}){const box=scene.add.rectangle(0,y,450,height,0x241747,.92).setStrokeStyle(1,accent,.6);modal.add(box);addSectInfo(scene,modal,-210,y-height/2+10,title,{size:'13px',color:'#fef08a',width:410,style:'bold'});addSectInfo(scene,modal,-210,y-height/2+33,body,{size:'10.5px',color:'#d8cbea',width:300});const btn=scene.add.rectangle(160,y+height/2-22,108,28,enabled?accent:0x334155,enabled?.8:.5).setStrokeStyle(1,enabled?accent:0x64748b).setInteractive({useHandCursor:enabled}),txt=scene.add.text(160,y+height/2-22,button,{fontFamily:FONT,fontSize:'9.5px',fontStyle:'bold',color:enabled?'#ffffff':'#94a3b8'}).setOrigin(.5);modal.add([btn,txt]);if(enabled&&onPress)btn.on('pointerdown',onPress);return{box,btn,txt};}
export function toastSect(scene,result,okIcon='✅'){scene?.showToast?.(`${result?.ok===false?'⚠️':okIcon} ${result?.message||''}`);}
