import { openSectMainHallModal } from './SectMainHallUI.js?v=20261001-org-relations-v40';
import { openSectScriptureModal } from './SectScriptureUI.js?v=20261001-org-relations-v40';
import { openSectAlchemyModal } from './SectAlchemyUI.js?v=20261001-org-relations-v40';
import { openSectForgeModal } from './SectForgeUI.js?v=20261001-org-relations-v40';
import { openSectDisciplineModal } from './SectDisciplineUI.js?v=20261001-org-relations-v40';
import { openSectMissionModal } from './SectMissionUI.js?v=20261001-org-relations-v40';
import { openSectSpiritBeastModal } from './SectSpiritBeastUI.js?v=20261001-org-relations-v40';
import { openSectMartialArenaModal } from './SectMartialArenaUI.js?v=20261001-org-relations-v40';
import { openSectMountainGateModal } from './SectMountainGateUI.js?v=20261001-org-relations-v40';
import { resolveSectContext, joinSect, leaveSect, toastSect } from './SectFactionBridge.js?v=20261001-org-relations-v40';
export class SectHubUIManager{static openBuildingUI(scene,buildingKey,faction){if(!scene)return null;const key=String(buildingKey||'').toLowerCase();if(key.includes('đại điện')||key.includes('chưởng môn')||key.includes('main_hall')||key.includes('truong_thon'))return openSectMainHallModal(scene,faction);if(key.includes('tàng kinh')||key.includes('scripture')||key.includes('kinh các'))return openSectScriptureModal(scene,faction);if(key.includes('luyện đan')||key.includes('alchemy')||key.includes('đan điện')||key.includes('duoc_diem'))return openSectAlchemyModal(scene,faction);if(key.includes('luyện khí')||key.includes('forge')||key.includes('khí phường')||key.includes('tho_ren'))return openSectForgeModal(scene,faction);if(key.includes('chấp pháp')||key.includes('discipline')||key.includes('giới luật'))return openSectDisciplineModal(scene,faction);if(key.includes('nhiệm vụ')||key.includes('mission')||key.includes('tuu_lau'))return openSectMissionModal(scene,faction);if(key.includes('linh thú')||key.includes('beast')||key.includes('thú viên')||key.includes('nong_phu'))return openSectSpiritBeastModal(scene,faction);if(key.includes('diễn võ')||key.includes('arena')||key.includes('võ đài')||key.includes('vo_quan'))return openSectMartialArenaModal(scene,faction);if(key.includes('xuất hành')||key.includes('mountain_gate')||key.includes('sơn môn')||key.includes('cổng')||key.includes('ve_si_cong'))return openSectMountainGateModal(scene,faction);return openSectMainHallModal(scene,faction);}}
export function installSectHubUI(MainGameScene){if(!MainGameScene?.prototype)return;const p=MainGameScene.prototype;if(p.__sectHubUiInstalled)return;p.__sectHubUiInstalled=true;p.getCurrentSectContext=function(factionOverride=null){return resolveSectContext(this,factionOverride);};p.openSectBuildingUI=function(buildingKey,factionOverride=null){const ctx=resolveSectContext(this,factionOverride);if(!ctx){this.showToast?.('⚠️ Khu vực hiện tại không có Tông Môn hợp lệ trong Faction V5.');return null;}return SectHubUIManager.openBuildingUI(this,buildingKey,ctx.faction);};p.joinCurrentSect=function(factionOverride=null){const ctx=resolveSectContext(this,factionOverride);const r=ctx?joinSect(ctx):{ok:false,message:'Không tìm thấy tông môn hợp lệ.'};toastSect(this,r);this.updateHUD?.();return r;};p.leaveCurrentSect=function(factionOverride=null){const ctx=resolveSectContext(this,factionOverride);const r=ctx?leaveSect(ctx):{ok:false,message:'Không tìm thấy tông môn hợp lệ.'};toastSect(this,r);this.updateHUD?.();return r;};}
