(()=>{'use strict';
const PROFILES={LOW:{renderScale:1.5,targetFps:30,enemyNearHz:20,enemyMidHz:8,enemyFarHz:2,maxVfx:36,particleScale:.45,shadowDistance:24},MEDIUM:{renderScale:2.25,targetFps:45,enemyNearHz:30,enemyMidHz:12,enemyFarHz:3,maxVfx:60,particleScale:.7,shadowDistance:40},HIGH:{renderScale:3,targetFps:60,enemyNearHz:60,enemyMidHz:20,enemyFarHz:6,maxVfx:100,particleScale:1,shadowDistance:65}};
function detect(){const mobile=(navigator.maxTouchPoints||0)>1||Math.min(screen.width,screen.height)<820;const memory=Number(navigator.deviceMemory)||0,cores=Number(navigator.hardwareConcurrency)||2;let name=mobile?'MEDIUM':'HIGH';if((memory&&memory<=4)||cores<=4)name='LOW';else if(!mobile&&cores>=8&&(memory===0||memory>=8))name='HIGH';return name;}
let name=detect(),current={...PROFILES[name]},manual=false,samples=[],lastEval=performance.now(),cooldownUntil=0;
function sample(dt){if(manual||!Number.isFinite(dt)||dt<=0)return current;samples.push(1/dt);if(samples.length>240)samples.shift();const now=performance.now();if(now-lastEval<5000||samples.length<60)return current;lastEval=now;const avg=samples.reduce((a,b)=>a+b,0)/samples.length;samples.length=0;if(now<cooldownUntil)return current;if(avg<current.targetFps*.72&&name!=='LOW'){name=name==='HIGH'?'MEDIUM':'LOW';current={...PROFILES[name]};cooldownUntil=now+12000;window.GameEvents&&window.GameEvents.emit('qualityChanged',{name,profile:current,reason:'fps-low'});}else if(avg>current.targetFps*.96&&name==='LOW'){name='MEDIUM';current={...PROFILES[name]};cooldownUntil=now+30000;window.GameEvents&&window.GameEvents.emit('qualityChanged',{name,profile:current,reason:'fps-stable'});}return current;}
function set(next,options={}){if(PROFILES[next]){manual=options.manual!==false;name=next;current={...PROFILES[next]};samples.length=0;window.GameEvents&&window.GameEvents.emit('qualityChanged',{name,profile:current,reason:manual?'manual':'auto'});}return current;}
function setAuto(){manual=false;return set(detect(),{manual:false});}
window.PerformanceProfile={PROFILES,get name(){return name;},get current(){return current;},get manual(){return manual;},sample,set,setAuto,engineScale(){const dpr=Math.max(1,window.devicePixelRatio||1);return dpr/Math.min(dpr,current.renderScale);}};
})();
