import { FACTION_ARCHETYPES, FACTION_POWER_TIERS, FACTION_SCOPES, FACTION_VISIBILITY, FACTION_DATA_LEVELS } from '../core/factionConstants.js';
import { stableFactionId } from '../core/factionIds.js'; import { createFactionDefinition } from '../core/factionDefinitions.js';
import { generatedFactionName } from './factionNaming.js'; import { getTerritoryFactionBudget } from './factionBudget.js';
export function hash32(value){let h=2166136261;for(const ch of String(value)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
export function rand01(seed,salt=''){return hash32(`${seed}:${salt}`)/0xffffffff;}
function pick(list,seed,salt=''){return list[Math.floor(rand01(seed,salt)*list.length)%list.length];}
const TYPES=[FACTION_ARCHETYPES.SECT,FACTION_ARCHETYPES.CULTIVATION_FAMILY,FACTION_ARCHETYPES.DYNASTY,FACTION_ARCHETYPES.MERCHANT_GUILD,FACTION_ARCHETYPES.PROFESSION_GUILD,FACTION_ARCHETYPES.UNDERWORLD,FACTION_ARCHETYPES.LOOSE_CULTIVATOR_ALLIANCE,FACTION_ARCHETYPES.NON_HUMAN_FACTION];
function weightedType(continentKey,seed){const pools={south:[...TYPES,FACTION_ARCHETYPES.SECT,FACTION_ARCHETYPES.CULTIVATION_FAMILY,FACTION_ARCHETYPES.DYNASTY],east:[...TYPES,FACTION_ARCHETYPES.SECT,FACTION_ARCHETYPES.ANCIENT_CLAN,FACTION_ARCHETYPES.MERCHANT_GUILD],west:[...TYPES,FACTION_ARCHETYPES.ANCIENT_CLAN,FACTION_ARCHETYPES.MERCHANT_GUILD,FACTION_ARCHETYPES.LOOSE_CULTIVATOR_ALLIANCE],north:[...TYPES,FACTION_ARCHETYPES.ANCIENT_CLAN,FACTION_ARCHETYPES.NON_HUMAN_FACTION],central:[...TYPES,FACTION_ARCHETYPES.ACADEMY,FACTION_ARCHETYPES.DYNASTY,FACTION_ARCHETYPES.PROFESSION_GUILD]};return pick(pools[continentKey]||TYPES,seed,'weighted-type');}
export function generateFaction({worldSeed='default',territoryId,continentKey='south',slot=0,archetype=null,tier=null,territoryMeta={}}){
 const seed=`${worldSeed}:${territoryId}:${slot}`; const type=archetype||weightedType(continentKey,seed); const powerTier=tier||pick([FACTION_POWER_TIERS.MINOR,FACTION_POWER_TIERS.MINOR,FACTION_POWER_TIERS.MEDIUM,FACTION_POWER_TIERS.LOCAL],seed,'tier'); const name=generatedFactionName(continentKey,type,hash32(seed));
 const id=stableFactionId({scope:'territory',archetype:type,territoryId,slot}); const elements=territoryMeta.elements||[];
 return createFactionDefinition({id,name,archetype:type,scope:FACTION_SCOPES.SECONDARY_TERRITORY,powerTier,continentIds:[continentKey],homeTerritoryId:territoryId,homePrimaryRegionId:territoryMeta.primaryRegionId||null,alignment:type===FACTION_ARCHETYPES.UNDERWORLD?'trung lập/ngầm':type===FACTION_ARCHETYPES.DEMONIC_FACTION?'ma đạo':'trung lập',visibility:type===FACTION_ARCHETYPES.UNDERWORLD?FACTION_VISIBILITY.HIDDEN:FACTION_VISIBILITY.REGIONAL,dataLevel:powerTier===FACTION_POWER_TIERS.MAJOR?FACTION_DATA_LEVELS.GENERATED:FACTION_DATA_LEVELS.BACKGROUND,
 dna:{culture:territoryMeta.theme||continentKey,doctrine:elements[0]||territoryMeta.theme||'tu luyện',elements,expansionism:rand01(seed,'expansion'),riskTolerance:rand01(seed,'risk'),secrecy:type===FACTION_ARCHETYPES.UNDERWORLD?.82+rand01(seed,'secret')*.18:rand01(seed,'secret')*.4,corruption:rand01(seed,'corruption')*.6,resourcePriority:(territoryMeta.products||[]).slice(0,3)},
 basePower:{cultivation:Math.round(25+rand01(seed,'cultivation')*50),military:Math.round(20+rand01(seed,'military')*55),economic:Math.round(15+rand01(seed,'economic')*65),political:Math.round(10+rand01(seed,'political')*60),intelligence:Math.round(10+rand01(seed,'intelligence')*70),infrastructure:Math.round(10+rand01(seed,'infra')*60),prestige:Math.round(15+rand01(seed,'prestige')*60),resourceControl:Math.round(15+rand01(seed,'resource')*70)},meta:{generated:true,worldSeed,slot,sourceTerritoryName:territoryMeta.name||null}});
}
export function generateTerritoryFactionSet({worldSeed='default',territoryId,continentKey='south',civilizationDensity=1,importance=1,territoryMeta={}}){const budget=getTerritoryFactionBudget({continentKey,civilizationDensity,importance});const result=[];let slot=0;const push=(count,type,tier)=>{for(let i=0;i<count;i++)result.push(generateFaction({worldSeed,territoryId,continentKey,slot:slot++,archetype:type,tier,territoryMeta}));};push(budget.majorSlots,null,FACTION_POWER_TIERS.MAJOR);push(budget.mediumSlots,null,FACTION_POWER_TIERS.MEDIUM);push(budget.familySlots,FACTION_ARCHETYPES.CULTIVATION_FAMILY,FACTION_POWER_TIERS.MINOR);push(budget.merchantSlots,FACTION_ARCHETYPES.MERCHANT_GUILD,FACTION_POWER_TIERS.MINOR);push(budget.guildSlots,FACTION_ARCHETYPES.PROFESSION_GUILD,FACTION_POWER_TIERS.MINOR);push(budget.underworldSlots,FACTION_ARCHETYPES.UNDERWORLD,FACTION_POWER_TIERS.MINOR);push(budget.minorSlots,null,FACTION_POWER_TIERS.MINOR);return Object.freeze(result);}
